// Code generated by `aql build --native`. DO NOT EDIT.
package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"

	"github.com/aql-lang/aql/cmd/go/internal/buildrt"
)

//go:embed config.json
var configJSON []byte

func main() {
	var cfg buildrt.Config
	if err := json.Unmarshal(configJSON, &cfg); err != nil {
		fmt.Fprintf(os.Stderr, "error: corrupt embedded config: %s\n", err)
		os.Exit(1)
	}
	os.Exit(buildrt.Main(cfg, os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}
