// Package buildrt is the shared runtime for executing an AQL program and
// printing its residual stack. It is the single implementation of "evaluate
// source, print the result" used by three callers:
//
//   - the `run` / `do` subcommands (via Eval),
//   - a standalone executable produced by `aql build` (self-embedding
//     launcher: cmd/go decodes an appended payload and calls Main),
//   - a `--native` binary generated by `aql build` (its tiny main.go calls
//     Main directly).
//
// Keeping the eval+print core here — depending only on the lang package and
// the standard library — lets the generated binary reuse it without importing
// the heavy `run` package (flag, repl, check).
package buildrt

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	lang "github.com/aql-lang/aql/lang/go"
)

// CompileMode selects which execution engine Eval/Main drives: the
// best-effort bytecode compiler (silent fallback — the default), the
// interpreter (--no-compile), or the bytecode compiler in FORCE mode
// (error if uncompilable).
// It mirrors the run subcommand's mode; run type-aliases this type so there is
// a single source of truth that the generated binary can reference without
// importing run.
type CompileMode int

const (
	// CompileOff runs the interpreter (the `--no-compile` flag).
	CompileOff CompileMode = iota
	// CompileTry runs the bytecode compiler when the program is compilable and
	// silently falls back to the interpreter otherwise — the default.
	CompileTry
	// CompileForce REQUIRES the bytecode path: an uncompilable program (or a VM
	// soundness assertion) aborts with the refusal reason rather than falling
	// back (the `--force-compile` flag).
	CompileForce
)

// langNew is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive the init-error arms of Eval and Main — lang.New only fails on
// registry construction errors that no Options value can provoke.
var langNew = lang.New

// Eval runs source under Options o with the engine selected by mode, then
// writes the residual stack (carriers joined by spaces) to w. This is the body
// the run subcommand's EvalOptionsMode forwards to.
func Eval(w io.Writer, source string, o lang.Options, mode CompileMode) error {
	return EvalColor(w, source, o, mode, false)
}

// EvalColor is Eval with the color decision resolved by the caller
// (lang.ResolveColor over the stream the error will be printed to):
// a structured AqlError renders through the diagnostic renderer with
// the ANSI palette; color=false keeps the byte-identical plain text.
func EvalColor(w io.Writer, source string, o lang.Options, mode CompileMode, color bool) error {
	return EvalReport(w, nil, nil, source, o, mode, color)
}

// EvalReport is Eval plus the -compile-report surface, a compilation-refusal
// warning stream, and caller-resolved color. When report is non-nil, the
// instance's detached-stamp attribution (lang.AQL.StampReport —
// design/RUNTIME-STAMPING.0.md) is printed to it after the run, one line per
// runtime-constructed callback with its outcome or refusal reason. When warn is
// non-nil and the default compile-try mode falls back because the WHOLE program
// refused to compile, a one-line performance warning naming the refusal reason
// is printed to it (a refusal runs on the slower interpreter). color renders a
// structured AqlError through the ANSI diagnostic renderer; color=false keeps
// the byte-identical plain text.
func EvalReport(w, report, warn io.Writer, source string, o lang.Options, mode CompileMode, color bool) error {
	a, err := langNew(o)
	if err != nil {
		return fmt.Errorf("init error: %s", err)
	}
	runErr := runAndPrint(w, warn, a, source, mode, color)
	if report != nil {
		PrintStampReport(report, a.StampReport())
	}
	return runErr
}

// PrintStampReport renders stamp attribution events one per line. An empty
// report still prints a header line so `-compile-report` under -no-compile
// (never armed, nil events) tells the user why it is empty.
func PrintStampReport(w io.Writer, events []lang.StampEvent) {
	if len(events) == 0 {
		fmt.Fprintln(w, "compile-report: no runtime-stamp attempts (interpreter mode, or no runtime-constructed callbacks)")
		return
	}
	for _, ev := range events {
		name := ev.Name
		if name == "" {
			name = "(anonymous fn)"
		}
		where := ""
		if ev.Pos.Row > 0 {
			where = fmt.Sprintf(" @ %d:%d", ev.Pos.Row, ev.Pos.Col)
		}
		if ev.Stamped {
			fmt.Fprintf(w, "compile-report: stamped %s%s\n", name, where)
		} else {
			reason := ev.Reason
			if reason == "" {
				reason = "body refused the stored-fn compile"
			}
			fmt.Fprintf(w, "compile-report: refused %s%s — %s\n", name, where, reason)
		}
	}
}

// runAndPrint executes source on an already-constructed instance (so callers
// that need to configure the instance first — e.g. seed an in-memory file
// system for bundled imports — can do so before running) and prints the
// residual stack exactly as the run subcommand does.
func runAndPrint(w, warn io.Writer, a *lang.AQL, source string, mode CompileMode, color bool) error {
	var result []any
	var err error
	switch mode {
	case CompileForce:
		result, err = a.RunCompiledStrict(source)
	case CompileTry:
		var reason string
		result, _, reason, err = a.RunCompiledReason(source)
		// Post-Stage-J a genuine refusal RETURNS an error instead of the
		// library silently re-running (plan Phase 11, C2). Try-mode's
		// contract is graceful degradation, so the CLI performs the
		// fallback ITSELF — explicitly and visibly: warn once, naming the
		// first offending construct, then interpret. The fallback moved
		// from the library (hidden) to this caller (attributed).
		if reason != "" {
			if warn != nil {
				fmt.Fprintf(warn, "warning: bytecode compilation refused, ran on the interpreter (slower): %s\n", reason)
			}
			result, err = a.RunInterp(source)
		}
	default:
		// -no-compile: the interpreter EXPLICITLY (Stage J flips the public
		// Run to the compiled path; this mode's contract is the tree-walker).
		result, err = a.RunInterp(source)
	}
	if err != nil {
		// A structured diagnostic re-renders with the ANSI palette when
		// the caller resolved color for the output stream; anything else
		// (and the color-off path) keeps the historical plain text.
		var ae *lang.AqlError
		if color && errors.As(err, &ae) {
			return fmt.Errorf("error: %s", ae.Render(lang.RenderOpts{Color: true}))
		}
		return fmt.Errorf("error: %s", err)
	}

	if len(result) > 0 {
		parts := make([]string, len(result))
		for i, v := range result {
			parts[i] = fmt.Sprint(v)
		}
		fmt.Fprintln(w, strings.Join(parts, " "))
	}
	return nil
}

// Config is the fully-resolved description of a program baked into a
// standalone executable: the entry source, every bundled file import, and the
// engine settings (registry, seed, compile mode, tape options) frozen at build
// time. It is JSON-serialised into the appended payload (self-embed) and
// referenced by the generated main (`--native`).
type Config struct {
	// Source is the entry program's source text.
	Source string `json:"source"`
	// EntryDir is the absolute directory of the entry file at build time. It
	// is the working directory the in-memory file system resolves relative
	// imports against, so the keys in Files (which are absolute paths) match
	// what loadFileModule asks for at run time.
	EntryDir string `json:"entryDir,omitempty"`
	// Files maps absolute path -> file bytes for the entry and every
	// transitively-imported .aql file. Empty when the program imports only
	// built-in aql: modules (which are compiled into the runtime).
	Files map[string][]byte `json:"files,omitempty"`
	// Registry is the registry path baked in (lang.Options.Registry).
	Registry string `json:"registry,omitempty"`
	// Seed is the random seed baked in (lang.Options.Seed).
	Seed int64 `json:"seed,omitempty"`
	// Compile is the bytecode compile-mode baked in.
	Compile CompileMode `json:"compile,omitempty"`
	// OptionsBlob is the raw --options jsonic string baked in, parsed at run
	// time exactly as the run subcommand parses --options.
	OptionsBlob string `json:"optionsBlob,omitempty"`
}

// Main is the entrypoint a standalone executable runs: build lang.Options from
// the baked Config, seed an in-memory file system with any bundled files, run
// the entry source, and map errors to a process exit code. args/stdin are
// accepted (and currently unused by the runtime) so a future AQL program that
// reads process args or stdin keeps working without changing this signature.
func Main(cfg Config, _ []string, _ io.Reader, stdout, stderr io.Writer) int {
	o := lang.Options{Registry: cfg.Registry, Seed: cfg.Seed}
	if cfg.OptionsBlob != "" {
		m, err := lang.ParseOptions(cfg.OptionsBlob)
		if err != nil {
			fmt.Fprintf(stderr, "error: %s\n", err)
			return 1
		}
		if err := lang.ApplyOptions(&o, m); err != nil {
			fmt.Fprintf(stderr, "error: %s\n", err)
			return 1
		}
	}

	a, err := langNew(o)
	if err != nil {
		fmt.Fprintf(stderr, "init error: %s\n", err)
		return 1
	}

	if len(cfg.Files) > 0 {
		mem := lang.NewMemFileOps()
		if cfg.EntryDir != "" {
			mem.Cwd = cfg.EntryDir
		}
		for path, data := range cfg.Files {
			mem.Files[path] = data
		}
		a.SetFileOps(mem)
	}

	if err := runAndPrint(stdout, stderr, a, cfg.Source, cfg.Compile, lang.ResolveColor(stderr, "auto")); err != nil {
		fmt.Fprintf(stderr, "%s\n", err)
		return 1
	}
	return 0
}

// magic marks the trailer of a self-embedding executable. It is intentionally
// unlikely to occur in a vanilla binary's tail and is exactly magicSize bytes.
var magic = []byte("AQLEXEC\x01")

// Footer layout appended after the JSON payload: magic (8 bytes) followed by
// the payload length as a big-endian uint64 (8 bytes). Detection reads these
// footerSize bytes from the end of the file.
const (
	magicSize  = 8
	lenSize    = 8
	footerSize = magicSize + lenSize
)

// EncodePayload returns the bytes to append to a copied host binary: the
// JSON-encoded Config followed by the fixed trailer (magic + 8-byte big-endian
// payload length). Detection reads the trailer from the end of the file.
// jsonMarshal is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive EncodePayload's marshal-failure arm, which is unreachable with
// the plain Config shape.
var jsonMarshal = json.Marshal

func EncodePayload(cfg Config) ([]byte, error) {
	body, err := jsonMarshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("encode payload: %w", err)
	}
	footer := make([]byte, footerSize)
	copy(footer[:magicSize], magic)
	binary.BigEndian.PutUint64(footer[magicSize:], uint64(len(body)))
	return append(body, footer...), nil
}

// DecodePayload extracts the embedded Config from a binary's raw bytes. ok is
// false (with a nil error) when the trailer magic is absent — i.e. this is a
// plain aql binary, not a built executable. A present-but-corrupt trailer
// returns an error.
func DecodePayload(image []byte) (cfg Config, ok bool, err error) {
	if len(image) < footerSize {
		return Config{}, false, nil
	}
	footer := image[len(image)-footerSize:]
	if !bytes.Equal(footer[:magicSize], magic) {
		return Config{}, false, nil
	}
	n := binary.BigEndian.Uint64(footer[magicSize:])
	end := len(image) - footerSize
	if uint64(end) < n {
		return Config{}, false, fmt.Errorf("embedded payload: length %d exceeds image", n)
	}
	body := image[end-int(n) : end]
	if err := json.Unmarshal(body, &cfg); err != nil {
		return Config{}, false, fmt.Errorf("embedded payload: %w", err)
	}
	return cfg, true, nil
}

// fileStat is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive ReadEmbeddedPayload's stat-failure arm — Stat on a freshly
// opened local file does not fail on a healthy host.
var fileStat = (*os.File).Stat

// fileReadAt is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive ReadEmbeddedPayload's read-failure arms, which the preceding
// size checks make unreachable with real files.
var fileReadAt = (*os.File).ReadAt

// ReadEmbeddedPayload returns the embedded Config if exePath is a built
// executable. ok is false (nil error) for a plain aql binary. Only the trailing
// footer is read first, and the payload only when the magic matches — so the
// common case (a stock aql binary, checked on every CLI invocation) costs a
// small tail read, not a full scan of the multi-megabyte binary.
func ReadEmbeddedPayload(exePath string) (cfg Config, ok bool, err error) {
	f, err := os.Open(exePath)
	if err != nil {
		return Config{}, false, fmt.Errorf("read self: %w", err)
	}
	defer f.Close()

	info, err := fileStat(f)
	if err != nil {
		return Config{}, false, fmt.Errorf("read self: %w", err)
	}
	size := info.Size()
	if size < footerSize {
		return Config{}, false, nil
	}

	footer := make([]byte, footerSize)
	if _, err := fileReadAt(f, footer, size-footerSize); err != nil {
		return Config{}, false, fmt.Errorf("read self: %w", err)
	}
	if !bytes.Equal(footer[:magicSize], magic) {
		return Config{}, false, nil
	}

	n := int64(binary.BigEndian.Uint64(footer[magicSize:]))
	if n < 0 || n > size-footerSize {
		return Config{}, false, fmt.Errorf("embedded payload: length %d exceeds image", n)
	}
	body := make([]byte, n)
	if _, err := fileReadAt(f, body, size-footerSize-n); err != nil {
		return Config{}, false, fmt.Errorf("embedded payload: %w", err)
	}
	if err := json.Unmarshal(body, &cfg); err != nil {
		return Config{}, false, fmt.Errorf("embedded payload: %w", err)
	}
	return cfg, true, nil
}

// AbsDir returns the absolute directory of a file path, for keying bundled
// files and setting the in-memory working directory consistently.
func AbsDir(file string) (string, error) {
	abs, err := filepath.Abs(file)
	if err != nil {
		return "", err
	}
	return filepath.Dir(abs), nil
}
