// Public entry point for the TypeScript port of borueng.

export { BoruError } from './error.ts'
export { cap } from './capability.ts'
export {
  CheckState,
  carrierResults,
  joinCarriers,
  severityFor,
  stripToCarriers,
  toCarrier,
} from './check.ts'
export { coerceBoolean } from './coretype.ts'
export type { CheckDiagnostic, CheckSeverity } from './check.ts'
export {
  CodeBuilder,
  OpCallNative,
  OpCallNativePoly,
  OpFallback,
  OpForNext,
  OpForSetup,
  OpJmp,
  OpJmpIfFalse,
  OpMakeList,
  OpMakeMap,
  OpPushConst,
  OpPushLocal,
  OpStoreLocal,
  OpTrap,
  disassemble,
} from './bytecode.ts'
export type { FallbackSpan, Op, PolyRef, Program, SigRef, TrapSpec } from './bytecode.ts'
export { EmitState } from './emit.ts'
export type {
  BranchEvent,
  CallEvent,
  Event,
  FallbackEvent,
  Fragment,
  LoopEvent,
  MakeListEvent,
  MakeMapEvent,
  Operand,
  SiteCounts,
  TrapEvent,
} from './emit.ts'
export { finalize } from './lower.ts'
export type { FinalizeResult } from './lower.ts'
export { runProgram } from './vm.ts'
export { compile, compileCheck, runCompiled } from './compile.ts'
export type { RunCompiledResult } from './compile.ts'
export { Engine } from './engine.ts'
export type { FunctionEntry } from './registry.ts'
export { Registry } from './registry.ts'
export type {
  Handler,
  NativeFunc,
  NativeSig,
  ReturnsFunc,
  Signature,
} from './signature.ts'
export {
  signatureScore,
  sortSignatures,
} from './signature.ts'
export type { BoruType } from './type.ts'
export type { SugarInfo, SugarKind } from './value.ts'
export { sugarExpansion } from './sugar.ts'
export {
  TAbsent,
  TAny,
  TAtom,
  TBigDecimal,
  TBigInteger,
  TBoolean,
  TDecimal,
  TDisjunct,
  TEnum,
  TError,
  TFloat,
  TFnUndef,
  TForward,
  TFunction,
  TIdeal,
  TInspect,
  TInterpString,
  TInteger,
  TList,
  TMap,
  TMark,
  TMove,
  TNegation,
  TNever,
  TNode,
  TNone,
  TNumber,
  TClass,
  TOpenParen,
  TOptions,
  TPathon,
  TReach,
  TRecord,
  TScalar,
  TCloseParen,
  TEnd,
  TSplice,
  TStore,
  TString,
  TStringEmpty,
  TStringProper,
  TSugar,
  TTable,
  TType,
  TWord,
  TXml,
  builtinRank,
  newType,
  typeNameTable,
} from './type.ts'
export {
  ChildType,
  ClassTypeInfo,
  OptionsData,
  OrderedMap,
  Value,
  newAny,
  newAtom,
  newBoolean,
  newCarrier,
  newConstrainedWord,
  newDynamicCarrier,
  newDecimal,
  newDisjunct,
  newEnum,
  newFloat,
  newFnDef,
  newFnUndef,
  newForwardMarker,
  newInspect,
  newInterpString,
  newInteger,
  newList,
  newMap,
  asSugar,
  isCloseParen,
  isEnd,
  isOpenParen,
  isSugar,
  newCloseParen,
  newEnd,
  newMark,
  newMove,
  newClassType,
  newNone,
  newOpenParen,
  newSugar,
  renderSugar,
  newOptions,
  newParenExpr,
  newString,
  newTypedList,
  newTypedMap,
  newTypeLiteral,
  newWord,
  newXml,
  newXmlInterp,
  withQuoted,
} from './value.ts'
export type {
  FnDefInfo,
  FnParam,
  FnSig,
  ForwardMarker,
  InterpSegment,
  MarkInfo,
  MoveInfo,
  WordInfo,
  XmlAttrTmpl,
  XmlChildTmpl,
  XmlElement,
  XmlTmpl,
} from './value.ts'
