// Spec-driven tests, mirroring aqleng/go/spec_test.go.
//
// Reads the SAME .tsv files at ../test/spec/ relative to this
// project (i.e. aqleng/test/spec/) and runs each row through the
// TypeScript engine. Uses the built-in node:test runner (Node 24+);
// the project relies on Node's experimental type-stripping so the
// .ts source executes without a transpile step.

import { describe, it } from 'node:test'
import { strict as assert } from 'node:assert'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  AqlError,
  Engine,
  type Handler,
  type NativeFunc,
  Registry,
  TAny,
  TAtom,
  TBoolean,
  TDecimal,
  TInteger,
  TNone,
  TString,
  TList,
  TWord,
  Value,
  type FnParam,
  type WordInfo,
  newAtom,
  newBoolean,
  newDecimal,
  newFnDef,
  newInteger,
  newList,
  newMark,
  newMove,
  newString,
  newTypeLiteral,
  newWord,
  withQuoted,
  typeNameTable,
} from './index.ts'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const SPEC_DIR = path.resolve(__dirname, '..', '..', 'test', 'spec')

// Counter for unique mark IDs generated by `replay`.
let replayCounter = 0

function registerSpecWords(r: Registry): void {
  const intHandler =
    (op: (a: bigint, b: bigint) => bigint): Handler =>
    (args) =>
      [newInteger(op(args[0]!.asInteger(), args[1]!.asInteger()))]

  const reg = (fn: NativeFunc): void => r.registerNativeFunc(fn)

  reg({
    name: 'add',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a + b) }],
  })
  reg({
    name: 'sub',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a - b) }],
  })
  reg({
    name: 'mul',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a * b) }],
  })
  reg({
    name: 'neg',
    signatures: [
      {
        args: [TInteger],
        handler: (args) => [newInteger(-args[0]!.asInteger())],
      },
    ],
  })
  reg({
    name: 'dup',
    signatures: [
      {
        args: [TAny],
        handler: (args) => [args[0]!, args[0]!],
      },
    ],
  })
  reg({
    name: 'swap',
    signatures: [
      {
        args: [TAny, TAny],
        // Under the unified §1.4 dispatch rule, args[0] is the top
        // of the stack and args[1] is the next-deeper. The splice
        // writes the handler's return slice in source order, so
        // returning [args[0], args[1]] places the old top at the
        // deeper position and the old next-deeper at the top — the
        // two values come out swapped on the stack.
        handler: (args) => [args[0]!, args[1]!],
      },
    ],
  })
  reg({
    name: 'drop',
    signatures: [
      {
        args: [TAny],
        handler: () => [],
      },
    ],
  })
  reg({
    name: 'concat',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString, TString],
        handler: (args) => [newString(args[0]!.asString() + args[1]!.asString())],
      },
    ],
  })
  reg({
    name: 'not',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TBoolean],
        handler: (args) => [newBoolean(!args[0]!.asBoolean())],
      },
    ],
  })
  reg({
    name: 'describe',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        handler: (args) => [newString(`int:${args[0]!.asInteger().toString()}`)],
      },
      {
        args: [TString],
        handler: (args) => [newString(`str:${args[0]!.asString()}`)],
      },
    ],
  })
  reg({
    name: 'tag',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny],
        handler: () => [newString('any')],
      },
      {
        args: [TInteger],
        handler: () => [newString('specific')],
      },
    ],
  })

  // fact, code, route: §1.1 literal-pattern dispatch via patterns.
  // Each declares a specific-value overload first plus a catch-all.
  reg({
    name: 'fact',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        patterns: new Map([[0, newInteger(0n)]]),
        handler: () => [newInteger(1n)],
      },
      {
        args: [TInteger],
        handler: (args) => [newInteger(args[0]!.asInteger())],
      },
    ],
  })
  reg({
    name: 'code',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        patterns: new Map([[0, newInteger(99n)]]),
        handler: () => [newString('ninety-nine')],
      },
      {
        args: [TInteger],
        handler: () => [newString('general')],
      },
    ],
  })
  reg({
    name: 'route',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString],
        patterns: new Map([[0, newString('admin')]]),
        handler: () => [newString('matched-admin')],
      },
      {
        args: [TString],
        handler: () => [newString('other')],
      },
    ],
  })

  // trip: 3-arg integer formatter. Default barrier = N so all
  // position-mixing arrangements (all-forward through all-stack)
  // bind sig[0..2] to the same source-order args.
  reg({
    name: 'trip',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger, TInteger],
        handler: (args) =>
          [newString(
            `${args[0]!.asInteger().toString()},${args[1]!.asInteger().toString()},${args[2]!.asInteger().toString()}`,
          )],
      },
    ],
  })

  // pair: mixed-barrier sig [Integer | Integer]. Forward fills
  // sig[0]; sig[1] must come from the stack. The handler formats
  // "args[0]:args[1]" so the binding is visible in the output.
  reg({
    name: 'pair',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger],
        barrierPos: 1,
        handler: (args) =>
          [newString(`${args[0]!.asInteger().toString()}:${args[1]!.asInteger().toString()}`)],
      },
    ],
  })

  // length, first: list-aware test words for list.tsv.
  reg({
    name: 'length',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => [newInteger(BigInt(args[0]!.asList().length))],
      },
    ],
  })
  reg({
    name: 'first',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => {
          const lst = args[0]!.asList()
          if (lst.length === 0) return [newTypeLiteral(TNone)]
          return [lst[0]!]
        },
      },
    ],
  })

  // def: spec-subset code-body binding. Captures `def NAME body`
  // where NAME arrives as a Word token (no /q machinery in this
  // runner's tokenizer) and body is any value — typically a List
  // literal that becomes a callable code body. The handler pushes
  // the body onto the def stack under NAME.
  reg({
    name: 'def',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TWord, TAny],
        noEvalArgs: new Set([1]),
        handler: (args, _ctx, _stk, registry) => {
          const w = args[0]!.asWord()
          registry.pushDef(w.name, args[1]!)
          return []
        },
      },
    ],
  })

  // fn: builds a function definition value from
  // `fn [ params ] [ returns ] [ body ]`. Each param is a single
  // Word token of the form `name:Type` (the spec tokenizer is
  // whitespace-only so we don't get a separate `:` token). The
  // handler parses each param, resolves the type via the type-name
  // table, and produces a TFunction Value the engine dispatches
  // when the surrounding `def` binding is later invoked.
  reg({
    name: 'fn',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList, TList, TList],
        noEvalArgs: new Set([0, 1, 2]),
        handler: (args) => {
          const paramsList = args[0]!.asList()
          const returnsList = args[1]!.asList()
          const body = args[2]!.asList()
          const params = paramsList.map((p) => parseFnParam(p))
          const returns = returnsList.map((r) => parseFnReturn(r))
          return [newFnDef({ params, returns, body })]
        },
      },
    ],
  })

  // quote: capture the next forward token as data.
  //   sig [TWord]: convert Word→Atom (so `quote dup` yields atom(dup)
  //                even when dup is a registered function — the TWord
  //                slot tells shouldDeferDispatch to keep the Word
  //                rather than dispatch it).
  //   sig [TAny]:  catch-all passthrough (`quote 5` → 5,
  //                `quote [1 2]` → [1 2]).
  reg({
    name: 'quote',
    forwardPrecedence: true,
    // The TAny slot needs noEvalArgs so a List arg arrives raw
    // rather than auto-evaluating before the handler sees it.
    signatures: [
      {
        args: [TWord],
        handler: (args) => [newAtom(args[0]!.asWord().name)],
      },
      {
        args: [TAny],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const v = args[0]!
          if (v.vType.matches(TList) && v.isConcrete()) {
            return [withQuoted(v)]
          }
          return [v]
        },
      },
    ],
  })

  // end is a pure boundary keyword handled by Engine.run; registering
  // it as a 0-arg fallback isn't required, but we also don't register
  // it as a normal native — the engine intercepts the Word at the
  // pointer and removes / fires accordingly (see Engine.stepEnd).

  // args: 0-arg word that returns the current fn-call's argument
  // frame as a list. dispatchFnDef pushes the matched args (in sig
  // order) before running the body so bodies can reference
  // positional args by index without naming each param. Empty list
  // when there's no active fn call.
  reg({
    name: 'args',
    forwardPrecedence: false,
    signatures: [
      {
        args: [],
        handler: (_args, _ctx, _stk, registry) => {
          const top = registry.topArgs()
          return [newList(top ? [...top] : [], { eval: false })]
        },
      },
    ],
  })

  // replay: takes a body list, emits Mark + body + Move so the body
  // executes once, then the Move replays it — net effect: body runs
  // twice. Demonstrates the mark/move plumbing without pulling in
  // for/while continuation semantics.
  reg({
    name: 'replay',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const body = args[0]!.asList()
          replayCounter++
          const id = `__replay_${replayCounter}`
          return [newMark(id, [...body]), ...body, newMove(id)]
        },
      },
    ],
  })

  // Simple-value defs the def.tsv spec references. A word whose name
  // is in the def stack is substituted by its value before normal
  // dispatch, provided the value isn't an FnDef / ObjectType.
  r.pushDef('pi', newInteger(3n))
  r.pushDef('tau', newInteger(6n))
  r.pushDef('greeting', newString('hello'))
}

// ── Tokenizer ─────────────────────────────────────────────────────────────

interface TokenStream {
  s: string
  i: number
}

function tokenize(s: string): Value[] {
  const stream: TokenStream = { s, i: 0 }
  const result = readTokens(stream, null)
  if (stream.i < stream.s.length) {
    throw new Error(`tokenize: unexpected ']' at ${stream.i}`)
  }
  return result
}

/**
 * Read tokens from `stream` until end-of-string or the matching close
 * bracket `until` (the character `]` for list bodies). Returns the
 * collected Values. Lists nest recursively — `[ [ 1 ] 2 ]` becomes
 * a TList containing a TList of Integer(1) plus an Integer(2).
 */
function readTokens(stream: TokenStream, until: ']' | null): Value[] {
  const out: Value[] = []
  while (stream.i < stream.s.length) {
    while (stream.i < stream.s.length && (stream.s[stream.i] === ' ' || stream.s[stream.i] === '\t')) {
      stream.i++
    }
    if (stream.i >= stream.s.length) break

    if (stream.s[stream.i] === '"') {
      let j = stream.i + 1
      while (j < stream.s.length && stream.s[j] !== '"') j++
      if (j >= stream.s.length) throw new Error(`unterminated string at ${stream.i}`)
      out.push(newString(stream.s.slice(stream.i + 1, j)))
      stream.i = j + 1
      continue
    }

    let j = stream.i
    while (j < stream.s.length && stream.s[j] !== ' ' && stream.s[j] !== '\t') j++
    const tok = stream.s.slice(stream.i, j)
    stream.i = j

    if (tok === '[') {
      const elems = readTokens(stream, ']')
      // Tokenizer-built lists default to eval=true so auto-evaluation
      // fires when they're consumed as a word arg, mirroring the Go
      // parser's NewEvalList semantics.
      out.push(newList(elems, { eval: true }))
      continue
    }
    if (tok === ']') {
      if (until !== ']') {
        throw new Error(`tokenize: unmatched ']' at ${stream.i - 1}`)
      }
      return out
    }

    switch (tok) {
      case 'true':
        out.push(newBoolean(true))
        continue
      case 'false':
        out.push(newBoolean(false))
        continue
      case 'null':
        out.push(newTypeLiteral(TNone))
        continue
    }
    if (/^-?\d+$/.test(tok)) {
      out.push(newInteger(BigInt(tok)))
      continue
    }
    if (/^-?\d+\.\d+$/.test(tok)) {
      out.push(newDecimal(Number.parseFloat(tok)))
      continue
    }
    // /-suffix modifiers — at the call site, force stack-only or
    // forward-only dispatch (/s, /f) regardless of the sig's declared
    // barrierPos, and produce an Atom from a bare word (/q, the short
    // form of `(quote name)`). Modifiers stack in any order: foo/sq ≡
    // foo/qs ≡ foo/q (q dominates; other modifiers are accepted but
    // ignored on the resulting Atom). Mirrors parseWord in eng/parser.
    const parsed = parseModifierSuffix(tok)
    if (parsed.quote) {
      out.push(newAtom(parsed.name))
    } else {
      out.push(newWordWithModifiers(parsed.name, parsed.forceStack, parsed.forceForward))
    }
  }
  if (until === ']') {
    throw new Error(`tokenize: unterminated list literal '['`)
  }
  return out
}

function newWordWithModifiers(name: string, forceStack: boolean, forceForward: boolean): Value {
  if (!forceStack && !forceForward) return newWord(name)
  const wi: WordInfo = { name }
  if (forceStack) wi.forceStack = true
  if (forceForward) wi.forceForward = true
  return new Value(TWord, wi)
}

type ModifierSuffix = {
  name: string
  forceStack: boolean
  forceForward: boolean
  quote: boolean
}

// parseModifierSuffix scans the trailing /-suffix on a word token.
// Mirrors parseWord in eng/parser/parse.go: digits (argCount), 'f'
// (forceForward), 's' (forceStack), 'q' (quote → Atom). Modifiers can
// appear in any order; f/s are mutually exclusive; each letter at most
// once; digits run contiguously. If the suffix is unrecognised or
// malformed, the entire token is treated as a plain word.
function parseModifierSuffix(tok: string): ModifierSuffix {
  const idx = tok.lastIndexOf('/')
  const noop: ModifierSuffix = { name: tok, forceStack: false, forceForward: false, quote: false }
  if (idx < 0 || idx >= tok.length - 1) return noop
  const mod = tok.slice(idx + 1)
  let forceStack = false
  let forceForward = false
  let quote = false
  let seenDigits = false
  let valid = true
  let i = 0
  while (i < mod.length) {
    const c = mod[i]!
    if (c >= '0' && c <= '9') {
      if (seenDigits) {
        valid = false
        break
      }
      let j = i
      while (j < mod.length && mod[j]! >= '0' && mod[j]! <= '9') j++
      // The argCount value itself is not propagated to the TS spec
      // tokenizer's Word — the kernel test fixtures don't exercise
      // multi-arity /N dispatch through this path — but we still must
      // consume the digit run so subsequent letters parse correctly.
      seenDigits = true
      i = j
      continue
    }
    if (c === 'f') {
      if (forceForward || forceStack) {
        valid = false
        break
      }
      forceForward = true
    } else if (c === 's') {
      if (forceForward || forceStack) {
        valid = false
        break
      }
      forceStack = true
    } else if (c === 'q') {
      if (quote) {
        valid = false
        break
      }
      quote = true
    } else {
      valid = false
      break
    }
    i++
  }
  if (!valid) return noop
  return { name: tok.slice(0, idx), forceStack, forceForward, quote }
}

/**
 * Parse one fn-param token. The spec tokenizer produces a Word per
 * whitespace-split chunk, so a typed param like `n:Integer` arrives
 * as a single Word with name `n:Integer`. Split on the first `:`,
 * resolve the type name, build an FnParam.
 */
function parseFnParam(v: Value): FnParam {
  if (!v.isWord()) {
    throw new Error(`fn: expected param Word, got ${v.toString()}`)
  }
  const w = v.asWord()
  const idx = w.name.indexOf(':')
  if (idx < 0) {
    throw new Error(`fn: param ${JSON.stringify(w.name)} missing ':TypeName' suffix`)
  }
  const name = w.name.slice(0, idx)
  const typeName = w.name.slice(idx + 1)
  const type = typeNameTable().get(typeName)
  if (!type) throw new Error(`fn: unknown type ${JSON.stringify(typeName)}`)
  return { name, type }
}

/** Parse one fn-return token (a bare TypeName Word). */
function parseFnReturn(v: Value) {
  if (!v.isWord()) throw new Error(`fn: expected return type Word`)
  const w = v.asWord()
  const type = typeNameTable().get(w.name)
  if (!type) throw new Error(`fn: unknown return type ${JSON.stringify(w.name)}`)
  return type
}

function renderStack(stack: Value[]): string {
  return stack.map(renderValue).join(' ')
}

function renderValue(v: Value): string {
  if (v.data === null) {
    if (v.vType.equal(TNone)) return 'null'
    return v.vType.toString()
  }
  if (v.vType.matches(TInteger)) return v.asInteger().toString()
  if (v.vType.matches(TDecimal)) return String(v.asDecimal())
  if (v.vType.matches(TString)) return JSON.stringify(v.asString())
  if (v.vType.matches(TBoolean)) return String(v.asBoolean())
  // Atoms render as `name/q` — the canonical short form (mirrors
  // eng/canon.go::CanonValue).
  if (v.vType.equal(TAtom)) return `${v.asAtom()}/q`
  return v.toString()
}

// ── Test harness ─────────────────────────────────────────────────────────

interface SpecRow {
  lineNum: number
  input: string
  expected: string
}

function parseSpec(file: string): SpecRow[] {
  const text = fs.readFileSync(file, 'utf8')
  const rows: SpecRow[] = []
  text.split('\n').forEach((raw, idx) => {
    const lineNum = idx + 1
    const trimmed = raw.replace(/[ \t]+$/, '')
    if (trimmed === '' || trimmed.startsWith('#')) return
    const parts = trimmed.split('\t')
    if (parts.length < 2) {
      throw new Error(`${file}:L${lineNum}: malformed row, want at least input<TAB>expected`)
    }
    rows.push({
      lineNum,
      input: parts[0]!.trim(),
      expected: parts[1]!.trim(),
    })
  })
  return rows
}

function runRow(row: SpecRow): { ok: true; got: string } | { ok: false; err: string } {
  const r = new Registry()
  registerSpecWords(r)

  let values: Value[]
  try {
    values = tokenize(row.input)
  } catch (e) {
    return { ok: false, err: `tokenize: ${(e as Error).message}` }
  }

  try {
    const result = new Engine(r).run(values)
    return { ok: true, got: renderStack(result) }
  } catch (e) {
    if (e instanceof AqlError) {
      return { ok: false, err: e.message }
    }
    return { ok: false, err: `unexpected: ${(e as Error).message}` }
  }
}

const specFiles = fs
  .readdirSync(SPEC_DIR)
  .filter((f) => f.endsWith('.tsv'))
  .sort()

describe('spec', () => {
  for (const file of specFiles) {
    const fullPath = path.join(SPEC_DIR, file)
    const rows = parseSpec(fullPath)
    describe(file.replace(/\.tsv$/, ''), () => {
      for (const row of rows) {
        const name = `L${row.lineNum} ${row.input}`
        it(name, () => {
          const result = runRow(row)
          if (row.expected.startsWith('ERROR:')) {
            const want = row.expected.slice('ERROR:'.length)
            assert.ok(!result.ok, `expected error containing ${JSON.stringify(want)}`)
            if (!result.ok && want !== '') {
              assert.ok(
                result.err.toLowerCase().includes(want.toLowerCase()),
                `error ${JSON.stringify(result.err)} does not contain ${JSON.stringify(want)}`,
              )
            }
            return
          }
          assert.ok(result.ok, result.ok ? '' : `unexpected error: ${result.err}`)
          if (result.ok) {
            assert.equal(result.got, row.expected)
          }
        })
      }
    })
  }
})
