// Shared spec fixtures: the word registry, tokenizer, and .tsv corpus
// loader used by BOTH the interpreter spec gate (spec.test.ts) and the
// compiled differential gate (corpus.test.ts). Extracted verbatim from the
// original spec.test.ts so the two gates run the identical fixture set.

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

import { canon } from './canon.ts'
import {
  coerceBoolean,
  isRecordShape,
  isTypeBody,
  isValueOfType,
  pathOf,
  typeOf,
} from './coretype.ts'
import { makeIdealHandler, makeScalarHandler, makeScalarOptsHandler } from './make.ts'
import {
  AqlError,
  Engine,
  type Handler,
  type NativeFunc,
  Registry,
  TAny,
  TAtom,
  TBoolean,
  TDecimal,
  TInteger,
  TNever,
  TNone,
  TNumber,
  TString,
  TList,
  TMap,
  TArray,
  TIdeal,
  TNode,
  TObject,
  TScalar,
  TType,
  TWord,
  Value,
  type FnParam,
  type FnSig,
  type InterpSegment,
  type WordInfo,
  type XmlChildTmpl,
  type XmlElement,
  type XmlTmpl,
  newAtom,
  newBoolean,
  newConstrainedWord,
  newDecimal,
  newDynamicCarrier,
  newDisjunct,
  newEnum,
  newFnDef,
  newFnUndef,
  newFloat,
  newInspect,
  newInterpString,
  newInteger,
  newList,
  newMap,
  newMark,
  newMove,
  newNone,
  newObjectType,
  ObjectTypeInfo,
  newParenExpr,
  newString,
  newTypedList,
  newTypedMap,
  newXml,
  newXmlInterp,
  OrderedMap,
  newTypeLiteral,
  newWord,
  withQuoted,
  typeNameTable,
} from './index.ts'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const SPEC_DIR = path.resolve(__dirname, '..', '..', 'spec')

// Counter for unique mark IDs generated by `replay`.
let replayCounter = 0

// Bare type-name → Type lookup, used by the tokenizer to resolve
// uppercase type words (Integer, List, …) to type literals.
const typeTable = typeNameTable()

function registerSpecWords(r: Registry): void {
  const intHandler =
    (op: (a: bigint, b: bigint) => bigint): Handler =>
    (args) =>
      [newInteger(op(args[0]!.asInteger(), args[1]!.asInteger()))]

  const reg = (fn: NativeFunc): void => r.registerNativeFunc(fn)

  reg({
    name: 'add',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a + b) }],
  })
  reg({
    name: 'sub',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a - b) }],
  })
  reg({
    name: 'mul',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a * b) }],
  })
  reg({
    name: 'neg',
    signatures: [
      {
        args: [TInteger],
        handler: (args) => [newInteger(-args[0]!.asInteger())],
      },
    ],
  })
  reg({
    name: 'dup',
    signatures: [
      {
        args: [TAny],
        handler: (args) => [args[0]!, args[0]!],
        returns: [TAny, TAny],
      },
    ],
  })
  reg({
    name: 'swap',
    signatures: [
      {
        args: [TAny, TAny],
        // Under the unified §1.4 dispatch rule, args[0] is the top
        // of the stack and args[1] is the next-deeper. The splice
        // writes the handler's return slice in source order, so
        // returning [args[0], args[1]] places the old top at the
        // deeper position and the old next-deeper at the top — the
        // two values come out swapped on the stack.
        handler: (args) => [args[0]!, args[1]!],
        returns: [TAny, TAny],
      },
    ],
  })
  reg({
    name: 'drop',
    signatures: [
      {
        args: [TAny],
        handler: () => [],
        returns: [],
      },
    ],
  })
  reg({
    name: 'concat',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString, TString],
        handler: (args) => [newString(args[0]!.asString() + args[1]!.asString())],
      },
    ],
  })
  // not / and / or — Boolean sigs plus an Any-coercing fallback,
  // mirroring registerEngSpecBoolean (CoerceBoolean).
  const notH: Handler = (args) => [newBoolean(!coerceBoolean(args[0]!))]
  const andH: Handler = (args) => [coerceBoolean(args[1]!) ? args[0]! : args[1]!]
  const orH: Handler = (args) => [coerceBoolean(args[1]!) ? args[1]! : args[0]!]
  reg({
    name: 'not',
    forwardPrecedence: true,
    signatures: [{ args: [TBoolean], handler: notH }, { args: [TAny], handler: notH }],
  })
  reg({
    name: 'and',
    forwardPrecedence: true,
    signatures: [
      { args: [TBoolean, TBoolean], handler: andH },
      { args: [TAny, TAny], handler: andH },
    ],
  })
  reg({
    name: 'or',
    signatures: [
      { args: [TBoolean, TBoolean], barrierPos: 1, handler: orH },
      { args: [TAny, TAny], barrierPos: 1, handler: orH },
    ],
  })
  reg({
    name: 'describe',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        handler: (args) => [newString(`int:${args[0]!.asInteger().toString()}`)],
      },
      {
        args: [TString],
        handler: (args) => [newString(`str:${args[0]!.asString()}`)],
      },
    ],
  })
  reg({
    name: 'tag',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny],
        handler: () => [newString('any')],
      },
      {
        args: [TInteger],
        handler: () => [newString('specific')],
      },
    ],
  })

  // fact, code, route: §1.1 literal-pattern dispatch via patterns.
  // Each declares a specific-value overload first plus a catch-all.
  reg({
    name: 'fact',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        patterns: new Map([[0, newInteger(0n)]]),
        handler: () => [newInteger(1n)],
      },
      {
        args: [TInteger],
        handler: (args) => [newInteger(args[0]!.asInteger())],
      },
    ],
  })
  reg({
    name: 'code',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        patterns: new Map([[0, newInteger(99n)]]),
        handler: () => [newString('ninety-nine')],
      },
      {
        args: [TInteger],
        handler: () => [newString('general')],
      },
    ],
  })
  reg({
    name: 'route',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString],
        patterns: new Map([[0, newString('admin')]]),
        handler: () => [newString('matched-admin')],
      },
      {
        args: [TString],
        handler: () => [newString('other')],
      },
    ],
  })

  // trip: 3-arg integer formatter. Default barrier = N so all
  // position-mixing arrangements (all-forward through all-stack)
  // bind sig[0..2] to the same source-order args.
  reg({
    name: 'trip',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger, TInteger],
        handler: (args) =>
          [newString(
            `${args[0]!.asInteger().toString()},${args[1]!.asInteger().toString()},${args[2]!.asInteger().toString()}`,
          )],
      },
    ],
  })

  // pair: mixed-barrier sig [Integer | Integer]. Forward fills
  // sig[0]; sig[1] must come from the stack. The handler formats
  // "args[0]:args[1]" so the binding is visible in the output.
  reg({
    name: 'pair',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger],
        barrierPos: 1,
        handler: (args) =>
          [newString(`${args[0]!.asInteger().toString()}:${args[1]!.asInteger().toString()}`)],
      },
    ],
  })

  // length, first: list-aware test words for list.tsv.
  reg({
    name: 'length',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => [newInteger(BigInt(args[0]!.asList().length))],
      },
    ],
  })
  reg({
    name: 'first',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => {
          const lst = args[0]!.asList()
          if (lst.length === 0) return [newNone()]
          return [lst[0]!]
        },
      },
    ],
  })

  // ── Forth-style stack manipulators (stack.tsv) ───────────────────
  // All stack-only (barrierPos 0): args[0] is the top, args[1] the
  // next-deeper, etc. The handler returns the splice-form replacement
  // in source order. Mirrors registerEngSpecStack. (dup/swap/drop are
  // registered above; the rest are added here.)
  const stackOp = (name: string, argCount: number, fn: (a: Value[]) => Value[]): void => {
    // Probe the handler to learn its TRUE result count so the checker models
    // the arity faithfully (Go annotates these via NativeSig.Returns). A
    // non-1 count makes the bytecode recorder refuse (multi/zero-result) and
    // fall back; a 1-result reorder (nip) stays compilable.
    const returns = fn(new Array<Value>(argCount).fill(newNone())).map(() => TAny)
    reg({
      name,
      signatures: [
        { args: new Array<typeof TAny>(argCount).fill(TAny), barrierPos: 0, handler: (a) => fn(a), returns },
      ],
    })
  }
  stackOp('over', 2, (a) => [a[1]!, a[0]!, a[1]!])
  stackOp('rot', 3, (a) => [a[1]!, a[0]!, a[2]!])
  stackOp('nip', 2, (a) => [a[0]!])
  stackOp('tuck', 2, (a) => [a[0]!, a[1]!, a[0]!])
  stackOp('dup2', 2, (a) => [a[1]!, a[0]!, a[1]!, a[0]!])
  stackOp('swap2', 4, (a) => [a[1]!, a[0]!, a[3]!, a[2]!])
  stackOp('drop2', 2, () => [])
  stackOp('over2', 4, (a) => [a[3]!, a[2]!, a[1]!, a[0]!, a[3]!, a[2]!])

  // ── q-suffixed fixtures (barrier.tsv, numbers.tsv, typeof.tsv, …) ──
  // These mirror test/go/engspec/engspec_test.go::registerSpecWords.
  // The eng/spec corpus references the q-suffixed names so they don't
  // collide with any production word set.
  const toFloat = (v: Value): number =>
    v.vType.matches(TInteger) ? Number(v.asInteger()) : v.asFloat()
  const numericBinary =
    (intOp: (a: bigint, b: bigint) => bigint, floatOp: (a: number, b: number) => number): Handler =>
    (args) => {
      if (args[0]!.vType.matches(TInteger) && args[1]!.vType.matches(TInteger)) {
        return [newInteger(intOp(args[0]!.asInteger(), args[1]!.asInteger()))]
      }
      return [newFloat(floatOp(toFloat(args[0]!), toFloat(args[1]!)))]
    }
  const numberPair = [TNumber, TNumber]

  reg({
    name: 'addq',
    forwardPrecedence: true,
    signatures: [{ args: numberPair, handler: numericBinary((a, b) => b + a, (a, b) => b + a) }],
  })
  reg({
    name: 'subq',
    forwardPrecedence: true,
    signatures: [{ args: numberPair, handler: numericBinary((a, b) => b - a, (a, b) => b - a) }],
  })
  reg({
    name: 'mulq',
    forwardPrecedence: true,
    signatures: [{ args: numberPair, handler: numericBinary((a, b) => b * a, (a, b) => b * a) }],
  })
  reg({
    name: 'negq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TNumber],
        barrierPos: 1,
        handler: (args) =>
          args[0]!.vType.matches(TInteger)
            ? [newInteger(-args[0]!.asInteger())]
            : [newFloat(-args[0]!.asFloat())],
      },
    ],
  })
  reg({
    name: 'concatq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString, TString],
        handler: (args) => [newString(args[1]!.asString() + args[0]!.asString())],
      },
    ],
  })
  reg({
    name: 'describeq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], handler: (args) => [newString(`int:${args[0]!.asInteger()}`)] },
      { args: [TString], handler: (args) => [newString(`str:${args[0]!.asString()}`)] },
    ],
  })
  reg({
    name: 'tagq',
    forwardPrecedence: true,
    signatures: [
      { args: [TAny], handler: () => [newString('any')] },
      { args: [TInteger], handler: () => [newString('specific')] },
    ],
  })
  reg({
    name: 'factq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], patterns: new Map([[0, newInteger(0n)]]), handler: () => [newInteger(1n)] },
      { args: [TInteger], handler: (args) => [newInteger(args[0]!.asInteger())] },
    ],
  })
  reg({
    name: 'codeq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], patterns: new Map([[0, newInteger(99n)]]), handler: () => [newString('ninety-nine')] },
      { args: [TInteger], handler: () => [newString('general')] },
    ],
  })
  reg({
    name: 'routeq',
    forwardPrecedence: true,
    signatures: [
      { args: [TString], patterns: new Map([[0, newString('admin')]]), handler: () => [newString('matched-admin')] },
      { args: [TString], handler: () => [newString('other')] },
    ],
  })
  reg({
    name: 'tripq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger, TInteger],
        handler: (args) =>
          [newString(`${args[0]!.asInteger()},${args[1]!.asInteger()},${args[2]!.asInteger()}`)],
      },
    ],
  })
  reg({
    name: 'pairq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger],
        barrierPos: 1,
        handler: (args) => [newString(`${args[0]!.asInteger()}:${args[1]!.asInteger()}`)],
      },
    ],
  })
  // nilq — a 0-arg word (barrier 0).
  reg({
    name: 'nilq',
    signatures: [{ args: [], barrierPos: 0, handler: () => [newString('nil')] }],
  })
  // flexq — two forward-eligible overloads of arity 1 and 2.
  reg({
    name: 'flexq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], handler: (args) => [newString(`one:${args[0]!.asInteger()}`)] },
      {
        args: [TInteger, TInteger],
        handler: (args) => [newString(`two:${args[0]!.asInteger()},${args[1]!.asInteger()}`)],
      },
    ],
  })
  // Fixed-arity Integer formatters with an intrinsic barrier at the
  // numeric-suffix position; handler renders args in sig order.
  const intArgsFmt: Handler = (args) =>
    [newString(args.map((a) => a.asInteger().toString()).join(','))]
  const intArity = (name: string, n: number, barrier: number): void => {
    reg({
      name,
      forwardPrecedence: true,
      signatures: [{ args: new Array<typeof TInteger>(n).fill(TInteger), barrierPos: barrier, handler: intArgsFmt }],
    })
  }
  intArity('tri1q', 3, 1)
  intArity('tri2q', 3, 2)
  intArity('quad1q', 4, 1)
  intArity('quadq', 4, 2)
  intArity('quad3q', 4, 3)
  intArity('quintq', 5, 3)
  intArity('hexq', 6, 3)
  intArity('septq', 7, 4)
  reg({
    name: 'lengthq',
    forwardPrecedence: true,
    signatures: [{ args: [TList], handler: (args) => [newInteger(BigInt(args[0]!.asList().length))] }],
  })
  reg({
    name: 'firstq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => {
          const lst = args[0]!.asList()
          return lst.length === 0 ? [newNone()] : [lst[0]!]
        },
      },
    ],
  })
  reg({
    name: 'replayq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const body = args[0]!.asList()
          replayCounter++
          const id = `__replayq_${replayCounter}`
          return [newMark(id, [...body]), ...body, newMove(id)]
        },
      },
    ],
  })

  // do — evaluate a list body in a sub-engine, or deep-evaluate the
  // list-valued slots of a map. Mirrors registerEngSpecDo. The arg
  // arrives unevaluated (noEvalArgs); a bare List/Map type literal fails
  // the concrete-container match and surfaces a signature_error.
  const doEvalMapValue = (v: Value): Value => {
    if (v.isMap()) {
      const src = v.asMap()
      const out = new OrderedMap()
      for (const k of src.keys()) out.set(k, doEvalMapValue(src.get(k)!))
      return newMap(out)
    }
    if (v.vType.matches(TList) && Array.isArray(v.data)) {
      const residual = new Engine(r).run([...v.asList()])
      if (residual.length === 1) return residual[0]!
      return newList(residual, { eval: false })
    }
    return v
  }
  reg({
    name: 'do',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TMap],
        noEvalArgs: new Set([0]),
        handler: (args) => [doEvalMapValue(args[0]!)],
      },
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // runInCheckMode makes `do` TRANSPARENT to the recorder: its body
        // runs in a sub-engine that records into the shared trace, and the
        // body residual (carriers with provenance) becomes do's result — so
        // `do [1 addq 2]` compiles inline with no do-event, exactly like a
        // fn body. In value mode the same handler just runs the body.
        runInCheckMode: true,
        handler: (args) => new Engine(r).run([...args[0]!.asList()]),
      },
    ],
  })

  // make — scalar coercion. The eng/spec make.tsv rows exercise the
  // scalar targets (String/Integer/Number/Float/Boolean/Atom). The
  // [Scalar, Any] sig with typeArgs on arg0 forces a type-literal
  // target. Object/Array/Options overloads are added by a later
  // increment. Mirrors registerEngSpecMake (scalar slice).
  reg({
    name: 'make',
    forwardPrecedence: true,
    signatures: [
      { args: [TObject, TAny, TObject], handler: () => unsupportedMake('Object prototype') },
      { args: [TScalar, TMap, TAny], typeArgs: new Set([0]), handler: (a) => makeScalarOptsHandler(a) },
      { args: [TAny, TAny, TMap], handler: () => unsupportedMake('with-opts') },
      { args: [TArray, TList], typeArgs: new Set([0]), handler: () => unsupportedMake('Array') },
      { args: [TIdeal, TMap], typeArgs: new Set([0]), handler: (a) => makeIdealHandler(a) },
      { args: [TScalar, TAny], typeArgs: new Set([0]), handler: (a) => makeScalarHandler(a) },
      { args: [TAny, TAny], handler: () => unsupportedMake('generic') },
    ],
  })
  // get / set — kernel-container signatures (the handlers cover the
  // Node map/list case; their full sig list is what inspect renders).
  // Mirrors registerEngSpecStorage.
  const getNodeH: Handler = (args) => {
    const key = args[0]!
    const c = args[1]!
    if (key.vType.matches(TInteger) && Array.isArray(c.data)) {
      const i = Number(key.asInteger())
      const lst = c.asList()
      return [i >= 0 && i < lst.length ? lst[i]! : newNone()]
    }
    if (c.data instanceof OrderedMap) {
      const k = key.vType.equal(TAtom) ? key.asAtom() : key.asString()
      const v = c.asMap().get(k)
      return [v ?? newNone()]
    }
    return [newNone()]
  }
  reg({
    name: 'get',
    signatures: [
      { args: [TString, TObject], barrierPos: 1, handler: getNodeH },
      { args: [TString, TNode], barrierPos: 1, handler: getNodeH },
      { args: [TInteger, TArray], barrierPos: 1, handler: getNodeH },
      { args: [TInteger, TObject], barrierPos: 1, handler: getNodeH },
      { args: [TInteger, TNode], barrierPos: 1, handler: getNodeH },
      { args: [TAtom, TObject], barrierPos: 1, handler: getNodeH },
      { args: [TAtom, TNode], barrierPos: 1, handler: getNodeH },
      { args: [TAny, TNone], barrierPos: 1, handler: () => [newNone()] },
    ],
  })
  reg({
    name: 'set',
    forwardPrecedence: true,
    signatures: [
      { args: [TString, TAny, TObject], handler: () => unsupportedMake('set') },
      { args: [TInteger, TAny, TArray], handler: () => unsupportedMake('set') },
      { args: [TAtom, TAny, TObject], handler: () => unsupportedMake('set') },
    ],
  })
  // refine — the uniform type constructor (its sig list is what inspect
  // renders; structural construction is a follow-up).
  reg({
    name: 'refine',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny, TNode],
        noEvalArgs: new Set([1]),
        handler: (args) => {
          const base = args[0]!
          // refine Record [ {k:T} … ] merges the pair-maps into a
          // record-shape map.
          if (base.data === null && base.vType.leaf() === 'Record' && Array.isArray(args[1]!.data)) {
            const om = new OrderedMap()
            for (const pair of args[1]!.asList()) {
              const m = pair.asMap()
              for (const k of m.keys()) om.set(k, m.get(k)!)
            }
            return [newMap(om)]
          }
          // refine Object {field:Type …} — a fresh object type with the
          // base Object as parent. refine Base {…} extends an existing
          // object type, inheriting its fields. The struct name is empty
          // until a `def Name …` binding stamps it.
          if (base.data === null && base.vType.leaf() === 'Object' && args[1]!.isMap()) {
            return [buildObjectType('Object', new OrderedMap(), args[1]!)]
          }
          if (base.data instanceof ObjectTypeInfo && args[1]!.isMap()) {
            return [buildObjectType(base.data.path, base.data.fields, args[1]!)]
          }
          return unsupportedMake('refine')
        },
      },
      { args: [TAny], handler: () => unsupportedMake('refine') },
    ],
  })

  // inspect — render a word's signatures or a type's structure as an
  // inspection map. Mirrors registerEngSpecInspect (buildInspection /
  // buildTypeInspection). The word form fires when the arg is a Word
  // naming a registered native; otherwise the type form runs.
  reg({
    name: 'inspect',
    forwardPrecedence: true,
    signatures: [
      {
        // Word form: the Atom quoteArgs slot captures the name as data
        // (so the matcher does not dispatch a registered word like `dup`).
        args: [TAtom],
        quoteArgs: new Set([0]),
        handler: (args, _ctx, _stk, registry) => {
          const name = args[0]!.asAtom()
          const fn = registry.lookup(name)
          if (fn) return [buildWordInspection(name, fn)]
          const top = registry.topOfDefStack(name)
          if (top !== undefined) return [buildDefinedInspection(name, top)]
          const unk = new OrderedMap()
          unk.set('name', newString(name))
          unk.set('kind', newWord('unknown'))
          unk.set('signatures', newList([], { eval: false }))
          return [newInspect(unk)]
        },
      },
      { args: [TAny], handler: (args) => [buildTypeInspection(args[0]!)] },
    ],
  })

  // word VALUE — wraps an (unevaluated) value as a code body. In this
  // TS subset an unquoted list bound via def already splices its
  // elements at the use site (Engine.stepWord path 2), so `word` is the
  // identity that defers evaluation of its argument. Mirrors the Go
  // `word`/__SP splice fixture for forth.tsv.
  reg({
    name: 'word',
    forwardPrecedence: true,
    // runInCheckMode so the word-body list is produced in the record pass and
    // bound by def; a later reference splices the body inline, which records
    // its events (the macro is transparent to the recorder, like do/def).
    signatures: [
      { args: [TAny], noEvalArgs: new Set([0]), runInCheckMode: true, handler: (args) => [args[0]!] },
    ],
  })

  // def: spec-subset code-body binding. Captures `def NAME body`
  // where NAME arrives as a Word token (no /q machinery in this
  // runner's tokenizer) and body is any value — typically a List
  // literal that becomes a callable code body. The handler pushes
  // the body onto the def stack under NAME.
  reg({
    name: 'def',
    forwardPrecedence: true,
    signatures: [
      // Map-destructuring form `def {…} value` — its signature is part
      // of def's canonical surface (so inspect reports it); the corpus
      // doesn't exercise its runtime, so it falls through to a stub.
      {
        args: [TMap, TAny],
        noEvalArgs: new Set([1]),
        handler: () => {
          throw new AqlError('unsupported', 'def: map-destructuring binding not ported')
        },
      },
      {
        // Name-binding form. The Atom quoteArgs slot captures the name
        // word (a constrained `NAME:[…]` word is kept intact so its
        // constraint survives — see the matcher's quoteArgs capture).
        args: [TAtom, TAny],
        quoteArgs: new Set([0]),
        noEvalArgs: new Set([1]),
        // Bind in check mode too, so later references resolve (otherwise
        // every `def x … x` cascades into undefined_word) — the binding is
        // a prerequisite for analysis, exactly as in Go. The bound carrier
        // carries the stripped-literal origin, so a compiled reference bakes
        // the value.
        runInCheckMode: true,
        returns: [],
        handler: (args, _ctx, _stk, registry) => {
          const nameArg = args[0]!
          const nameWord = nameArg.isWord() ? nameArg.asWord() : { name: nameArg.asAtom(), constraint: undefined }
          const name = nameWord.name
          const value = args[1]!
          // A digit-first name is a malformed number, never a name.
          if (/^-?\d/.test(name)) {
            throw new AqlError('invalid_numeric_literal', `invalid numeric literal: ${name}`, name)
          }
          // Container-typed binding `def NAME:[…]` / `def NAME:{…}`: the
          // tokenizer attached the constraint shape to the name word. The
          // value must satisfy it, else def-time validation fails.
          if (nameWord.constraint !== undefined) {
            if (!isValueOfType(value, nameWord.constraint)) {
              throw new AqlError(
                'type_error',
                `def ${name}: value ${value.toString()} does not satisfy ${nameWord.constraint.toString()}`,
                name,
              )
            }
            // A typed-name binding stores the value as data — a plain
            // list binds inert (non-splicing); `word` is needed to splice.
            const bound =
              value.vType.matches(TList) && Array.isArray(value.data) && !value.quoted
                ? newList(value.asList(), { eval: false })
                : value
            registry.pushDef(name, bound)
            return []
          }
          // Typed binding `def x:Type v`: the name carries a `:Constraint`
          // suffix (a simple scalar type, a value pattern, or a bound
          // type name). The value must satisfy the constraint.
          const colon = name.indexOf(':')
          if (colon > 0) {
            const bindName = name.slice(0, colon)
            const constraintStr = name.slice(colon + 1)
            if (constraintStr !== '' && constraintStr[0] !== '{' && constraintStr[0] !== '[') {
              const t = typeTable.get(constraintStr)
              const constraint =
                t !== undefined
                  ? newTypeLiteral(t)
                  : (registry.topOfDefStack(constraintStr) ?? atomicValue(constraintStr))
              if (!isValueOfType(value, constraint)) {
                throw new AqlError(
                  'type_error',
                  `def ${bindName}: value ${value.toString()} does not satisfy ${constraintStr}`,
                  bindName,
                )
              }
              registry.pushDef(bindName, value)
              return []
            }
          }
          // A capitalised name binding an object type stamps the struct
          // name onto it, so `inspect Name` reports struct:Name and a
          // child type can record `Object/Name` as its parent path.
          if (value.data instanceof ObjectTypeInfo && value.data.name === '') {
            value.data.name = name
          }
          registry.pushDef(name, value)
          return []
        },
      },
    ],
  })

  // fn: builds a function-definition value from a single list of
  // triples `fn [ [params] [returns] [body] … ]`, mirroring the Go
  // `fn` fixture (ParseFnDef). The named-triple form (params is a list
  // of `name:Type` words) yields a callable FnDef; other forms (the
  // flat `fn [ Integer Integer [body] ]` and multi-sig shapes) produce
  // a Function value sufficient for typeof/is. fnsig builds a
  // FunctionSignature value.
  reg({
    name: 'fn',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // Build the fn value in check mode so def binds it and a later call
        // inlines the body (dispatchFnDefCheck/analyseFnBody), exactly as the
        // compiled-test fn fixture does.
        runInCheckMode: true,
        handler: (args) => {
          const elems = args[0]!.asList()
          if (elems.length === 0 || elems.length % 3 !== 0) {
            throw new AqlError('fn_invalid_spec', `fn: list length must be a non-zero multiple of 3`)
          }
          const sigs: FnSig[] = []
          for (let i = 0; i < elems.length; i += 3) {
            sigs.push(parseFnTriple(elems[i]!, elems[i + 1]!, elems[i + 2]!))
          }
          return [newFnDef({ sigs })]
        },
      },
    ],
  })
  reg({
    name: 'fnsig',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const elems = args[0]!.asList()
          if (elems.length === 0 || elems.length % 2 !== 0) {
            throw new AqlError('fn_invalid_spec', `fnsig: list length must be a non-zero multiple of 2`)
          }
          return [newFnUndef(elems)]
        },
      },
    ],
  })

  // quote: capture the next forward token as data.
  //   sig [Atom] quoteArgs: captures the upcoming Word as an Atom name
  //                (so `quote dup` yields dup/q).
  //   sig [TAny]:  catch-all passthrough (`quote 5` → 5,
  //                `quote [1 2]` → (quote [1 2])).
  reg({
    name: 'quote',
    forwardPrecedence: true,
    // The TAny slot needs noEvalArgs so a List arg arrives raw
    // rather than auto-evaluating before the handler sees it.
    signatures: [
      {
        args: [TAtom],
        quoteArgs: new Set([0]),
        handler: (args) => [args[0]!],
      },
      {
        args: [TAny],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const v = args[0]!
          if (v.vType.matches(TList) && v.isConcrete()) {
            return [withQuoted(v)]
          }
          return [v]
        },
      },
    ],
  })

  // end is a pure boundary keyword handled by Engine.run; registering
  // it as a 0-arg fallback isn't required, but we also don't register
  // it as a normal native — the engine intercepts the Word at the
  // pointer and removes / fires accordingly (see Engine.stepEnd).

  // args: 0-arg word that returns the current fn-call's argument
  // frame as a list. dispatchFnDef pushes the matched args (in sig
  // order) before running the body so bodies can reference
  // positional args by index without naming each param. Empty list
  // when there's no active fn call.
  reg({
    name: 'args',
    forwardPrecedence: false,
    signatures: [
      {
        args: [],
        // `args` reads the current call's positional-arg frame — a
        // context-dependent value the compiled stream does not maintain (an
        // inlined fn body has no frame). Refuse to compile it so any program
        // using it falls back to the interpreter. Mirrors Go marking args/__pa
        // as a meta (uncompilable) site.
        returnsFn: (_a, r) => {
          r.check.emit?.markUncompilable('args: context-dependent word not compilable')
          return [newDynamicCarrier(TList)]
        },
        handler: (_args, _ctx, _stk, registry) => {
          const top = registry.topArgs()
          return [newList(top ? [...top] : [], { eval: false })]
        },
      },
    ],
  })

  // break / continue — outside a loop they bubble out as an error,
  // mirroring registerEngSpecDefinition's flow-ctrl stubs.
  reg({
    name: 'break',
    signatures: [
      {
        args: [],
        handler: () => {
          throw new AqlError('flow_error', 'break outside loop')
        },
      },
    ],
  })
  reg({
    name: 'continue',
    signatures: [
      {
        args: [],
        handler: () => {
          throw new AqlError('flow_error', 'continue outside loop')
        },
      },
    ],
  })

  // undef NAME — pop the named binding. A capitalised (type) name with
  // no binding is a type_error; a lowercase unbound name is a harmless
  // no-op. Mirrors registerEngSpecDefinition::undef.
  reg({
    name: 'undef',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TWord],
        handler: (args, _ctx, _stk, registry) => {
          const name = args[0]!.asWord().name
          const has = registry.topOfDefStack(name) !== undefined
          if (/^[A-Z]/.test(name) && !has) {
            throw new AqlError('type_error', `undef ${name}: no such type binding`, name)
          }
          if (has) registry.popDef(name)
          return []
        },
      },
    ],
  })

  // replay: takes a body list, emits Mark + body + Move so the body
  // executes once, then the Move replays it — net effect: body runs
  // twice. Demonstrates the mark/move plumbing without pulling in
  // for/while continuation semantics.
  reg({
    name: 'replay',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const body = args[0]!.asList()
          replayCounter++
          const id = `__replay_${replayCounter}`
          return [newMark(id, [...body]), ...body, newMove(id)]
        },
      },
    ],
  })

  // typeof / pathof / is — type-introspection fixtures, mirroring
  // test/go/engspec/engspec_test.go::registerEngSpecTypeWords. They
  // delegate to the ported algorithm primitives in coretype.ts.
  reg({
    name: 'typeof',
    forwardPrecedence: true,
    signatures: [{ args: [TAny], handler: (args) => [typeOf(args[0]!)] }],
  })
  reg({
    name: 'pathof',
    forwardPrecedence: true,
    signatures: [{ args: [TAny], typeArgs: new Set([0]), handler: (args) => [pathOf(args[0]!)] }],
  })
  // tor — union (disjunct) of two type values. enum — a fixed
  // enumeration. tand — type intersection (only its sig is inspected
  // by the corpus, so a minimal handler suffices). Mirror
  // registerEngSpecTypeOps + registerEngSpecTypeWords::enum.
  const flattenAlts = (v: Value): Value[] => (v.isDisjunct() ? v.asDisjunct().alternatives : [v])
  reg({
    name: 'tor',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny, TAny],
        barrierPos: 1,
        handler: (args) => {
          const alts = [...flattenAlts(args[1]!), ...flattenAlts(args[0]!)]
          const seen = new Set<string>()
          const out: Value[] = []
          for (const a of alts) {
            const k = canon([a])
            if (!seen.has(k)) {
              seen.add(k)
              out.push(a)
            }
          }
          if (out.length === 1) return [out[0]!]
          return [newDisjunct(out)]
        },
      },
    ],
  })
  reg({
    name: 'tand',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny, TAny],
        barrierPos: 1,
        handler: (args) =>
          canon([args[0]!]) === canon([args[1]!]) ? [args[0]!] : [newTypeLiteral(TNever)],
      },
    ],
  })
  reg({
    name: 'enum',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          // A typed list `[:T …]` carries a child constraint each
          // element must satisfy; a plain list has none.
          const list = args[0]!
          const hasChild = list.isTypedList()
          const child = hasChild ? list.asChildType().child : undefined
          const elems = hasChild ? list.asChildType().elements : list.asList()
          const alts = elems.map((e) => {
            const v = e.isWord() ? newAtom(e.asWord().name) : e
            if (child !== undefined && !isValueOfType(v, child)) {
              throw new AqlError(
                'type_error',
                `enum: element ${v.toString()} does not satisfy ${child.vType.leaf()}`,
              )
            }
            return v
          })
          return [newEnum(alts)]
        },
      },
    ],
  })
  reg({
    name: 'is',
    signatures: [
      {
        args: [TAny, TAny],
        barrierPos: 1,
        handler: (args) => [newBoolean(isValueOfType(args[1]!, args[0]!))],
      },
    ],
  })

  // Simple-value defs the def.tsv spec references. A word whose name
  // is in the def stack is substituted by its value before normal
  // dispatch, provided the value isn't an FnDef / ObjectType.
  r.pushDef('pi', newInteger(3n))
  r.pushDef('tau', newInteger(6n))
  r.pushDef('greeting', newString('hello'))
}

// ── Tokenizer ─────────────────────────────────────────────────────────────

interface TokenStream {
  s: string
  i: number
}

function tokenize(s: string): Value[] {
  const stream: TokenStream = { s, i: 0 }
  const result = readTokens(stream, null)
  if (stream.i < stream.s.length) {
    throw new Error(`tokenize: unexpected ']' at ${stream.i}`)
  }
  return result
}

/**
 * Read tokens from `stream` until end-of-string or the matching close
 * bracket `until` (the character `]` for list bodies). Returns the
 * collected Values. Lists nest recursively — `[ [ 1 ] 2 ]` becomes
 * a TList containing a TList of Integer(1) plus an Integer(2).
 */
function readTokens(stream: TokenStream, until: ']' | null): Value[] {
  const out: Value[] = []
  while (stream.i < stream.s.length) {
    while (stream.i < stream.s.length && (stream.s[stream.i] === ' ' || stream.s[stream.i] === '\t')) {
      stream.i++
    }
    if (stream.i >= stream.s.length) break

    // String literals. The eng/spec corpus uses single quotes (the
    // canonical AQL form); double quotes are also accepted. The closing
    // quote must match the opener.
    const quote = stream.s[stream.i]
    if (quote === '"' || quote === "'") {
      let j = stream.i + 1
      while (j < stream.s.length && stream.s[j] !== quote) j++
      if (j >= stream.s.length) throw new Error(`unterminated string at ${stream.i}`)
      out.push(newString(stream.s.slice(stream.i + 1, j)))
      stream.i = j + 1
      continue
    }

    if (stream.s[stream.i] === '{') {
      stream.i++
      out.push(readMap(stream))
      continue
    }

    // XML literal: `<tag …>…</tag>` or `<tag …/>`.
    if (stream.s[stream.i] === '<' && /[A-Za-z]/.test(stream.s[stream.i + 1] ?? '')) {
      out.push(parseXml(stream))
      continue
    }

    // Backtick template string: `lit${expr}lit…` (holes and nested
    // backticks balance).
    if (stream.s[stream.i] === '`') {
      const end = endOfBacktick(stream.s, stream.i)
      out.push(parseBacktick(stream.s.slice(stream.i + 1, end - 1)))
      stream.i = end
      continue
    }

    // Structural delimiters are always their own token, even when not
    // whitespace-separated (`[1 2 3]`, `${{a:1}}`).
    const ch = stream.s[stream.i]!
    if (ch === '[') {
      stream.i++
      out.push(makeListFromElems(readTokens(stream, ']')))
      continue
    }
    if (ch === ']') {
      if (until !== ']') {
        throw new Error(`tokenize: unmatched ']' at ${stream.i}`)
      }
      stream.i++
      return out
    }
    if (ch === '(' || ch === ')') {
      out.push(newWord(ch))
      stream.i++
      continue
    }
    if (ch === '}') {
      throw new Error(`tokenize: unmatched '}' at ${stream.i}`)
    }

    let j = stream.i
    while (j < stream.s.length && !isTokenBoundary(stream.s[j]!)) j++
    const tok = stream.s.slice(stream.i, j)
    stream.i = j
    // A binding name with a container constraint — `NAME:[…]` / `NAME:{…}`
    // — tokenises as `NAME:` immediately abutting an opening bracket. The
    // constraint shape rides along on the name word so `def` can validate.
    if (tok.length > 1 && tok.endsWith(':') && (stream.s[stream.i] === '[' || stream.s[stream.i] === '{')) {
      const open = stream.s[stream.i]!
      stream.i++
      const constraint = open === '[' ? makeListFromElems(readTokens(stream, ']')) : readMap(stream)
      out.push(newConstrainedWord(tok.slice(0, -1), constraint))
      continue
    }
    // `quote`/`inspect` capture the upcoming WORD lexically — the real
    // parser hands them the source token before it becomes a boolean
    // literal. So `true`/`false` immediately after one arrive as Words
    // (`quote true` → true/q; `inspect true` → an unknown-word report),
    // not the boolean value.
    const prev = out[out.length - 1]
    if (
      (tok === 'true' || tok === 'false') &&
      prev !== undefined &&
      prev.isWord() &&
      (prev.asWord().name === 'quote' || prev.asWord().name === 'inspect')
    ) {
      out.push(newWord(tok))
      continue
    }
    out.push(atomicValue(tok))
  }
  if (until === ']') {
    throw new Error(`tokenize: unterminated list literal '['`)
  }
  return out
}

// readMap parses a `{ key:value … }` map body. The opening `{` has
// already been consumed. Keys run up to the `:`; the value immediately
// following may itself be a string, list, map, or atomic token.
function readMap(stream: TokenStream): Value {
  const m = new OrderedMap()
  const s = stream.s
  let child: Value | undefined
  for (;;) {
    while (stream.i < s.length && (s[stream.i] === ' ' || s[stream.i] === '\t')) stream.i++
    if (stream.i >= s.length) throw new Error(`tokenize: unterminated map literal '{'`)
    if (s[stream.i] === '}') {
      stream.i++
      break
    }
    let k = stream.i
    while (k < s.length && s[k] !== ':' && s[k] !== ' ' && s[k] !== '\t' && s[k] !== '}') k++
    if (s[k] !== ':') throw new Error(`tokenize: map entry missing ':' at ${stream.i}`)
    const key = s.slice(stream.i, k)
    stream.i = k + 1 // consume ':'
    const val = readMapValue(stream)
    // An empty key (`{ :T }`) is the typed-map child annotation.
    if (key === '') child = val
    else m.set(key, val)
  }
  if (child !== undefined && m.size === 0) return newTypedMap(child)
  return newMap(m)
}

// readXmlName reads an XML tag / attribute name.
function readXmlName(stream: TokenStream): string {
  const s = stream.s
  let n = ''
  while (stream.i < s.length && /[A-Za-z0-9_-]/.test(s[stream.i]!)) {
    n += s[stream.i]
    stream.i++
  }
  return n
}

// parseXml parses an XML literal starting at `<`, producing a static
// Xml value, or an XmlInterp template when it contains ${} holes.
function parseXml(stream: TokenStream): Value {
  const holes = { has: false }
  const tmpl = parseXmlTmpl(stream, holes)
  return holes.has ? newXmlInterp(tmpl) : newXml(tmplToStatic(tmpl))
}

function tmplToStatic(t: XmlTmpl): XmlElement {
  return {
    tag: t.tag,
    attrs: t.attrs.map((a) => ({
      name: a.name,
      value: a.segs.map((seg) => ('lit' in seg ? seg.lit : '')).join(''),
    })),
    children: t.children.map((c) => ('lit' in c ? c.lit : tmplToStatic((c as { elem: XmlTmpl }).elem))),
  }
}

// readXmlHole consumes a `${ … }` hole and returns its tokens.
function readXmlHole(stream: TokenStream): Value[] {
  const s = stream.s
  stream.i += 2 // consume '${'
  let depth = 1
  const start = stream.i
  while (stream.i < s.length && depth > 0) {
    const c = s[stream.i]
    if (c === '{') depth++
    else if (c === '}') {
      depth--
      if (depth === 0) break
    }
    stream.i++
  }
  if (stream.i >= s.length) throw new Error('xml: unterminated ${ hole')
  const inner = s.slice(start, stream.i)
  stream.i++ // consume '}'
  return tokenize(inner)
}

// parseXmlTmpl parses one element into a template, recording whether any
// ${} hole appears. Attribute values must be quoted (or a bare ${});
// closing tags must match.
function parseXmlTmpl(stream: TokenStream, holes: { has: boolean }): XmlTmpl {
  const s = stream.s
  const skip = (): void => {
    while (stream.i < s.length && (s[stream.i] === ' ' || s[stream.i] === '\t')) stream.i++
  }
  stream.i++ // consume '<'
  const tag = readXmlName(stream)
  if (tag === '') throw new Error('xml: expected tag name')
  const attrs: { name: string; segs: InterpSegment[] }[] = []
  for (;;) {
    skip()
    const c = s[stream.i]
    if (c === '/' || c === '>') break
    const name = readXmlName(stream)
    if (name === '') throw new Error('xml: malformed element')
    if (s[stream.i] !== '=') throw new Error('xml: attribute requires a quoted value')
    stream.i++ // consume '='
    const segs: InterpSegment[] = []
    if (s[stream.i] === '"') {
      stream.i++ // open quote
      let lit = ''
      while (stream.i < s.length && s[stream.i] !== '"') {
        if (s[stream.i] === '$' && s[stream.i + 1] === '{') {
          if (lit !== '') {
            segs.push({ lit })
            lit = ''
          }
          segs.push({ expr: readXmlHole(stream) })
          holes.has = true
        } else {
          lit += s[stream.i]
          stream.i++
        }
      }
      if (stream.i >= s.length) throw new Error('xml: unterminated attribute')
      stream.i++ // close quote
      if (lit !== '' || segs.length === 0) segs.push({ lit })
    } else if (s[stream.i] === '$' && s[stream.i + 1] === '{') {
      segs.push({ expr: readXmlHole(stream) })
      holes.has = true
    } else {
      throw new Error('xml: attribute requires a quoted value')
    }
    attrs.push({ name, segs })
  }
  if (s[stream.i] === '/') {
    stream.i++
    if (s[stream.i] !== '>') throw new Error('xml: expected >')
    stream.i++
    return { tag, attrs, children: [] }
  }
  stream.i++ // consume '>'
  const children: XmlChildTmpl[] = []
  for (;;) {
    if (stream.i >= s.length) throw new Error('xml: unterminated element')
    if (s[stream.i] === '<' && s[stream.i + 1] === '/') {
      stream.i += 2
      const close = readXmlName(stream)
      if (s[stream.i] !== '>') throw new Error('xml: expected >')
      stream.i++
      if (close !== tag) throw new Error(`xml: mismatched closing tag </${close}> for <${tag}>`)
      return { tag, attrs, children }
    }
    if (s[stream.i] === '<') {
      children.push({ elem: parseXmlTmpl(stream, holes) })
      continue
    }
    if (s[stream.i] === '$' && s[stream.i + 1] === '{') {
      children.push({ expr: readXmlHole(stream) })
      holes.has = true
      continue
    }
    let t = ''
    while (stream.i < s.length && s[stream.i] !== '<' && !(s[stream.i] === '$' && s[stream.i + 1] === '{')) {
      t += s[stream.i]
      stream.i++
    }
    children.push({ lit: t })
  }
}

// A token ends at whitespace or any structural delimiter, so tight
// forms like `[1 2 3]` and `${{a:1}}` tokenise correctly.
function isTokenBoundary(c: string): boolean {
  return (
    c === ' ' ||
    c === '\t' ||
    c === '[' ||
    c === ']' ||
    c === '(' ||
    c === ')' ||
    c === '{' ||
    c === '}' ||
    c === '`'
  )
}

// endOfBacktick returns the index just past the backtick that closes
// the one opening at `start`, skipping over balanced ${…} holes (which
// may themselves contain nested backticks).
function endOfBacktick(s: string, start: number): number {
  let i = start + 1
  while (i < s.length) {
    const c = s[i]
    if (c === '`') return i + 1
    if (c === '$' && s[i + 1] === '{') {
      i = endOfBrace(s, i + 1)
      continue
    }
    i++
  }
  throw new Error(`unterminated backtick at ${start}`)
}

// endOfBrace returns the index just past the `}` matching the `{` at i,
// balancing nested braces and skipping nested backticks.
function endOfBrace(s: string, i: number): number {
  i++ // past '{'
  let depth = 1
  while (i < s.length && depth > 0) {
    const c = s[i]
    if (c === '{') depth++
    else if (c === '}') depth--
    else if (c === '`') {
      i = endOfBacktick(s, i)
      continue
    }
    i++
  }
  return i
}

// parseBacktick splits a backtick template into literal and ${expr}
// segments (holes balance braces/backticks). With no interpolation it
// is a plain string; otherwise an InterpString the engine evaluates.
function parseBacktick(content: string): Value {
  const segs: InterpSegment[] = []
  let hasExpr = false
  let i = 0
  while (i < content.length) {
    const dollar = content.indexOf('${', i)
    if (dollar < 0) {
      if (i < content.length) segs.push({ lit: content.slice(i) })
      break
    }
    if (dollar > i) segs.push({ lit: content.slice(i, dollar) })
    const close = endOfBrace(content, dollar + 1) // index past matching }
    if (close > content.length) throw new Error(`unterminated \${ in backtick`)
    segs.push({ expr: tokenize(content.slice(dollar + 2, close - 1)) })
    hasExpr = true
    i = close
  }
  if (!hasExpr) {
    return newString(segs.map((s) => ('lit' in s ? s.lit : '')).join(''))
  }
  return newInterpString(segs)
}

// makeListFromElems builds a list value, detecting a leading `:T`
// element as a typed-list child annotation (`[:Integer 1 2 3]`).
function makeListFromElems(elems: Value[]): Value {
  // A `:T` child annotation may appear anywhere in the list. `:Name` is
  // one token; a container child (`:[…]` / `:{…}`) tokenises as a bare
  // `:` followed by the container element.
  for (let i = 0; i < elems.length; i++) {
    const e = elems[i]!
    if (!e.isWord()) continue
    const nm = e.asWord().name
    if (nm === ':' && i + 1 < elems.length) {
      const child = elems[i + 1]!
      const rest = elems.filter((_, j) => j !== i && j !== i + 1)
      return newTypedList(child, rest)
    }
    if (nm.length > 1 && nm.startsWith(':')) {
      const t = typeTable.get(nm.slice(1))
      if (t !== undefined) {
        const rest = elems.filter((_, j) => j !== i)
        // A bare scalar child only RETAINS sibling values when it is the
        // first element (`[:T v0 v1]` → a concrete typed list). A child
        // annotation that appears after a value (`[v0 :T v1]`) gives
        // plain typed-list semantics: the values are not retained, so
        // the result is a bare (non-concrete) typed-list carrier.
        // Parser quirk pinned by types.tsv L758 vs nodes.tsv L93.
        return i === 0 ? newTypedList(newTypeLiteral(t), rest) : newTypedList(newTypeLiteral(t))
      }
    }
  }
  return newList(elems, { eval: true })
}

// readMapValue reads the value immediately after a map key's `:`.
function readMapValue(stream: TokenStream): Value {
  const s = stream.s
  const c = s[stream.i]
  if (c === '"' || c === "'") {
    let j = stream.i + 1
    while (j < s.length && s[j] !== c) j++
    if (j >= s.length) throw new Error(`unterminated string at ${stream.i}`)
    const str = newString(s.slice(stream.i + 1, j))
    stream.i = j + 1
    return str
  }
  if (c === '[') {
    stream.i++
    return makeListFromElems(readTokens(stream, ']'))
  }
  if (c === '{') {
    stream.i++
    return readMap(stream)
  }
  if (c === '(') {
    // A parenthesised expression as a map value collapses to a single
    // residual when the map is deep-evaluated (unlike a list value).
    stream.i++
    let depth = 1
    const start = stream.i
    while (stream.i < s.length && depth > 0) {
      const ch = s[stream.i]
      if (ch === '(') depth++
      else if (ch === ')') {
        depth--
        if (depth === 0) break
      }
      stream.i++
    }
    const inner = s.slice(start, stream.i)
    stream.i++ // consume ')'
    return newParenExpr(tokenize(inner))
  }
  let j = stream.i
  while (j < s.length && s[j] !== ' ' && s[j] !== '\t' && s[j] !== '}') j++
  const tok = s.slice(stream.i, j)
  stream.i = j
  return atomicValue(tok)
}

// atomicValue converts one whitespace-delimited token (not a string,
// list, or map) into a Value: booleans, none/null, numbers, bare
// type-name → type literal, /q → atom, otherwise a word with modifiers.
function atomicValue(tok: string): Value {
  switch (tok) {
    case 'true':
      return newBoolean(true)
    case 'false':
      return newBoolean(false)
    case 'none':
      return newNone()
    case 'null':
      // `null` is the atom 'null' in AQL source (the parser lexes the
      // JSON null literal as an Atom), distinct from the `none` value.
      return newAtom('null')
  }
  if (/^-?\d+$/.test(tok)) return newInteger(BigInt(tok))
  if (/^-?\d+\.\d+$/.test(tok)) return newDecimal(Number.parseFloat(tok))
  // /-suffix modifiers — /s, /f force stack/forward dispatch, /q makes
  // an Atom, /N filters by arity. Mirrors parseWord in eng/parser.
  const parsed = parseModifierSuffix(tok)
  if (parsed.quote) return newAtom(parsed.name)
  // A bare type-name word (Integer, List, None, Type, …) resolves to a
  // type-literal value, mirroring the parser's TypeNameTable lookup.
  if (parsed.name === tok) {
    const t = typeTable.get(tok)
    if (t !== undefined) return newTypeLiteral(t)
  }
  return newWordWithModifiers(parsed.name, parsed.forceStack, parsed.forceForward, parsed.argCount)
}

function newWordWithModifiers(
  name: string,
  forceStack: boolean,
  forceForward: boolean,
  argCount: number | undefined,
): Value {
  if (!forceStack && !forceForward && argCount === undefined) return newWord(name)
  const wi: WordInfo = { name }
  if (forceStack) wi.forceStack = true
  if (forceForward) wi.forceForward = true
  if (argCount !== undefined) wi.argCount = argCount
  return new Value(TWord, wi)
}

type ModifierSuffix = {
  name: string
  forceStack: boolean
  forceForward: boolean
  quote: boolean
  argCount: number | undefined
}

// parseModifierSuffix scans the trailing /-suffix on a word token.
// Mirrors parseWord in eng/parser/parse.go: digits (argCount), 'f'
// (forceForward), 's' (forceStack), 'q' (quote → Atom). Modifiers can
// appear in any order; f/s are mutually exclusive; each letter at most
// once; digits run contiguously. If the suffix is unrecognised or
// malformed, the entire token is treated as a plain word.
function parseModifierSuffix(tok: string): ModifierSuffix {
  const idx = tok.lastIndexOf('/')
  const noop: ModifierSuffix = {
    name: tok,
    forceStack: false,
    forceForward: false,
    quote: false,
    argCount: undefined,
  }
  if (idx < 0 || idx >= tok.length - 1) return noop
  const mod = tok.slice(idx + 1)
  let forceStack = false
  let forceForward = false
  let quote = false
  let seenDigits = false
  let argCount: number | undefined
  let valid = true
  let i = 0
  while (i < mod.length) {
    const c = mod[i]!
    if (c >= '0' && c <= '9') {
      if (seenDigits) {
        valid = false
        break
      }
      let j = i
      while (j < mod.length && mod[j]! >= '0' && mod[j]! <= '9') j++
      argCount = Number.parseInt(mod.slice(i, j), 10)
      seenDigits = true
      i = j
      continue
    }
    if (c === 'f') {
      if (forceForward || forceStack) {
        valid = false
        break
      }
      forceForward = true
    } else if (c === 's') {
      if (forceForward || forceStack) {
        valid = false
        break
      }
      forceStack = true
    } else if (c === 'q') {
      if (quote) {
        valid = false
        break
      }
      quote = true
    } else {
      valid = false
      break
    }
    i++
  }
  if (!valid) return noop
  return { name: tok.slice(0, idx), forceStack, forceForward, quote, argCount }
}

// parseFnTriple parses one [params][returns][body] triple into an
// FnSig. The named form has a params list (`[n:Integer ?]`); the flat
// form has bare type literals for the param/return slots.
function parseFnTriple(p: Value, r: Value, b: Value): FnSig {
  let params: FnParam[] = []
  if (p.vType.matches(TList) && Array.isArray(p.data)) {
    for (const pe of p.asList()) {
      if (pe.isWord() && pe.asWord().name === '?') {
        if (params.length > 0) params[params.length - 1]!.optional = true
        continue
      }
      params.push(parseFnParam(pe))
    }
  } else {
    // Flat form: the param slot is a bare type (unnamed param).
    params = [{ name: '', type: parseFnReturn(p) }]
  }
  const returns =
    r.vType.matches(TList) && Array.isArray(r.data)
      ? r.asList().map((x) => parseFnReturn(x))
      : [parseFnReturn(r)]
  const body = b.vType.matches(TList) && Array.isArray(b.data) ? b.asList() : [b]
  return { params, returns, body }
}

/**
 * Parse one fn-param token. The spec tokenizer produces a Word per
 * whitespace-split chunk, so a typed param like `n:Integer` arrives
 * as a single Word with name `n:Integer`. Split on the first `:`,
 * resolve the type name, build an FnParam.
 */
function parseFnParam(v: Value): FnParam {
  if (!v.isWord()) {
    throw new Error(`fn: expected param Word, got ${v.toString()}`)
  }
  const w = v.asWord()
  const idx = w.name.indexOf(':')
  if (idx < 0) {
    throw new Error(`fn: param ${JSON.stringify(w.name)} missing ':TypeName' suffix`)
  }
  const name = w.name.slice(0, idx)
  const typeName = w.name.slice(idx + 1)
  const type = typeNameTable().get(typeName)
  if (!type) throw new Error(`fn: unknown type ${JSON.stringify(typeName)}`)
  return { name, type }
}

/** Parse one fn-return token (a bare TypeName Word). */
function parseFnReturn(v: Value) {
  // A return slot is a type — either a resolved type literal (the
  // tokenizer turns bare `Integer` into one) or a bare TypeName word.
  if (v.data === null) return v.vType
  if (!v.isWord()) throw new Error(`fn: expected return type`)
  const w = v.asWord()
  const type = typeNameTable().get(w.name)
  if (!type) throw new Error(`fn: unknown return type ${JSON.stringify(w.name)}`)
  return type
}

// unsupportedMake is the placeholder handler for make/get/set/refine
// overloads whose construction isn't ported yet; their signatures still
// drive inspect rendering.
function unsupportedMake(what: string): Value[] {
  throw new AqlError('unsupported', `make/${what}: not yet ported`)
}

// buildWordInspection renders a registered word's metadata as an
// inspection map: {name:'…' kind:native signatures:[{args:['…' …]} …]}.
function buildWordInspection(
  name: string,
  fn: { declOrder: { args: { leaf(): string }[] }[] },
): Value {
  const om = new OrderedMap()
  om.set('name', newString(name))
  om.set('kind', newWord('native'))
  const sigs = fn.declOrder.map((sig) => {
    const sm = new OrderedMap()
    sm.set('args', newList(sig.args.map((t) => newString(t.leaf())), { eval: false }))
    return newMap(sm)
  })
  om.set('signatures', newList(sigs, { eval: false }))
  return newInspect(om)
}

// buildTypeInspection renders a value's type structure as an inspection
// map, mirroring buildTypeInspection in eng/go. Kinds: literal (bare
// type / concrete value), record, typed_list, typed_map, disjunct,
// function_shape, unknown (atom name lookup).
function strList(items: string[]): Value {
  return newList(items.map((s) => newString(s)), { eval: false })
}
// buildObjectType assembles an object-type value from a parent path,
// the parent's inherited fields, and a field map. Inherited fields keep
// their order and are followed by the map's own fields.
function buildObjectType(parentPath: string, inherited: OrderedMap, fieldMap: Value): Value {
  const fields = new OrderedMap()
  for (const k of inherited.keys()) fields.set(k, inherited.get(k)!)
  const m = fieldMap.asMap()
  for (const k of m.keys()) fields.set(k, m.get(k)!)
  return newObjectType(new ObjectTypeInfo('', parentPath, fields))
}

function buildTypeInspection(v: Value): Value {
  const om = new OrderedMap()
  // A concrete atom is treated as a name to look up.
  if (v.vType.equal(TAtom) && v.data !== null) {
    om.set('name', newString(v.asAtom()))
    om.set('kind', newWord('unknown'))
    om.set('signatures', newList([], { eval: false }))
    return newInspect(om)
  }
  // Typed list / typed map.
  if (v.isTypedList() || v.isTypedMap()) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.isTypedMap() ? 'Map' : 'List'))
    om.set('kind', newWord(v.isTypedMap() ? 'typed_map' : 'typed_list'))
    om.set('child', newString(v.asChildType().child.vType.toString()))
    return newInspect(om)
  }
  // Disjunct / Enum.
  if (v.isDisjunct()) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.vType.leaf()))
    om.set('kind', newWord('disjunct'))
    om.set('alternatives', strList(v.asDisjunct().alternatives.map((a) => a.vType.toString())))
    return newInspect(om)
  }
  // FunctionSignature (fnsig) — pairs of [params][returns]. The bare
  // type literal renders as function_shape with no signatures.
  if (v.vType.equal(typeTable.get('FunctionSignature')!)) {
    om.set('type', newString('Type'))
    om.set('struct', newString('FunctionSignature'))
    om.set('kind', newWord('function_shape'))
    const pairs = Array.isArray(v.data) ? (v.data as Value[]) : []
    const sigs: Value[] = []
    for (let i = 0; i + 1 < pairs.length; i += 2) {
      const sm = new OrderedMap()
      sm.set('params', strList(pairs[i]!.asList().map((p) => p.vType.leaf())))
      sm.set('returns', strList(pairs[i + 1]!.asList().map((r) => r.vType.leaf())))
      sigs.push(newMap(sm))
    }
    om.set('signatures', newList(sigs, { eval: false }))
    return newInspect(om)
  }
  // Object type (refine Object {…}): kind:object with its struct name,
  // optional parent path (omitted for a direct child of the base
  // Object), and its fields rendered as a name→type-leaf map.
  if (v.data instanceof ObjectTypeInfo) {
    const info = v.data
    om.set('type', newString('Type'))
    om.set('struct', newString(info.name))
    om.set('kind', newWord('object'))
    if (info.parentPath !== 'Object') om.set('parent', newString(info.parentPath))
    const fields = new OrderedMap()
    for (const k of info.fields.keys()) fields.set(k, newString(info.fields.get(k)!.vType.leaf()))
    om.set('fields', newMap(fields))
    return newInspect(om)
  }
  // Bare type literals (incl. the none value) and concrete values.
  if (v.isNone()) {
    om.set('type', newString('None'))
    om.set('kind', newWord('literal'))
    return newInspect(om)
  }
  if (v.data === null) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.vType.leaf()))
    om.set('kind', newWord('literal'))
    return newInspect(om)
  }
  // Any other type body whose VType lives under Type (e.g. a Function
  // value) is a TYPE literal of its leaf.
  if (v.vType.matches(TType)) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.vType.leaf()))
    om.set('kind', newWord('literal'))
    return newInspect(om)
  }
  // Record-shape map → a TYPE.
  if (isRecordShape(v)) {
    om.set('type', newString('Type'))
    om.set('struct', newString('Map'))
    om.set('kind', newWord('record'))
    const fields = new OrderedMap()
    const m = v.asMap()
    for (const k of m.keys()) fields.set(k, newString(m.get(k)!.vType.leaf()))
    om.set('fields', newMap(fields))
    return newInspect(om)
  }
  // Any other concrete value — a literal of its own type.
  om.set('type', newString(v.vType.leaf()))
  om.set('kind', newWord('literal'))
  return newInspect(om)
}

// buildDefinedInspection renders a def-bound name: a bound type body
// gets the type inspection prefixed with name; an FnDef gets kind:
// defined with its param signatures plus a synthetic 0-arg fallback;
// a plain value gets kind:defined with its rendered value.
function buildDefinedInspection(name: string, top: Value): Value {
  if (!top.isFnDef() && (top.data === null || isTypeBody(top))) {
    const insp = buildTypeInspection(top).asMap()
    const om = new OrderedMap()
    om.set('name', newString(name))
    for (const k of insp.keys()) om.set(k, insp.get(k)!)
    return newInspect(om)
  }
  const om = new OrderedMap()
  om.set('name', newString(name))
  om.set('kind', newWord('defined'))
  if (top.isFnDef()) {
    const fd = top.asFnDef()
    const sigMaps = fd.sigs.map((s) => {
      const sm = new OrderedMap()
      sm.set('args', newList(s.params.map((p) => newString(p.type.leaf())), { eval: false }))
      return newMap(sm)
    })
    const empty = new OrderedMap()
    empty.set('args', newList([], { eval: false }))
    sigMaps.push(newMap(empty))
    om.set('signatures', newList(sigMaps, { eval: false }))
  } else {
    om.set('value', top)
    om.set('signatures', newList([], { eval: false }))
  }
  return newInspect(om)
}

// renderStack renders the residual stack as canonical AQL source via
// the ported Canon, matching the Go engspec runner's eng.Canon output.
function renderStack(stack: Value[]): string {
  return canon(stack)
}

// ── Test harness ─────────────────────────────────────────────────────────

interface SpecRow {
  lineNum: number
  input: string
  expected: string
}

function parseSpec(file: string): SpecRow[] {
  const text = fs.readFileSync(file, 'utf8')
  const rows: SpecRow[] = []
  text.split('\n').forEach((raw, idx) => {
    const lineNum = idx + 1
    const trimmed = raw.replace(/[ \t]+$/, '')
    if (trimmed === '' || trimmed.startsWith('#')) return
    const parts = trimmed.split('\t')
    if (parts.length < 2) {
      throw new Error(`${file}:L${lineNum}: malformed row, want at least input<TAB>expected`)
    }
    rows.push({
      lineNum,
      input: parts[0]!.trim(),
      expected: parts[1]!.trim(),
    })
  })
  return rows
}

export { SPEC_DIR, registerSpecWords, tokenize, renderStack, parseSpec }
export type { SpecRow }

