// Command genhelp pre-computes help example results by running each
// expression through the AQL engine. Output is written to
// internal/engine/help/examples_gen.go as a static map.
//
//go:generate go run ./cmd/genhelp
package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/metsitaba/voxgig-exp/aql/internal/engine"
	"github.com/metsitaba/voxgig-exp/aql/internal/engine/help"
	"github.com/metsitaba/voxgig-exp/aql/internal/native"
	"github.com/metsitaba/voxgig-exp/aql/internal/parser"
)

func main() {
	reg, err := engine.DefaultRegistry()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genhelp: %v\n", err)
		os.Exit(1)
	}
	native.Register(reg)
	reg.SetParseFunc(parser.Parse)

	// Collect all example expressions across all words.
	// Use a fresh registry per word to avoid state leakage between examples.
	results := map[string]string{}
	words := help.Words()
	sort.Strings(words)

	for _, word := range words {
		info := engine.BuildFuncInfo(reg, word)
		if info == nil {
			continue
		}
		exprs := help.ExampleExprs(*info)

		// Fresh registry per word.
		wordReg, err := engine.DefaultRegistry()
		if err != nil {
			fmt.Fprintf(os.Stderr, "genhelp: %v\n", err)
			os.Exit(1)
		}
		native.Register(wordReg)
		wordReg.SetParseFunc(parser.Parse)

		for _, expr := range exprs {
			if _, done := results[expr]; done {
				continue
			}
			result, err := evalExpr(wordReg, expr)
			if err != nil || result == "" {
				continue // skip errors (side-effect-only words, etc.)
			}
			results[expr] = result
		}
	}

	// Generate Go source file.
	var b strings.Builder
	b.WriteString("// Code generated by cmd/genhelp; DO NOT EDIT.\n\n")
	b.WriteString("package help\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\texampleResults = map[string]string{\n")

	// Sort keys for deterministic output.
	keys := make([]string, 0, len(results))
	for k := range results {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		b.WriteString(fmt.Sprintf("\t\t%q: %q,\n", k, results[k]))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	outPath := "internal/engine/help/examples_gen.go"
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "genhelp: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "genhelp: wrote %d examples to %s\n", len(results), outPath)
}

func evalExpr(reg *engine.Registry, expr string) (string, error) {
	vals, err := parser.Parse(expr)
	if err != nil {
		return "", err
	}

	// Suppress output from print/trace.
	savedOut := reg.Output
	reg.Output = io.Discard
	defer func() { reg.Output = savedOut }()

	eng := engine.NewTop(reg)
	result, err := eng.Run(vals)
	if err != nil {
		return "", err
	}
	var parts []string
	for _, v := range result {
		parts = append(parts, v.String())
	}
	return strings.Join(parts, " "), nil
}
