package vault

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"os/user"
	"path/filepath"
	"strings"
	"time"
)

// AuditEvent is one structured entry in the vault audit log. The
// log is append-only JSONL at ~/.aql/vault.audit.jsonl, one event
// per line. Fields that are zero-valued are omitted so each line
// stays small and grep-friendly.
//
// No raw secret values, capability tokens, or request bodies are
// ever recorded — only the metadata needed to answer "who used
// which alias, when, against which host, with what outcome".
type AuditEvent struct {
	Timestamp  string `json:"ts"`
	Actor      string `json:"actor,omitempty"`
	Action     string `json:"action"`
	Alias      string `json:"alias,omitempty"`
	Capability string `json:"cap,omitempty"`
	Provider   string `json:"provider,omitempty"`
	Agent      string `json:"agent,omitempty"`
	Method     string `json:"method,omitempty"`
	Host       string `json:"host,omitempty"`
	Path       string `json:"path,omitempty"`
	Status     int    `json:"status,omitempty"`
	Outcome    string `json:"outcome,omitempty"`
	Reason     string `json:"reason,omitempty"`
}

// auditPath is the on-disk JSONL log location.
func auditPath(homeDir string) string {
	return filepath.Join(homeDir, ".aql", "vault.audit.jsonl")
}

// appendAudit writes one event to the log. Errors are reported to
// the caller; the caller decides whether a log failure should
// also fail the surrounding operation. In practice writes never
// block on the host backend and only fail on disk-full / permission
// problems, so callers can usually treat the error as a warning.
//
// If the vault's Config["audit.enabled"] is the string "false"
// the write is silently skipped.
func appendAudit(homeDir string, ev AuditEvent) error {
	if ev.Timestamp == "" {
		ev.Timestamp = time.Now().UTC().Format(time.RFC3339Nano)
	}
	if ev.Actor == "" {
		ev.Actor = defaultActor()
	}

	// Honor the per-vault disable switch. A missing or unparseable
	// store does not block writes — that lets us audit the very
	// init that creates the store.
	if s, err := LoadStore(homeDir); err == nil && s != nil {
		if v, ok := s.Config["audit.enabled"]; ok {
			if s, ok := v.(string); ok && strings.EqualFold(s, "false") {
				return nil
			}
		}
	}

	dir := filepath.Join(homeDir, ".aql")
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	f, err := os.OpenFile(auditPath(homeDir),
		os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	return enc.Encode(ev)
}

// defaultActor names the local user for events generated by
// interactive CLI invocations. Falls back to "local" when the OS
// user is unavailable (e.g. in a minimal container).
func defaultActor() string {
	if u, err := user.Current(); err == nil && u.Username != "" {
		return "user:" + u.Username
	}
	return "local"
}

// runAudit implements `aql vault audit`. By default it prints
// every event in human-readable form; flags narrow the view or
// stream new entries.
func runAudit(args []string, homeDir string, stdout, stderr io.Writer) int {
	flagSet := flag.NewFlagSet("vault audit", flag.ContinueOnError)
	flagSet.SetOutput(stderr)
	action := flagSet.String("action", "", "show only events with this action (e.g. proxy.request)")
	alias := flagSet.String("alias", "", "show only events touching this alias")
	actor := flagSet.String("actor", "", "show only events from this actor")
	last := flagSet.Int("last", 0, "show only the last N matching events (0 = all)")
	jsonOut := flagSet.Bool("json", false, "emit raw JSONL instead of human-readable lines")
	if err := flagSet.Parse(args); err != nil {
		return 1
	}

	path := auditPath(homeDir)
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			fmt.Fprintln(stdout, "(no audit events recorded)")
			return 0
		}
		fmt.Fprintf(stderr, "error: %s\n", err)
		return 1
	}
	defer f.Close()

	var events []AuditEvent
	dec := json.NewDecoder(f)
	for {
		var ev AuditEvent
		if err := dec.Decode(&ev); err != nil {
			if err == io.EOF {
				break
			}
			fmt.Fprintf(stderr, "warning: skipping malformed audit line: %s\n", err)
			continue
		}
		if *action != "" && ev.Action != *action {
			continue
		}
		if *alias != "" && ev.Alias != *alias {
			continue
		}
		if *actor != "" && ev.Actor != *actor {
			continue
		}
		events = append(events, ev)
	}

	if *last > 0 && len(events) > *last {
		events = events[len(events)-*last:]
	}

	for _, ev := range events {
		if *jsonOut {
			b, _ := json.Marshal(ev)
			fmt.Fprintln(stdout, string(b))
			continue
		}
		fmt.Fprintln(stdout, formatAuditLine(ev))
	}
	if len(events) == 0 {
		fmt.Fprintln(stdout, "(no matching events)")
	}
	return 0
}

// formatAuditLine renders one event in a `key=value` style that
// is compact enough for tail-style use yet still self-describing.
// Optional fields are omitted entirely when empty.
func formatAuditLine(ev AuditEvent) string {
	parts := []string{
		ev.Timestamp,
		"action=" + ev.Action,
		"actor=" + ev.Actor,
	}
	if ev.Alias != "" {
		parts = append(parts, "alias="+ev.Alias)
	}
	if ev.Agent != "" {
		parts = append(parts, "agent="+ev.Agent)
	}
	if ev.Capability != "" {
		parts = append(parts, "cap="+shortCap(ev.Capability))
	}
	if ev.Provider != "" {
		parts = append(parts, "provider="+ev.Provider)
	}
	if ev.Method != "" {
		parts = append(parts, "method="+ev.Method)
	}
	if ev.Host != "" {
		parts = append(parts, "host="+ev.Host)
	}
	if ev.Path != "" {
		parts = append(parts, "path="+ev.Path)
	}
	if ev.Status != 0 {
		parts = append(parts, fmt.Sprintf("status=%d", ev.Status))
	}
	if ev.Outcome != "" {
		parts = append(parts, "outcome="+ev.Outcome)
	}
	if ev.Reason != "" {
		parts = append(parts, "reason="+ev.Reason)
	}
	return strings.Join(parts, " ")
}

// shortCap truncates a capability ID to its first 8 hex chars to
// match how `vault grant` and `vault revoke` accept short prefixes.
func shortCap(id string) string {
	if len(id) > 8 {
		return id[:8]
	}
	return id
}

// ReadAudit returns every event in the log (oldest first). Used
// by tests; production code calls runAudit instead.
func ReadAudit(homeDir string) ([]AuditEvent, error) {
	f, err := os.Open(auditPath(homeDir))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	defer f.Close()
	var out []AuditEvent
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 64*1024), 1<<20)
	for sc.Scan() {
		var ev AuditEvent
		if err := json.Unmarshal(sc.Bytes(), &ev); err != nil {
			continue
		}
		out = append(out, ev)
	}
	return out, sc.Err()
}
