// Package help provides embedded help text for boru built-in words.
//
// examples_gen.go is regenerated by the genhelp tool, which lives in the
// cmd/go module: run `go generate ./...` (or `go run ./genhelp`) from the
// repo's cmd/go directory.
package help

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	core "github.com/boru-lang/boru/core/go"
)

// Entry holds the help documentation for a single boru word.
type Entry struct {
	Word        string // canonical word name
	Summary     string // one-line description
	Description string // brief multi-line explanation
	Notes       []string

	// Examples, when non-empty, are hand-authored illustrative lines that
	// REPLACE the auto-generated positional permutations in `describe`
	// output. Each string is a complete line shown verbatim (the author
	// includes any trailing `;# …` comment). Auto-generated permutations
	// teach nothing for non-trivial words like set/get/make/fold/each —
	// this lets a word ship realistic examples against real operands.
	// See §5.2/§9.5 in the DX report.
	Examples []string
}

// SigInfo holds the dynamically extracted signature data for formatting.
type SigInfo struct {
	Args       []string // type names per arg, e.g. ["Integer", "Integer"]
	Returns    []string // inferred return type abbreviations
	BarrierPos int      // forward-eligible boundary; positions [BarrierPos..N-1] are stack-only
	// Keywords overrides the rendered slot at a position with a KEYWORD
	// literal (a /q slot carrying a concrete Atom pattern — it admits
	// exactly that one word). e.g. def's `def name fn [...]` form renders
	// position 1 as "fn/q" instead of the bare "Atom". Nil when the sig
	// has no keyword slots.
	Keywords map[int]string
}

// FuncInfo carries everything needed for dynamic help rendering.
type FuncInfo struct {
	Name        string
	ForwardArgs bool
	Sigs        []SigInfo
	Entry       *Entry // static docs (may be nil)

	// Module/Doc are populated for native-module exports (e.g.
	// ArrayUtil.indices): Module is the import id ("boru:array-util"), Doc a
	// one-line summary carried on the function's FnDefInfo. When set, the
	// header shows the doc and a "Module:" line. Empty for core words, which
	// fall back to their static help Entry.
	Module string
	Doc    string

	// Examples are hand-authored `describe` lines carried on a module
	// export's FnDefInfo. They take precedence over both the static
	// Entry's examples and the generated permutations — a module export
	// has no Entry, and for a capability word the permutations are
	// well-formed nonsense. Empty for exports nobody has written
	// examples for, which keep the generated lines.
	Examples []string
}

// registry holds all help entries keyed by word name.
var registry = map[string]*Entry{}

// exampleResults holds pre-computed example results keyed by expression.
// Populated by go:generate via cmd/go/genhelp.
var exampleResults = map[string]string{}

// dynamicExampleResults holds example results generated at runtime for
// words registered after initial startup (e.g. native functions added
// via the API). Checked after the static map.
var dynamicExampleResults = map[string]string{}

// producesLiveHandle reports whether a word returns a handle to something
// still RUNNING after the call — a timer, a ticker, a process.
//
// Example generation EXECUTES the expressions it synthesises, to show a
// real result. For a pure word that is exactly right. For a word that
// returns a live handle it is a resource leak with no owner: the
// generator has nowhere to keep the handle and never cancels it, so
// registering `interval` started a real ticker that then fired for the
// lifetime of the process.
//
// That is not a documentation problem. The leaked ticker runs its
// callback on a forked registry against the same process state every
// later execution touches, which is a DATA RACE — it is what kept
// `make test-race` red (an interval created during `seedBoru`'s
// RegisterNativeFunc racing a later test's check pass), and any embedder
// registering the temporal module after MarkReady got the same leak.
//
// Keyed on the word NAME, which is unsatisfying — the return type would
// generalise to any future timer-like word — but SigInfo.Returns is EMPTY
// for exactly these words (verified: `interval`/`timeout` both report
// `returns=[]` from BuildFuncInfo), so a return-keyed rule silently never
// fires. A rule that cannot fire is worse than an explicit list, because
// it reads as covering the case.
//
// Such words keep their signature, description and hand-authored
// examples; only the synthesised run-it-for-real example is skipped.
func producesLiveHandle(name string) bool {
	switch name {
	case "interval", "timeout", "spawn", "service", "watch":
		return true
	}
	return false
}

// GenerateDynamicExamples computes and stores example results for a word
// using the provided eval function. Called when new functions are
// registered after initial startup.
func GenerateDynamicExamples(info FuncInfo, eval func(string) (string, error)) {
	if eval == nil {
		return
	}
	if producesLiveHandle(info.Name) {
		return
	}
	for _, expr := range ExampleExprs(info) {
		// A static entry normally wins — it was computed by the same
		// engine at build time. The exception is a RECORDED REFUSAL:
		// this function runs precisely when a word gains a definition,
		// and a new overload is exactly what turns
		// `add true false ;# error [boru/type_error]` into a lie. Those
		// are re-evaluated so the live engine can correct the snapshot.
		if prior, ok := exampleResults[expr]; ok && !IsRefusalRender(prior) {
			continue
		}
		if _, ok := dynamicExampleResults[expr]; ok {
			continue
		}
		encoded, ok := EncodeExampleResult(eval(expr))
		if !ok {
			continue
		}
		dynamicExampleResults[expr] = encoded
	}
}

// register adds an entry to the global help registry.
func register(e *Entry) {
	registry[e.Word] = e
}

// Lookup returns the help entry for a word, or nil if none exists.
func Lookup(word string) *Entry {
	return registry[word]
}

// Words returns all registered word names in no particular order.
func Words() []string {
	names := make([]string, 0, len(registry))
	for k := range registry {
		names = append(names, k)
	}
	return names
}

// isNonCommutative2Arg returns true if the word is a non-commutative
// binary operation (where arg order matters).
func isNonCommutative2Arg(info FuncInfo) bool {
	has2Arg := false
	for _, sig := range info.Sigs {
		if len(sig.Args) == 2 {
			has2Arg = true
			break
		}
	}
	if !has2Arg {
		return false
	}
	switch info.Name {
	case "sub", "div", "mod", "pow", "atan2",
		"lt", "gt", "lte", "gte", "implies":
		return true
	}
	return false
}

// isHouseStyleInfix reports whether a word is one of the two-argument
// words common convention reads as an infix operator, which house style
// therefore writes infix — `1 add 2`, `10 sub 3` (STYLE-GUIDE.md §S2).
//
// This is deliberately a NAME list, not a property of the signature:
// "reads as an operator" is a fact about convention, not about arity or
// commutativity. It overlaps isNonCommutative2Arg without either
// containing the other — `add` is house-style infix and commutative,
// `atan2` is non-commutative and not an operator anyone writes infix.
// Keep it in step with the operator list in STYLE-GUIDE.md §S2.
func isHouseStyleInfix(name string) bool {
	switch name {
	case "add", "sub", "mul", "div", "mod", "pow",
		"and", "or", "lt", "lte", "gt", "gte", "eq", "neq":
		return true
	}
	return false
}

// typeAbbrev shortens a full type path to its leaf name.
func typeAbbrev(t string) string {
	parts := strings.Split(t, "/")
	return parts[len(parts)-1]
}

// Format renders a static help entry as a human-readable string.
// Used when dynamic registry data is not available (e.g. REPL /help).
func Format(e *Entry) string {
	var b strings.Builder
	b.WriteString(e.Word)
	b.WriteString(" — ")
	if e.Summary != "" {
		b.WriteString(e.Summary)
	} else {
		b.WriteString("<not described>")
	}
	b.WriteByte('\n')
	if e.Description != "" {
		b.WriteString("\nDescription:\n")
		writeWrapped(&b, e.Description, 70, "  ")
	}
	if len(e.Notes) > 0 {
		b.WriteString("\nNotes:\n")
		for _, n := range e.Notes {
			b.WriteString("  - ")
			b.WriteString(n)
			b.WriteByte('\n')
		}
	}
	if len(e.Examples) > 0 {
		b.WriteString("\nExamples:\n")
		for _, line := range e.Examples {
			b.WriteString("  ")
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	b.WriteString("\nDocs: ")
	b.WriteString(ReferenceURL)
	b.WriteByte('\n')
	return b.String()
}

// FormatDynamic renders help for a word using live registry data.
func FormatDynamic(info FuncInfo) string {
	var b strings.Builder

	entry := info.Entry
	summary := "<not described>"
	if entry != nil && entry.Summary != "" {
		summary = entry.Summary
	}
	// A module export's own Doc wins over any same-named core help entry —
	// it describes this specific export (e.g. ArrayUtil.indices), not a
	// coincidentally-named built-in.
	if info.Doc != "" {
		summary = info.Doc
	}

	// Header
	b.WriteString(info.Name)
	b.WriteString(" — ")
	b.WriteString(summary)
	b.WriteByte('\n')

	// Module provenance, when this is a native-module export.
	if info.Module != "" {
		b.WriteString("Module: ")
		b.WriteString(info.Module)
		b.WriteByte('\n')
	}

	// Precedence
	b.WriteByte('\n')
	switch precedenceShape(info) {
	case precedenceMixed:
		writePrecedenceMixed(&b, info)
	case precedenceForward:
		b.WriteString("Precedence: forward — looks ahead for arguments first.\n")
		writePrecedenceExamples(&b, info)
	default:
		b.WriteString("Precedence: stack — arguments must be on the stack.\n")
		writePrecedenceExamplesStack(&b, info)
	}

	// Signatures
	b.WriteString("\nSignatures: (in match order)\n")
	writeSigs(&b, info.Sigs)

	// Description
	desc := "<not described>"
	if entry != nil && entry.Description != "" {
		desc = entry.Description
	} else if info.Doc != "" {
		desc = info.Doc
	}
	b.WriteString("\nDescription:\n")
	writeWrapped(&b, desc, 70, "  ")

	// Examples
	b.WriteString("\nExamples:\n")
	writeExamples(&b, info)

	// Notes
	if entry != nil && len(entry.Notes) > 0 {
		b.WriteString("\nNotes:\n")
		for _, n := range entry.Notes {
			b.WriteString("  - ")
			b.WriteString(n)
			b.WriteByte('\n')
		}
	}

	// Docs link back to the reference in the repo.
	b.WriteString("\nDocs: ")
	b.WriteString(ReferenceURL)
	b.WriteByte('\n')

	return b.String()
}

// writePrecedenceExamples shows all arg configurations for forward words.
// For 2-arg words: word x y <=> y word x <=> y x word
// This reflects outward-consumption: sig[0] is nearest to word on each side.
func writePrecedenceExamples(b *strings.Builder, info FuncInfo) {
	// Find longest signature (up to 3 args)
	maxArgs := 0
	for _, sig := range info.Sigs {
		if len(sig.Args) > maxArgs {
			maxArgs = len(sig.Args)
		}
	}
	if maxArgs > 3 {
		maxArgs = 3
	}
	if maxArgs == 0 {
		return
	}

	vars := []string{"x", "y", "z"}[:maxArgs]
	name := info.Name

	// Generate all configurations: 0 prefix to maxArgs prefix.
	// prefix=0: word x y z      (all forward)
	// prefix=1: z word x y      (1 on stack = sig[maxArgs-1], rest forward)
	// prefix=2: z y word x      (2 on stack, 1 forward)
	// prefix=3: z y x word      (all stack)
	//
	// Stack args appear outermost-first in source (deepest on stack = leftmost).
	// Forward args appear nearest-first after word.
	configs := make([]string, 0, maxArgs+1)
	for prefix := 0; prefix <= maxArgs; prefix++ {
		var parts []string
		// Stack args: the last `prefix` vars, in reverse order (deepest first)
		for i := maxArgs - 1; i >= maxArgs-prefix; i-- {
			parts = append(parts, vars[i])
		}
		parts = append(parts, name)
		// Forward args: the first (maxArgs-prefix) vars, in order
		for i := 0; i < maxArgs-prefix; i++ {
			parts = append(parts, vars[i])
		}
		configs = append(configs, strings.Join(parts, " "))
	}

	b.WriteString("  ")
	b.WriteString(strings.Join(configs, "  <=>  "))
	b.WriteByte('\n')

	// For non-commutative binary words, argument order changes the
	// result, so spell out which form reads naturally rather than
	// leaving a cryptic inline note on the examples. There is no
	// two-arg special case behind this: the two spellings are just
	// two splits of the one argument-order rule.
	//
	// The note stays FACTUAL. "Infix is house style" is a claim about
	// one enumerated set of operator words (STYLE-GUIDE.md §S2), which
	// is NOT the same set this predicate admits — so it belongs in
	// those words' own Entry Descriptions, not in a line rendered for
	// every non-commutative binary word.
	if isNonCommutative2Arg(info) {
		b.WriteString("  Order matters: the infix form `x ")
		b.WriteString(name)
		b.WriteString(" y` reads left-to-right;\n")
		b.WriteString("  `")
		b.WriteString(name)
		b.WriteString(" x y` is the other split — see Description.\n")
	}
}

// writePrecedenceExamplesStack shows the stack-only pattern.
func writePrecedenceExamplesStack(b *strings.Builder, info FuncInfo) {
	maxArgs := 0
	for _, sig := range info.Sigs {
		if len(sig.Args) > maxArgs {
			maxArgs = len(sig.Args)
		}
	}
	if maxArgs > 3 {
		maxArgs = 3
	}
	if maxArgs == 0 {
		return
	}

	vars := []string{"x", "y", "z"}[:maxArgs]
	// Stack-only: all args must precede the word
	var parts []string
	for i := maxArgs - 1; i >= 0; i-- {
		parts = append(parts, vars[i])
	}
	parts = append(parts, info.Name)
	b.WriteString("  ")
	b.WriteString(strings.Join(parts, " "))
	b.WriteByte('\n')
}

// writeSigs renders the signatures in column-aligned format.
func writeSigs(b *strings.Builder, sigs []SigInfo) {
	if len(sigs) == 0 {
		b.WriteString("  (none)\n")
		return
	}

	// Build formatted lines: [ [args...]  result ]
	type sigLine struct {
		args    string
		returns string
	}
	var lines []sigLine
	maxArgsLen := 0
	maxRetLen := 0
	for _, sig := range sigs {
		abbrevArgs := make([]string, len(sig.Args))
		for i, a := range sig.Args {
			if kw, ok := sig.Keywords[i]; ok {
				abbrevArgs[i] = kw
			} else {
				abbrevArgs[i] = typeAbbrev(a)
			}
		}
		argsStr := "[" + strings.Join(abbrevArgs, " ") + "]"

		abbrevRets := make([]string, len(sig.Returns))
		for i, r := range sig.Returns {
			abbrevRets[i] = typeAbbrev(r)
		}
		retStr := strings.Join(abbrevRets, " ")

		if len(argsStr) > maxArgsLen {
			maxArgsLen = len(argsStr)
		}
		if len(retStr) > maxRetLen {
			maxRetLen = len(retStr)
		}
		lines = append(lines, sigLine{args: argsStr, returns: retStr})
	}

	for _, l := range lines {
		b.WriteString("  [ ")
		b.WriteString(l.args)
		argPad := maxArgsLen - len(l.args) + 2
		for i := 0; i < argPad; i++ {
			b.WriteByte(' ')
		}
		b.WriteString(l.returns)
		retPad := maxRetLen - len(l.returns) + 1
		for i := 0; i < retPad; i++ {
			b.WriteByte(' ')
		}
		b.WriteString("]\n")
	}
}

// Standard example values by type leaf name.
var exampleValues = map[string][]string{
	"Integer": {"2", "3", "4", "5", "6", "7", "8", "9"},
	"Float":   {"2.25", "3.5", "4.75", "5.25", "6.5", "7.75", "8.25", "9.5"},
	"Number":  {"2", "3.5", "4", "5.25", "6", "7.5", "8", "9.25"},
	"String":  {"'a'", "'b'", "'c'", "'d'", "'e'", "'f'"},
	"Scalar":  {"'a'", "'b'", "'c'", "'d'", "'e'", "'f'"},
	"Atom":    {"a/q", "b/q", "c/q", "d/q", "e/q", "f/q"},
	"Boolean": {"true", "false", "true", "false"},
	"List":    {"['a','b']", "['c','d']", "['e','f']"},
	"Map":     {"{a:1,b:2}", "{c:3,d:4}", "{e:5,f:6}"},
	"Any":     {"2", "3", "4", "5", "6", "7", "8", "9"},
	"Node":    {"{a:1}", "['x']", "{b:2}", "['y']"},
}

// exampleVal returns a standard example value for a type.
// counter is used to cycle through the available values.
func exampleVal(typeName string, counter *int) string {
	leaf := typeAbbrev(typeName)
	vals, ok := exampleValues[leaf]
	if !ok {
		vals = exampleValues["Any"]
	}
	idx := *counter % len(vals)
	*counter++
	return vals[idx]
}

// examplePrefixes returns the stack-prefix counts to render as examples
// for one signature, in display order. The prefix is the number of args
// that sit on the stack (before the word); the rest are forward tokens.
//
//   - Stack-only words (no forward sigs) must put every arg on the
//     stack, so the only valid form is prefix == nArgs.
//   - House-style infix operators lead with the INFIX form (prefix 1):
//     `a word b`. That is the spelling STYLE-GUIDE.md §S2 requires for
//     them, and `describe` is documentation — it must not open with the
//     form the style guide rejects. The non-commutative ones keep the
//     forward form as a second example: the pair binds the SAME
//     arguments (`3.5 sub 2` and `sub 2 3.5` both give 1.5), which
//     shows that writing a call all-forward reverses the order the
//     operands appear in — the step readers get wrong.
//   - Every other forward word leads with the canonical forward form
//     (prefix 0): `word a b`, which reads in declared argument order.
//
// Both ExampleExprs (generator) and writeExamples (renderer) call this
// so the pre-computed result map always lines up with what is shown.
// examplePrefixes picks how many arguments each generated example
// places BEFORE the word (the stack side). The choice is PER SIGNATURE,
// from its own barrier: positions [BarrierPos..N-1] always come from
// the stack, so an example may put at most BarrierPos args forward. The
// word-wide ForwardArgs flag is not enough — a mixed-barrier word like
// `or` (BarrierPos 1) would get the all-forward `or true false`, which
// the live engine refuses with a signature_error; the help must not
// teach a spelling describe's own Precedence section says is invalid.
func examplePrefixes(info FuncInfo, sig SigInfo) []int {
	nArgs := len(sig.Args)
	if nArgs == 0 {
		return nil
	}
	if !info.ForwardArgs {
		return []int{nArgs}
	}
	barrier := sig.BarrierPos
	if barrier < 0 || barrier > nArgs {
		// -1 is the unnormalized all-forward sentinel (module-wrapper
		// FnSigs carry it raw); an over-wide barrier means the same.
		barrier = nArgs
	}
	minPrefix := nArgs - barrier
	if nArgs == 2 && minPrefix <= 1 && isHouseStyleInfix(info.Name) {
		if minPrefix == 0 && isNonCommutative2Arg(info) {
			return []int{1, 0}
		}
		return []int{1}
	}
	return []int{minPrefix}
}

// sigHasExampleVals reports whether every argument type in sig has a
// representative literal in exampleValues. Signatures over exotic types
// (dates, durations, functions, …) would otherwise be illustrated with
// invented numbers, so they are skipped for example generation.
func sigHasExampleVals(sig SigInfo) bool {
	for _, a := range sig.Args {
		if _, ok := exampleValues[typeAbbrev(a)]; !ok {
			return false
		}
	}
	return true
}

// sigExampleVals picks the example values for one signature, advancing
// the shared per-type counters so successive signatures use distinct
// values. Both the generator and renderer must walk signatures in the
// same order with the same counters for the expressions to match.
func sigExampleVals(sig SigInfo, counters map[string]int) []string {
	vals := make([]string, len(sig.Args))
	for i, a := range sig.Args {
		leaf := typeAbbrev(a)
		c := counters[leaf]
		vals[i] = exampleVal(a, &c)
		counters[leaf] = c
	}
	return vals
}

// ExampleExprs returns all example expressions that would be generated
// for a word, without computing results. Used by the generator to know
// which expressions to pre-compute.
func ExampleExprs(info FuncInfo) []string {
	var exprs []string
	seen := map[string]bool{}
	counters := map[string]int{}
	for _, sig := range info.Sigs {
		nArgs := len(sig.Args)
		if nArgs == 0 || !sigHasExampleVals(sig) {
			continue
		}
		vals := sigExampleVals(sig, counters)
		for _, prefix := range examplePrefixes(info, sig) {
			expr := buildExampleExpr(info.Name, vals, prefix, nArgs)
			if seen[expr] {
				continue
			}
			seen[expr] = true
			exprs = append(exprs, expr)
		}
	}
	return exprs
}

// writeExamples renders column-aligned examples for a word: the
// canonical forward form per signature (plus the infix form for
// non-commutative binary words). Identical expressions across
// signatures are shown once.
func writeExamples(b *strings.Builder, info FuncInfo) {
	// Hand-authored examples win over the auto-generated permutations —
	// a module export's own first (it describes THIS export), then the
	// static help Entry's.
	if authored := info.Examples; len(authored) > 0 {
		writeExampleLines(b, authored)
		return
	}
	if info.Entry != nil && len(info.Entry.Examples) > 0 {
		writeExampleLines(b, info.Entry.Examples)
		return
	}
	if len(info.Sigs) == 0 {
		b.WriteString("  (no examples)\n")
		return
	}

	var examples []exLine
	seen := map[string]bool{}
	maxExprLen := 0
	counters := map[string]int{}

	for _, sig := range info.Sigs {
		nArgs := len(sig.Args)
		if nArgs == 0 || !sigHasExampleVals(sig) {
			continue
		}
		vals := sigExampleVals(sig, counters)
		for _, prefix := range examplePrefixes(info, sig) {
			expr := buildExampleExpr(info.Name, vals, prefix, nArgs)
			if seen[expr] { //covergate:allow native handler defensive error-propagation / same-assertion guard (§native)
				continue
			}
			seen[expr] = true
			result := evalExample(expr, info.Name, sig, vals)
			if len(expr) > maxExprLen {
				maxExprLen = len(expr)
			}
			examples = append(examples, exLine{expr: expr, result: result})
		}
	}

	if len(examples) == 0 {
		b.WriteString("  (no examples)\n")
		return
	}

	writeGeneratedExamples(b, examples, maxExprLen)
}

// exLine is one generated example: the expression and its evaluated
// result, rendered as `expr   ;# result` with the results column-aligned.
type exLine struct {
	expr   string
	result string
}

// writeExampleLines renders hand-authored example lines verbatim, one
// per line, indented to match the generated ones. The author owns the
// whole line including any trailing `;# …`.
func writeExampleLines(b *strings.Builder, lines []string) {
	for _, line := range lines {
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

// writeGeneratedExamples renders the positional permutations, aligning
// the `;#` result column across them.
func writeGeneratedExamples(b *strings.Builder, examples []exLine, maxExprLen int) {
	for _, ex := range examples {
		b.WriteString("  ")
		b.WriteString(ex.expr)
		padding := maxExprLen - len(ex.expr) + 3
		for i := 0; i < padding; i++ {
			b.WriteByte(' ')
		}
		b.WriteString(";# ")
		b.WriteString(ex.result)
		b.WriteByte('\n')
	}
}

// buildSigArgs returns the sig args in signature order for a given config.
// Regardless of prefix/forward layout, the argument equivalence principle
// means all configs produce sig[0]=vals[0], sig[1]=vals[1], etc.
func buildSigArgs(vals []string, prefix, nArgs int) []string {
	result := make([]string, len(vals))
	copy(result, vals)
	return result
}

// buildExampleExpr constructs an expression with `prefix` args on stack
// and the rest forward. Mirrors the precedence layout:
//
//	prefix=0: word v0 v1 v2      (all forward)
//	prefix=1: v2 word v0 v1      (last on stack)
//	prefix=2: v2 v1 word v0      (last two on stack)
//	prefix=3: v2 v1 v0 word      (all on stack)
func buildExampleExpr(name string, vals []string, prefix, nArgs int) string {
	var parts []string
	// Stack args: last `prefix` vals, outermost (deepest) first
	for i := nArgs - 1; i >= nArgs-prefix; i-- {
		parts = append(parts, vals[i])
	}
	parts = append(parts, name)
	// Forward args: first (nArgs-prefix) vals, in order
	for i := 0; i < nArgs-prefix; i++ {
		parts = append(parts, vals[i])
	}
	return strings.Join(parts, " ")
}

// evalExample looks up a pre-computed result for an expression,
// checking the dynamic (live-engine) map first, then the static
// build-time map, then falling back to static computation.
func evalExample(expr, name string, sig SigInfo, vals []string) string {
	// Dynamic first: it is computed by the LIVE engine, so where the two
	// disagree the static map is a stale build-time snapshot — the case
	// GenerateDynamicExamples re-evaluates a recorded refusal for.
	if result, ok := dynamicExampleResults[expr]; ok {
		return result
	}
	if result, ok := exampleResults[expr]; ok {
		return result
	}
	sigArgs := buildSigArgs(vals, 0, len(vals))
	return computeExampleResult(name, sig, sigArgs)
}

// computeExampleResult computes a result string for an example.
// sigArgs are in signature order: sigArgs[0] = sig[0], sigArgs[1] = sig[1].
// For common operations we compute real results; otherwise use "...".
func computeExampleResult(name string, sig SigInfo, sigArgs []string) string {
	if len(sigArgs) == 2 {
		return computeBinaryResult(name, sig, sigArgs[0], sigArgs[1])
	}
	if len(sigArgs) == 1 {
		return computeUnaryResult(name, sig, sigArgs[0])
	}
	return "..."
}

func computeBinaryResult(name string, sig SigInfo, a, b string) string {
	// a = sig[0] (nearest arg), b = sig[1] (further arg).
	// Non-commutative ops compute args[1] op args[0] = b op a.
	aF, aOk := parseNum(a)
	bF, bOk := parseNum(b)

	if aOk && bOk {
		var result float64
		switch name {
		case "add":
			result = aF + bF
		case "sub":
			result = bF - aF
		case "mul":
			result = aF * bF
		case "div":
			if aF == 0 {
				return "error"
			}
			result = bF / aF
		case "mod":
			if aF == 0 {
				return "error"
			}
			result = math.Mod(bF, aF)
		case "pow":
			return "..."
		case "min":
			if aF < bF {
				result = aF
			} else {
				result = bF
			}
		case "max":
			if aF > bF {
				result = aF
			} else {
				result = bF
			}
		default:
			return "..."
		}
		return formatResult(result, sig)
	}

	// String concat for add applies only when an operand is a quoted
	// String (handler does args[1] + args[0] = b + a). Two non-String
	// scalars — e.g. `add true false` — are a within-type op the heuristic
	// cannot evaluate (Boolean arithmetic is a defined error), so show
	// "..." rather than a bogus concatenation.
	if name == "add" && (strings.HasPrefix(a, "'") || strings.HasPrefix(b, "'")) {
		aStr := strings.Trim(a, "'")
		bStr := strings.Trim(b, "'")
		return "'" + bStr + aStr + "'"
	}

	return "..."
}

// formatResult formats a numeric result to match the engine's output.
func formatResult(result float64, sig SigInfo) string {
	if len(sig.Returns) == 0 {
		return "..."
	}
	retLeaf := typeAbbrev(sig.Returns[0])
	if retLeaf == "Integer" {
		return fmt.Sprintf("%d", int64(result))
	}
	// Render through the ENGINE's own float formatter rather than a local
	// approximation of it. The hand-rolled
	// `strconv.FormatFloat(result, 'f', -1, 64)` this replaces claimed to
	// "match engine" and did not: it drops the decimal point on a whole
	// value, so a Float 7 rendered as `7` — an Integer literal — where the
	// engine renders `7.0`. That difference is type-visible in boru, so
	// the fallback was documenting the wrong type. core.FormatFloat is the
	// same function `describe` output is compared against, so the two
	// cannot drift apart again.
	return core.FormatFloat(result)
}

func computeUnaryResult(name string, sig SigInfo, a string) string {
	aF, aOk := parseNum(a)
	if !aOk {
		return "..."
	}
	var result float64
	switch name {
	case "abs":
		if aF < 0 {
			result = -aF
		} else {
			result = aF
		}
	case "negate":
		result = -aF
	case "sign":
		if aF > 0 {
			return "1"
		} else if aF < 0 {
			return "-1"
		}
		return "0"
	default:
		return "..."
	}
	return formatResult(result, sig)
}

func parseNum(s string) (float64, bool) {
	s = strings.Trim(s, "'")
	var f float64
	n, err := fmt.Sscanf(s, "%f", &f)
	return f, err == nil && n == 1
}

// writeWrapped writes text wrapped at width with the given indent.
func writeWrapped(b *strings.Builder, text string, width int, indent string) {
	words := strings.Fields(text)
	lineLen := 0
	b.WriteString(indent)
	for i, w := range words {
		if i > 0 && lineLen+1+len(w) > width {
			b.WriteByte('\n')
			b.WriteString(indent)
			lineLen = 0
		} else if i > 0 {
			b.WriteByte(' ')
			lineLen++
		}
		b.WriteString(w)
		lineLen += len(w)
	}
	b.WriteByte('\n')
}

// Precedence shapes. A word's signatures do not have to agree about where
// their arguments come from, and until 2026-08-02 this renderer assumed
// they did: it branched on a single `ForwardArgs` flag, which is true when
// ANY signature is forward-eligible. Every word with a MIXED barrier
// therefore advertised the full forward equivalence chain — including
// spellings it refuses. `apply` is the recorded case (NUR023): its
// `[Function]` row is stack-only, so `apply f/v 5` raises a signature
// error while the help says `apply x y <=> y apply x <=> y x apply`. It is
// not alone — `dot` (NUR049's subject) has sixteen `BarrierPos: 1` rows
// that take their receiver from the stack, and advertised the same false
// chain.
type precedenceKind int

const (
	precedenceStack precedenceKind = iota
	precedenceForward
	precedenceMixed
)

// sigIsAllForward reports whether every position of a signature can be
// filled by looking ahead. BarrierPos is the boundary: positions
// [BarrierPos..N-1] always come from the stack.
//
// A NEGATIVE BarrierPos is the "-1" sentinel for all-forward-eligible.
// The registry normalizes it to TotalArgs() when a native is registered
// (eng/go/registry.go), but an FnSig carried on an FnDefInfo — every
// module-export wrapper, which the wrapper rule requires to declare -1 —
// still holds the raw sentinel when it reaches here. Normalizing in these
// two predicates keeps that shape from reading as stack-only.
func sigIsAllForward(s SigInfo) bool {
	return s.BarrierPos < 0 || s.BarrierPos >= len(s.Args)
}

// sigIsStackOnly reports whether a signature takes nothing forward.
func sigIsStackOnly(s SigInfo) bool { return s.BarrierPos == 0 }

// precedenceShape classifies a word by whether its signatures AGREE about
// argument sourcing. A word only earns the unqualified "forward" or
// "stack" line when they all agree; anything else is reported as varying,
// because a single line cannot be true of every row.
//
// Zero-arg words are deliberately excluded from the mixed path: with no
// arguments to source, BarrierPos is inert (the registry normalizes -1 to
// TotalArgs(), which is 0), so both readings describe the same nothing.
// Which of the two they should declare is a live convention question
// recorded as NUR023, not something for this renderer to take a side on.
func precedenceShape(info FuncInfo) precedenceKind {
	maxArgs := 0
	for _, s := range info.Sigs {
		if len(s.Args) > maxArgs {
			maxArgs = len(s.Args)
		}
	}
	if maxArgs == 0 || len(info.Sigs) == 0 {
		if info.ForwardArgs {
			return precedenceForward
		}
		return precedenceStack
	}

	allForward, allStack := true, true
	for _, s := range info.Sigs {
		if len(s.Args) == 0 {
			continue // inert; see the doc comment
		}
		if !sigIsAllForward(s) {
			allForward = false
		}
		if !sigIsStackOnly(s) {
			allStack = false
		}
	}
	switch {
	case allForward:
		return precedenceForward
	case allStack:
		return precedenceStack
	default:
		return precedenceMixed
	}
}

// writePrecedenceMixed reports a word whose signatures disagree, naming the
// split per group rather than asserting one chain that is false for some
// rows. It shows the ONE spelling that satisfies every signature — full
// stack form always does, since a forward-eligible position accepts a
// stack value too — so a reader has something that always works.
func writePrecedenceMixed(b *strings.Builder, info FuncInfo) {
	b.WriteString("Precedence: varies by signature — see the split below.\n")

	var forward, mixed, stack []SigInfo
	for _, s := range info.Sigs {
		if len(s.Args) == 0 {
			continue
		}
		switch {
		case sigIsAllForward(s):
			forward = append(forward, s)
		case sigIsStackOnly(s):
			stack = append(stack, s)
		default:
			mixed = append(mixed, s)
		}
	}

	// verb is the bare stem; a one-row group needs the -s form. Both stems
	// used here are regular, so stem+"s" is the whole of the agreement.
	line := func(verb, rest string, group []SigInfo) {
		if len(group) == 0 {
			return
		}
		b.WriteString("  ")
		b.WriteString(strconv.Itoa(len(group)))
		if len(group) == 1 {
			b.WriteString(" signature " + verb + "s ")
		} else {
			b.WriteString(" signatures " + verb + " ")
		}
		b.WriteString(rest)
		b.WriteByte('\n')
	}
	line("look", "ahead for every argument.", forward)
	line("take", "a leading argument forward and the rest from the stack.", mixed)
	line("take", "every argument from the stack.", stack)

	maxArgs := 0
	for _, s := range info.Sigs {
		if len(s.Args) > maxArgs {
			maxArgs = len(s.Args)
		}
	}
	if maxArgs > 3 {
		maxArgs = 3
	}
	vars := []string{"x", "y", "z"}[:maxArgs]
	var parts []string
	for i := maxArgs - 1; i >= 0; i-- {
		parts = append(parts, vars[i])
	}
	parts = append(parts, info.Name)
	b.WriteString("  Full stack form satisfies every signature:  ")
	b.WriteString(strings.Join(parts, " "))
	b.WriteString("\n  Which forward spellings dispatch depends on the signature matched;\n")
	b.WriteString("  see the list below.\n")
}
