// Code generated by piecetool -facade; DO NOT EDIT.
//
// The eng facade over the core module (design/ENG-FOUR-PIECE.0.md
// Stage 4): type aliases are zero-cost, the function wrappers are thin
// enough to inline, and set-once vars mirror by value at init (core's
// package init completes first). Mutable slot tables are NOT mirrored —
// their installers write core.X directly.
package eng

import (
	"context"
	"io"
	"math/big"
	"regexp"
	"time"

	check "github.com/boru-lang/boru/check/go"
	compiler "github.com/boru-lang/boru/compiler/go"
	core "github.com/boru-lang/boru/core/go"
	apd "github.com/cockroachdb/apd/v3"
)

var _ = context.Canceled
var _ io.Reader
var _ big.Int
var _ regexp.Regexp
var _ time.Time
var _ apd.Decimal
var _ = core.TheInactiveEmit
var _ = check.DispatchBraid
var _ compiler.EmitState

type (
	DeadSig       = check.DeadSig
	GuardClause   = check.GuardClause
	SpreadPayload = check.SpreadPayload
	UserPolyPlan  = check.UserPolyPlan
)

const (
	CarrierDisjunctCap = check.CarrierDisjunctCap
	FnAnalysisQuota    = check.FnAnalysisQuota
)

// Cold func-value re-exports: exported core funcs no suite calls
// through the facade (API surface only — lang re-export vars,
// short-circuited operands, external embedders). A var of func type
// keeps every reference site compiling verbatim with no wrapper body
// to leave uncovered; a name moves back up to a wrapper func when a
// hot path starts calling it.
var (
	AnyAnyCarrier                 = check.AnyAnyCarrier
	AnyDynamicCarrier             = check.AnyDynamicCarrier
	AnyNonConcreteOperand         = check.AnyNonConcreteOperand
	BodyRefsFnLocalFn             = check.BodyRefsFnLocalFn
	BuildFnBodyReturnsFn          = check.BuildFnBodyReturnsFn
	CarrierResults                = check.CarrierResults
	CheckAddUnique                = check.CheckAddUnique
	CheckAtUncaughtTopLevel       = check.CheckAtUncaughtTopLevel
	CheckMakeConstruction         = check.CheckMakeConstruction
	DeadSignatures                = check.DeadSignatures
	DeferredParamListResidual     = check.DeferredParamListResidual
	DynamicReachableOverloadCount = check.DynamicReachableOverloadCount
	FnPredicateOverloadHazard     = check.FnPredicateOverloadHazard
	IsDeferredWordList            = check.IsDeferredWordList
	IsVariadicSpread              = check.IsVariadicSpread
	JoinCarriersInner             = check.JoinCarriersInner
	MintFlexShapeCarrier          = check.MintFlexShapeCarrier
	NewVariadicCarrier            = check.NewVariadicCarrier
	OrderingReturnsFn             = check.OrderingReturnsFn
	ParamBodyCarrier              = check.ParamBodyCarrier
	ParamInputCarrier             = check.ParamInputCarrier
	RecordTypedDefMake            = check.RecordTypedDefMake
	RefuseForwardStackDrift       = check.RefuseForwardStackDrift
	RunFnBodyOnce                 = check.RunFnBodyOnce
	ScalarFoldOperand             = check.ScalarFoldOperand
	SpliceFnValueCheckResult      = check.SpliceFnValueCheckResult
	StoreShapeOf                  = check.StoreShapeOf
	TryRecordMethodApply          = check.TryRecordMethodApply
	TryShapedMethodDispatch       = check.TryShapedMethodDispatch
	UnionCarrierForType           = check.UnionCarrierForType
)

func AdoptShapeValue(a0 core.Value, a1 int) core.Value { return check.AdoptShapeValue(a0, a1) }

func AnalyseFnBody(a0 *core.Registry, a1 string, a2 []string, a3 []core.Value, a4 []core.Value, a5 []core.CapturedBinding, a6 []*core.Type, a7 bool) []core.Value {
	return check.AnalyseFnBody(a0, a1, a2, a3, a4, a5, a6, a7)
}

func AnalyseLoopBody(a0 *core.Registry, a1 core.Value, a2 []string, a3 []core.Value, a4 bool) []core.Value {
	return check.AnalyseLoopBody(a0, a1, a2, a3, a4)
}

func ApplyComplementNarrowing(a0 *core.Registry, a1 core.Value) func() {
	return check.ApplyComplementNarrowing(a0, a1)
}

func ApplyGuardNarrowing(a0 *core.Registry, a1 core.Value) func() {
	return check.ApplyGuardNarrowing(a0, a1)
}

func BodyFreeForFallback(a0 *core.Registry, a1 core.Value) bool {
	return check.BodyFreeForFallback(a0, a1)
}

func BodyHasSentinel(a0 core.Value) bool { return check.BodyHasSentinel(a0) }

func BodyHasSentinelDeep(a0 *core.Registry, a1 core.Value) bool {
	return check.BodyHasSentinelDeep(a0, a1)
}

func BoolWord(a0 bool) string { return check.BoolWord(a0) }

func CheckAddUniqueDiagnostic(a0 *core.Registry, a1 string, a2 string, a3 string, a4 core.SrcPos) {
	check.CheckAddUniqueDiagnostic(a0, a1, a2, a3, a4)
}

func CheckAtIndices(a0 *core.Registry, a1 core.Value, a2 core.Value, a3 string) {
	check.CheckAtIndices(a0, a1, a2, a3)
}

func CheckListIndex(a0 *core.Registry, a1 core.Value, a2 core.Value, a3 string) {
	check.CheckListIndex(a0, a1, a2, a3)
}

func CommonAncestorType(a0 *core.Type, a1 *core.Type) *core.Type {
	return check.CommonAncestorType(a0, a1)
}

func DataListElemTypeFromValue(a0 core.Value) *core.Type { return check.DataListElemTypeFromValue(a0) }

func DryPassReturns(a0 func(args []core.Value, named map[string]core.Value, body []core.Value, r *core.Registry) ([]core.Value, error), a1 ...*core.Type) core.ReturnsFunc {
	return check.DryPassReturns(a0, a1...)
}

func DryPassWrap(a0 func(args []core.Value, named map[string]core.Value, body []core.Value, r *core.Registry) ([]core.Value, error), a1 core.ReturnsFunc) core.ReturnsFunc {
	return check.DryPassWrap(a0, a1)
}

func ElementCarrierFromValue(a0 core.Value) core.Value { return check.ElementCarrierFromValue(a0) }

func FnAnalysisKey(a0 uint64, a1 string, a2 []core.Value, a3 []core.CapturedBinding, a4 []core.Value) string {
	return check.FnAnalysisKey(a0, a1, a2, a3, a4)
}

func FoldVariadicArms(a0 []core.Value, a1 []core.Value) (core.Value, bool) {
	return check.FoldVariadicArms(a0, a1)
}

func InstallJoinedDefs(a0 *core.Registry, a1 map[string]core.Value, a2 map[string]core.Value) {
	check.InstallJoinedDefs(a0, a1, a2)
}

func JoinCarrierStacks(a0 []core.Value, a1 []core.Value) []core.Value {
	return check.JoinCarrierStacks(a0, a1)
}

func JoinCarriers(a0 core.Value, a1 core.Value) core.Value { return check.JoinCarriers(a0, a1) }

func LiteralCondValue(a0 core.Value) (bool, bool) { return check.LiteralCondValue(a0) }

func NewCarrierTypedList(a0 *core.Type) core.Value { return check.NewCarrierTypedList(a0) }

func NewCarrierTypedListLen(a0 *core.Type, a1 int) core.Value {
	return check.NewCarrierTypedListLen(a0, a1)
}

func NewCarrierTypedListValue(a0 core.Value) core.Value { return check.NewCarrierTypedListValue(a0) }

func NewDynamicCarrierValue(a0 core.Value) core.Value { return check.NewDynamicCarrierValue(a0) }

func NewElementCarrier(a0 *core.Type) core.Value { return check.NewElementCarrier(a0) }

func ReturnsAddConcat() core.ReturnsFunc { return check.ReturnsAddConcat() }

func ReturnsFreshInstance(a0 ...int) core.ReturnsFunc { return check.ReturnsFreshInstance(a0...) }

func ReturnsIdentity(a0 ...int) core.ReturnsFunc { return check.ReturnsIdentity(a0...) }

func ReturnsListElemAt(a0 int) core.ReturnsFunc { return check.ReturnsListElemAt(a0) }

func ReturnsNumericBinary() core.ReturnsFunc { return check.ReturnsNumericBinary() }

func ReturnsPreserveListAt(a0 int) core.ReturnsFunc { return check.ReturnsPreserveListAt(a0) }

func ReturnsStatic(a0 ...*core.Type) core.ReturnsFunc { return check.ReturnsStatic(a0...) }

func RunCarrierBody(a0 *core.Registry, a1 core.Value) []core.Value {
	return check.RunCarrierBody(a0, a1)
}

func RunCarrierBodyKeepDefs(a0 *core.Registry, a1 core.Value) []core.Value {
	return check.RunCarrierBodyKeepDefs(a0, a1)
}

func RunCarrierBodyWithDefs(a0 *core.Registry, a1 core.Value) ([]core.Value, map[string]core.Value) {
	return check.RunCarrierBodyWithDefs(a0, a1)
}

func RunCarrierCondBody(a0 *core.Registry, a1 core.Value) ([]core.Value, map[string]core.Value) {
	return check.RunCarrierCondBody(a0, a1)
}

func ShapeFieldRead(a0 core.Value) core.Value { return check.ShapeFieldRead(a0) }

func StaticListLen(a0 core.Value) (int, bool) { return check.StaticListLen(a0) }

func StripToCarriers(a0 []core.Value) []core.Value { return check.StripToCarriers(a0) }
