// Code generated by piecetool -facade; DO NOT EDIT.
//
// The eng facade over the core module (design/ENG-FOUR-PIECE.0.md
// Stage 4): type aliases are zero-cost, the function wrappers are thin
// enough to inline, and set-once vars mirror by value at init (core's
// package init completes first). Mutable slot tables are NOT mirrored —
// their installers write core.X directly.
package eng

import (
	"context"
	"io"
	"math/big"
	"regexp"
	"time"

	check "github.com/boru-lang/boru/check/go"
	compiler "github.com/boru-lang/boru/compiler/go"
	core "github.com/boru-lang/boru/core/go"
	apd "github.com/cockroachdb/apd/v3"
)

var _ = context.Canceled
var _ io.Reader
var _ big.Int
var _ regexp.Regexp
var _ time.Time
var _ apd.Decimal
var _ = core.TheInactiveEmit
var _ = check.DispatchBraid
var _ compiler.EmitState

type (
	CompiledFn     = compiler.CompiledFn
	CompiledFnRef  = compiler.CompiledFnRef
	ConstLocalRef  = compiler.ConstLocalRef
	DepSnapEntry   = compiler.DepSnapEntry
	DispatchSpec   = compiler.DispatchSpec
	DynMethodSpec  = compiler.DynMethodSpec
	EmitEvent      = compiler.EmitEvent
	EmitFragment   = compiler.EmitFragment
	EmitOperand    = compiler.EmitOperand
	EmitState      = compiler.EmitState
	EmitTrap       = compiler.EmitTrap
	GlobalBindSpec = compiler.GlobalBindSpec
	Instr          = compiler.Instr
	InterpSeg      = compiler.InterpSeg
	InterpSpec     = compiler.InterpSpec
	MakeMapSpec    = compiler.MakeMapSpec
	Opcode         = compiler.Opcode
	PolyRef        = compiler.PolyRef
	Program        = compiler.Program
	RestampBox     = compiler.RestampBox
	SigRef         = compiler.SigRef
	TrapSpec       = compiler.TrapSpec
	TypeRef        = compiler.TypeRef
	UserPolyRef    = compiler.UserPolyRef
	XmlInterpSpec  = compiler.XmlInterpSpec
)

const (
	ClosureInKeyVal        = compiler.ClosureInKeyVal
	ClosureInValue         = compiler.ClosureInValue
	OpBindDynScope         = compiler.OpBindDynScope
	OpBindGlobal           = compiler.OpBindGlobal
	OpBindTyped            = compiler.OpBindTyped
	OpCallDynApplyTop      = compiler.OpCallDynApplyTop
	OpCallDynFrame         = compiler.OpCallDynFrame
	OpCallDynMethod        = compiler.OpCallDynMethod
	OpCallDynMixedFromMark = compiler.OpCallDynMixedFromMark
	OpCallDynTrailTop      = compiler.OpCallDynTrailTop
	OpCallDynamic          = compiler.OpCallDynamic
	OpCallDynamicMixed     = compiler.OpCallDynamicMixed
	OpCallDynamicTrailing  = compiler.OpCallDynamicTrailing
	OpCallNative           = compiler.OpCallNative
	OpCallNativePoly       = compiler.OpCallNativePoly
	OpCallUser             = compiler.OpCallUser
	OpCallUserPoly         = compiler.OpCallUserPoly
	OpDispatchRematch      = compiler.OpDispatchRematch
	OpDrop                 = compiler.OpDrop
	OpDropToMark           = compiler.OpDropToMark
	OpFallback             = compiler.OpFallback
	OpFlowBreak            = compiler.OpFlowBreak
	OpFlowContinue         = compiler.OpFlowContinue
	OpForNext              = compiler.OpForNext
	OpForSetup             = compiler.OpForSetup
	OpInterp               = compiler.OpInterp
	OpInterpXml            = compiler.OpInterpXml
	OpJmp                  = compiler.OpJmp
	OpJmpIfFalse           = compiler.OpJmpIfFalse
	OpLookupDynScope       = compiler.OpLookupDynScope
	OpLookupDynScopeData   = compiler.OpLookupDynScopeData
	OpMakeList             = compiler.OpMakeList
	OpMakeMap              = compiler.OpMakeMap
	OpPopMark              = compiler.OpPopMark
	OpPushClosure          = compiler.OpPushClosure
	OpPushConst            = compiler.OpPushConst
	OpPushConstFresh       = compiler.OpPushConstFresh
	OpPushConstFreshLocal  = compiler.OpPushConstFreshLocal
	OpPushLocal            = compiler.OpPushLocal
	OpPushType             = compiler.OpPushType
	OpRet                  = compiler.OpRet
	OpReverse              = compiler.OpReverse
	OpSpliceDyn            = compiler.OpSpliceDyn
	OpStackMark            = compiler.OpStackMark
	OpStoreLocal           = compiler.OpStoreLocal
	OpSwap                 = compiler.OpSwap
	OpTailCallUser         = compiler.OpTailCallUser
	OpTrap                 = compiler.OpTrap
	RestampMaxTries        = compiler.RestampMaxTries
	SiteDynamic            = compiler.SiteDynamic
	SiteMeta               = compiler.SiteMeta
	SiteMono               = compiler.SiteMono
	SitePoly               = compiler.SitePoly
)

// Cold func-value re-exports: exported core funcs no suite calls
// through the facade (API surface only — lang re-export vars,
// short-circuited operands, external embedders). A var of func type
// keeps every reference site compiling verbatim with no wrapper body
// to leave uncovered; a name moves back up to a wrapper func when a
// hot path starts calling it.
var (
	AnalyseCodeEffectCarrier = compiler.AnalyseCodeEffectCarrier
	ClosureWantsKeyVal       = compiler.ClosureWantsKeyVal
	CompiledRef              = compiler.CompiledRef
	ConstOperand             = compiler.ConstOperand
	EventOperand             = compiler.EventOperand
	InterpBodyInert          = compiler.InterpBodyInert
	InterpMemberInert        = compiler.InterpMemberInert
	IsCompiledClosure        = compiler.IsCompiledClosure
	RewritePromotedRefs      = compiler.RewritePromotedRefs
	StampCompiledRef         = compiler.StampCompiledRef
	StampDetachedSig         = compiler.StampDetachedSig
	StampFnValue             = compiler.StampFnValue
	StampFnValueInPlace      = compiler.StampFnValueInPlace
	TryRecordFallback        = compiler.TryRecordFallback
)

func NewClosure(a0 int, a1 []core.Value) core.Value { return compiler.NewClosure(a0, a1) }

func NewEmitState() *compiler.EmitState { return compiler.NewEmitState() }

func StampDetachedFn(a0 *core.Registry, a1 core.FnDefInfo, a2 core.SrcPos) (*compiler.CompiledFnRef, bool) {
	return compiler.StampDetachedFn(a0, a1, a2)
}
