// Code generated by piecetool -facade; DO NOT EDIT.
//
// The eng facade over the core module (design/ENG-FOUR-PIECE.0.md
// Stage 4): type aliases are zero-cost, the function wrappers are thin
// enough to inline, and set-once vars mirror by value at init (core's
// package init completes first). Mutable slot tables are NOT mirrored —
// their installers write core.X directly.
package eng

import (
	"context"
	"io"
	"math/big"
	"regexp"
	"time"

	check "github.com/boru-lang/boru/check/go"
	compiler "github.com/boru-lang/boru/compiler/go"
	core "github.com/boru-lang/boru/core/go"
	apd "github.com/cockroachdb/apd/v3"
)

var _ = context.Canceled
var _ io.Reader
var _ big.Int
var _ regexp.Regexp
var _ time.Time
var _ apd.Decimal
var _ = core.TheInactiveEmit
var _ = check.DispatchBraid
var _ compiler.EmitState

type (
	BailEvent         = core.BailEvent
	BoolPayload       = core.BoolPayload
	BoruError         = core.BoruError
	BoruImpl          = core.BoruImpl
	BranchRecord      = core.BranchRecord
	CallableSpec      = core.CallableSpec
	CapturedBinding   = core.CapturedBinding
	CheckDiagnostic   = core.CheckDiagnostic
	CheckState        = core.CheckState
	ChildEntry        = core.ChildEntry
	ChildTypeInfo     = core.ChildTypeInfo
	ClassInstanceInfo = core.ClassInstanceInfo
	ClassTypeInfo     = core.ClassTypeInfo
	ClosurePayload    = core.ClosurePayload
	CompileEffect     = core.CompileEffect
	DeclSite          = core.DeclSite
	DefTable          = core.DefTable
	DispatchModInfo   = core.DispatchModInfo
	EffectLedger      = core.EffectLedger
	EmitFragmentRef   = core.EmitFragmentRef
	Engine            = core.Engine
	ErrorInfo         = core.ErrorInfo
	ExtensionPayload  = core.ExtensionPayload
	FallbackSpan      = core.FallbackSpan
	FlexListData      = core.FlexListData
	FlowCtrl          = core.FlowCtrl
	FnDefInfo         = core.FnDefInfo
	FnFrameMeta       = core.FnFrameMeta
	FnParam           = core.FnParam
	FnSig             = core.FnSig
	FnSigSpec         = core.FnSigSpec
	FnUndefInfo       = core.FnUndefInfo
	ForCont           = core.ForCont
	ForwardInfo       = core.ForwardInfo
	FrameTailSpec     = core.FrameTailSpec
	GuardFactInfo     = core.GuardFactInfo
	Handler           = core.Handler
	HostTypeBody      = core.HostTypeBody
	Ideal             = core.Ideal
	IdealRegistry     = core.IdealRegistry
	IfCont            = core.IfCont
	IntPayload        = core.IntPayload
	InterpEntry       = core.InterpEntry
	InterpPart        = core.InterpPart
	ListPayload       = core.ListPayload
	MapPayload        = core.MapPayload
	ModuleCallChecker = core.ModuleCallChecker
	ModuleCallID      = core.ModuleCallID
	ModuleDesc        = core.ModuleDesc
	ModuleRegistry    = core.ModuleRegistry
	NativeFunc        = core.NativeFunc
	OrderedMap        = core.OrderedMap
	PolicyDenied      = core.PolicyDenied
	PolyNoMatchSpec   = core.PolyNoMatchSpec
	ReachInfo         = core.ReachInfo
	ReachSeg          = core.ReachSeg
	RecordTypeInfo    = core.RecordTypeInfo
	Recorder          = core.Recorder
	Registry          = core.Registry
	ResourceTypeInfo  = core.ResourceTypeInfo
	ReturnsFunc       = core.ReturnsFunc
	SigImpl           = core.SigImpl
	Signature         = core.Signature
	SrcPos            = core.SrcPos
	StoreInstanceInfo = core.StoreInstanceInfo
	StoreShapeInfo    = core.StoreShapeInfo
	StrPayload        = core.StrPayload
	SyncWriter        = core.SyncWriter
	TableData         = core.TableData
	TableTypeInfo     = core.TableTypeInfo
	Tape              = core.Tape
	TapeConfig        = core.TapeConfig
	Type              = core.Type
	TypeTable         = core.TypeTable
	TypedBindSpec     = core.TypedBindSpec
	Value             = core.Value
	WordChecker       = core.WordChecker
	WordInfo          = core.WordInfo
	XmlAttrTmpl       = core.XmlAttrTmpl
	XmlCren           = core.XmlCren
	XmlTmpl           = core.XmlTmpl
)

const (
	BarrierAllForward       = core.BarrierAllForward
	BodyOutResidual         = core.BodyOutResidual
	CapPolicy               = core.CapPolicy
	CompileDynBody          = core.CompileDynBody
	CompileFallbackBody     = core.CompileFallbackBody
	CompileIslandPure       = core.CompileIslandPure
	CompileStoresBody       = core.CompileStoresBody
	CompileStoresFn         = core.CompileStoresFn
	DefaultStepLimit        = core.DefaultStepLimit
	DefaultTapeGrowthFactor = core.DefaultTapeGrowthFactor
	DefaultTapeInitialFloor = core.DefaultTapeInitialFloor
	DefaultTapeMaxGrows     = core.DefaultTapeMaxGrows
	DepGTE                  = core.DepGTE
	DepLTE                  = core.DepLTE
	ExitCodeKey             = core.ExitCodeKey
	ExitErrorCode           = core.ExitErrorCode
	FlowBreak               = core.FlowBreak
	FlowContinue            = core.FlowContinue
	FlowNone                = core.FlowNone
	OverflowBlock           = core.OverflowBlock
	OverflowDrop            = core.OverflowDrop
	OverflowFail            = core.OverflowFail
	SeverityError           = core.SeverityError
	SeverityInfo            = core.SeverityInfo
	SeverityWarning         = core.SeverityWarning
	StackHeadroom           = core.StackHeadroom
	TypedBindDepScalar      = core.TypedBindDepScalar
	XmlCrenChild            = core.XmlCrenChild
	XmlCrenExpr             = core.XmlCrenExpr
	XmlCrenLit              = core.XmlCrenLit
)

var (
	Builtin            = core.Builtin
	ErrMailboxOverload = core.ErrMailboxOverload
	ErrRuntimeDown     = core.ErrRuntimeDown
	TAny               = core.TAny
	TAtom              = core.TAtom
	TBoolean           = core.TBoolean
	TClass             = core.TClass
	TEnum              = core.TEnum
	TError             = core.TError
	TFlexXml           = core.TFlexXml
	TFloat             = core.TFloat
	TFnUndef           = core.TFnUndef
	TFunction          = core.TFunction
	TIdeal             = core.TIdeal
	TInspect           = core.TInspect
	TInteger           = core.TInteger
	TList              = core.TList
	TMap               = core.TMap
	TMicron            = core.TMicron
	TNever             = core.TNever
	TNode              = core.TNode
	TNone              = core.TNone
	TNumber            = core.TNumber
	TParenExpr         = core.TParenExpr
	TPathon            = core.TPathon
	TReach             = core.TReach
	TRecord            = core.TRecord
	TResource          = core.TResource
	TScalar            = core.TScalar
	TStore             = core.TStore
	TString            = core.TString
	TTable             = core.TTable
	TType              = core.TType
	TWord              = core.TWord
	TXml               = core.TXml
	TheInactiveEmit    = core.TheInactiveEmit
)

// Cold func-value re-exports: exported core funcs no suite calls
// through the facade (API surface only — lang re-export vars,
// short-circuited operands, external embedders). A var of func type
// keeps every reference site compiling verbatim with no wrapper body
// to leave uncovered; a name moves back up to a wrapper func when a
// hot path starts calling it.
var (
	AppendFrameTail          = core.AppendFrameTail
	AsAtom                   = core.AsAtom
	AsBigDecimal             = core.AsBigDecimal
	AsBigInteger             = core.AsBigInteger
	AsBoolean                = core.AsBoolean
	AsDefCleanup             = core.AsDefCleanup
	AsDispatchMod            = core.AsDispatchMod
	AsError                  = core.AsError
	AsFlexXml                = core.AsFlexXml
	AsFloatApprox            = core.AsFloatApprox
	AsFrameOpen              = core.AsFrameOpen
	AsMark                   = core.AsMark
	AsMove                   = core.AsMove
	AsPathon                 = core.AsPathon
	AsReach                  = core.AsReach
	AsResourceType           = core.AsResourceType
	AsReturnCheck            = core.AsReturnCheck
	AsStore                  = core.AsStore
	AtomReferent             = core.AtomReferent
	BodyTokens               = core.BodyTokens
	Boru                     = core.Boru
	BuildReturnCountError    = core.BuildReturnCountError
	BuildReturnTypeError     = core.BuildReturnTypeError
	BuiltinInitError         = core.BuiltinInitError
	CanonValue               = core.CanonValue
	CanonicalType            = core.CanonicalType
	CloneValue               = core.CloneValue
	CommonAncestorType       = core.CommonAncestorType
	CompareValues            = core.CompareValues
	CowDel                   = core.CowDel
	ExactEqual               = core.ExactEqual
	ExitCode                 = core.ExitCode
	ExpandOptionalSigs       = core.ExpandOptionalSigs
	FlexDeepCopy             = core.FlexDeepCopy
	FnSigSatisfiesSpec       = core.FnSigSatisfiesSpec
	FnUndefMatchesFnDef      = core.FnUndefMatchesFnDef
	FoldVariadicArms         = core.FoldVariadicArms
	FormatBigDecimal         = core.FormatBigDecimal
	FormatBigInteger         = core.FormatBigInteger
	FormatFloat              = core.FormatFloat
	FormatForPrint           = core.FormatForPrint
	FormatValueJSON          = core.FormatValueJSON
	FromNative               = core.FromNative
	GrowthCeiling            = core.GrowthCeiling
	InstallCompiledRuntime   = core.InstallCompiledRuntime
	InstallFrameBinding      = core.InstallFrameBinding
	InvokeCallback           = core.InvokeCallback
	IsAppliableFn            = core.IsAppliableFn
	IsAtom                   = core.IsAtom
	IsCloseParen             = core.IsCloseParen
	IsDefCleanup             = core.IsDefCleanup
	IsDelegationFnDef        = core.IsDelegationFnDef
	IsError                  = core.IsError
	IsFlexMap                = core.IsFlexMap
	IsFlexXml                = core.IsFlexXml
	IsFnTypedCarrier         = core.IsFnTypedCarrier
	IsFnValueResidual        = core.IsFnValueResidual
	IsForward                = core.IsForward
	IsFrameOpen              = core.IsFrameOpen
	IsHostTypeBody           = core.IsHostTypeBody
	IsImplicitMap            = core.IsImplicitMap
	IsInternalErr            = core.IsInternalErr
	IsInternalMarker         = core.IsInternalMarker
	IsInterpString           = core.IsInterpString
	IsMark                   = core.IsMark
	IsMicronType             = core.IsMicronType
	IsMove                   = core.IsMove
	IsOpenParen              = core.IsOpenParen
	IsParenExpr              = core.IsParenExpr
	IsPathon                 = core.IsPathon
	IsReach                  = core.IsReach
	IsResourceType           = core.IsResourceType
	IsReturnCheck            = core.IsReturnCheck
	IsSplice                 = core.IsSplice
	IsTypeLiteral            = core.IsTypeLiteral
	IsTypeValue              = core.IsTypeValue
	JoinCarriers             = core.JoinCarriers
	LookupModuleCallChecker  = core.LookupModuleCallChecker
	LookupWordChecker        = core.LookupWordChecker
	MakeBoruError            = core.MakeBoruError
	MakeBoruErrorAt          = core.MakeBoruErrorAt
	MakeHandler              = core.MakeHandler
	MakeObjHandler           = core.MakeObjHandler
	MakePathon               = core.MakePathon
	MakeScalarHandler        = core.MakeScalarHandler
	MakeScalarOptsHandler    = core.MakeScalarOptsHandler
	MakeWithOpts             = core.MakeWithOpts
	MapFieldBoolean          = core.MapFieldBoolean
	MapFieldFloat            = core.MapFieldFloat
	MapFieldInteger          = core.MapFieldInteger
	MapFieldString           = core.MapFieldString
	MatchSignature           = core.MatchSignature
	MintTestType             = core.MintTestType
	NewBigDecimal            = core.NewBigDecimal
	NewBigInteger            = core.NewBigInteger
	NewClassInstance         = core.NewClassInstance
	NewDefTable              = core.NewDefTable
	NewDepScalar             = core.NewDepScalar
	NewDisjunct              = core.NewDisjunct
	NewDispatchMod           = core.NewDispatchMod
	NewDynamicCarrierValue   = core.NewDynamicCarrierValue
	NewDynamicTypeTable      = core.NewDynamicTypeTable
	NewEnd                   = core.NewEnd
	NewEvalList              = core.NewEvalList
	NewEvalMap               = core.NewEvalMap
	NewExitError             = core.NewExitError
	NewExtension             = core.NewExtension
	NewFlexList              = core.NewFlexList
	NewFlexMap               = core.NewFlexMap
	NewForward               = core.NewForward
	NewFrameOpen             = core.NewFrameOpen
	NewIdealRegistry         = core.NewIdealRegistry
	NewImplicitMap           = core.NewImplicitMap
	NewInterpString          = core.NewInterpString
	NewModuleRegistry        = core.NewModuleRegistry
	NewNegation              = core.NewNegation
	NewOptionsType           = core.NewOptionsType
	NewParenExpr             = core.NewParenExpr
	NewPathonFromString      = core.NewPathonFromString
	NewProcess               = core.NewProcess
	NewProcessRuntime        = core.NewProcessRuntime
	NewReach                 = core.NewReach
	NewReachFromKeys         = core.NewReachFromKeys
	NewReadList              = core.NewReadList
	NewRegistry              = core.NewRegistry
	NewResourceType          = core.NewResourceType
	NewStoreValue            = core.NewStoreValue
	NewStoreWithPrototype    = core.NewStoreWithPrototype
	NewTableType             = core.NewTableType
	NewTape                  = core.NewTape
	NewTapeWith              = core.NewTapeWith
	NewTypedList             = core.NewTypedList
	NewTypedListWithElements = core.NewTypedListWithElements
	NewTypedMap              = core.NewTypedMap
	NewTypedMapWithEntries   = core.NewTypedMapWithEntries
	NewWordUsurp             = core.NewWordUsurp
	NewXmlElement            = core.NewXmlElement
	NewXmlInterp             = core.NewXmlInterp
	NoMatchDiag              = core.NoMatchDiag
	NodeDeepCopy             = core.NodeDeepCopy
	OpenUnifyMap             = core.OpenUnifyMap
	PadRight                 = core.PadRight
	PopFrameArgs             = core.PopFrameArgs
	PrintHandler             = core.PrintHandler
	PrintstrHandler          = core.PrintstrHandler
	RebuildXmlFromTmpl       = core.RebuildXmlFromTmpl
	ReorderHintFor           = core.ReorderHintFor
	ReparentValue            = core.ReparentValue
	RequireConcreteList      = core.RequireConcreteList
	ResolveChildTypeExpr     = core.ResolveChildTypeExpr
	ResolveRef               = core.ResolveRef
	ResolveSigChildParam     = core.ResolveSigChildParam
	ResolveTypeLiteralDef    = core.ResolveTypeLiteralDef
	ResolveWordsDeepR        = core.ResolveWordsDeepR
	RetagTypedContainerValue = core.RetagTypedContainerValue
	RunPooled                = core.RunPooled
	RunPooledSub             = core.RunPooledSub
	RunResolved              = core.RunResolved
	RunTrace                 = core.RunTrace
	RunTypedBind             = core.RunTypedBind
	RuntimeNoMatch           = core.RuntimeNoMatch
	SetAtomReferent          = core.SetAtomReferent
	Shape                    = core.Shape
	SigArgType               = core.SigArgType
	SigTypeMatches           = core.SigTypeMatches
	SpliceExpand             = core.SpliceExpand
	StampModuleCallGates     = core.StampModuleCallGates
	StampedModuleCall        = core.StampedModuleCall
	StepLimitFor             = core.StepLimitFor
	StripAscribed            = core.StripAscribed
	TandHandler              = core.TandHandler
	ToNative                 = core.ToNative
	TorHandler               = core.TorHandler
	TorReturnsFn             = core.TorReturnsFn
	TraceColorize            = core.TraceColorize
	TraceHandler             = core.TraceHandler
	TraceWrap                = core.TraceWrap
	TypeNameTable            = core.TypeNameTable
	UnifyExplain             = core.UnifyExplain
	UnifyR                   = core.UnifyR
	ValToString              = core.ValToString
	ValuesEqual              = core.ValuesEqual
)

func ApplyComplementNarrowing(a0 *core.Registry, a1 core.Value) func() {
	return core.ApplyComplementNarrowing(a0, a1)
}

func ApplyGuardNarrowing(a0 *core.Registry, a1 core.Value) func() {
	return core.ApplyGuardNarrowing(a0, a1)
}

func AsChildType(a0 core.Value) (core.ChildTypeInfo, error) { return core.AsChildType(a0) }

func AsClassInstance(a0 core.Value) (core.ClassInstanceInfo, error) { return core.AsClassInstance(a0) }

func AsClassType(a0 core.Value) (core.ClassTypeInfo, error) { return core.AsClassType(a0) }

func AsDisjunct(a0 core.Value) (core.DisjunctInfo, error) { return core.AsDisjunct(a0) }

func AsFloat(a0 core.Value) (float64, error) { return core.AsFloat(a0) }

func AsInteger(a0 core.Value) (int64, error) { return core.AsInteger(a0) }

func AsList(a0 core.Value) (core.ReadList, error) { return core.AsList(a0) }

func AsMap(a0 core.Value) (core.ReadMap, error) { return core.AsMap(a0) }

func AsMutableMap(a0 core.Value) (*core.OrderedMap, error) { return core.AsMutableMap(a0) }

func AsRecordType(a0 core.Value) (core.RecordTypeInfo, error) { return core.AsRecordType(a0) }

func AsString(a0 core.Value) (string, error) { return core.AsString(a0) }

func AsTableType(a0 core.Value) (core.TableTypeInfo, error) { return core.AsTableType(a0) }

func AsWord(a0 core.Value) (core.WordInfo, error) { return core.AsWord(a0) }

func BoolWord(a0 bool) string { return core.BoolWord(a0) }

func BoundToKind(a0 *core.DepBound, a1 bool) core.DepKind { return core.BoundToKind(a0, a1) }

func Canon(a0 []core.Value) string { return core.Canon(a0) }

func CoerceBoolean(a0 core.Value) bool { return core.CoerceBoolean(a0) }

func DeepEqual(a0 core.Value, a1 core.Value) bool { return core.DeepEqual(a0, a1) }

func GenerateObjectTypeID() string { return core.GenerateObjectTypeID() }

func GetKey(a0 core.Value) string { return core.GetKey(a0) }

func Go(a0 core.Handler, a1 ...core.GoOpt) *core.GoImpl { return core.Go(a0, a1...) }

func InstallDef(a0 *core.Registry, a1 string, a2 core.Value, a3 ...bool) {
	core.InstallDef(a0, a1, a2, a3...)
}

func InstallFnDef(a0 *core.Registry, a1 string, a2 core.FnDefInfo, a3 ...bool) {
	core.InstallFnDef(a0, a1, a2, a3...)
}

func InstallJoinedDefs(a0 *core.Registry, a1 map[string]core.Value, a2 map[string]core.Value) {
	core.InstallJoinedDefs(a0, a1, a2)
}

func InstallType(a0 *core.Registry, a1 string, a2 core.Value) error {
	return core.InstallType(a0, a1, a2)
}

func InvokeBody(a0 *core.Registry, a1 core.Value, a2 []core.Value) ([]core.Value, error) {
	return core.InvokeBody(a0, a1, a2)
}

func IsBareTypeNode(a0 core.Value) bool { return core.IsBareTypeNode(a0) }

func IsCapitalisedName(a0 string) bool { return core.IsCapitalisedName(a0) }

func IsClassType(a0 core.Value) bool { return core.IsClassType(a0) }

func IsConcrete(a0 core.Value) bool { return core.IsConcrete(a0) }

func IsDisjunct(a0 core.Value) bool { return core.IsDisjunct(a0) }

func IsOptionsType(a0 core.Value) bool { return core.IsOptionsType(a0) }

func IsRecordShape(a0 core.Value) bool { return core.IsRecordShape(a0) }

func IsRecordType(a0 core.Value) bool { return core.IsRecordType(a0) }

func IsTableType(a0 core.Value) bool { return core.IsTableType(a0) }

func IsTypeBody(a0 core.Value) bool { return core.IsTypeBody(a0) }

func IsTypedList(a0 core.Value) bool { return core.IsTypedList(a0) }

func IsTypedMap(a0 core.Value) bool { return core.IsTypedMap(a0) }

func IsValueOfType(a0 core.Value, a1 core.Value) bool { return core.IsValueOfType(a0, a1) }

func IsWord(a0 core.Value) bool { return core.IsWord(a0) }

func JoinCarrierStacks(a0 []core.Value, a1 []core.Value) []core.Value {
	return core.JoinCarrierStacks(a0, a1)
}

func LiteralCondValue(a0 core.Value) (bool, bool) { return core.LiteralCondValue(a0) }

func New(a0 *core.Registry) *core.Engine { return core.New(a0) }

func NewAtom(a0 string) core.Value { return core.NewAtom(a0) }

func NewBoolean(a0 bool) core.Value { return core.NewBoolean(a0) }

func NewCarrier(a0 *core.Type) core.Value { return core.NewCarrier(a0) }

func NewCarrierTypedList(a0 *core.Type) core.Value { return core.NewCarrierTypedList(a0) }

func NewCarrierTypedListValue(a0 core.Value) core.Value { return core.NewCarrierTypedListValue(a0) }

func NewClassType(a0 *core.Type, a1 core.ClassTypeInfo) core.Value { return core.NewClassType(a0, a1) }

func NewCloseParen() core.Value { return core.NewCloseParen() }

func NewDynamicCarrier(a0 *core.Type) core.Value { return core.NewDynamicCarrier(a0) }

func NewEnum(a0 []core.Value) core.Value { return core.NewEnum(a0) }

func NewError(a0 error) core.Value { return core.NewError(a0) }

func NewFloat(a0 float64) core.Value { return core.NewFloat(a0) }

func NewFnUndef(a0 core.FnUndefInfo) core.Value { return core.NewFnUndef(a0) }

func NewFunction(a0 core.FnDefInfo) core.Value { return core.NewFunction(a0) }

func NewInteger(a0 int64) core.Value { return core.NewInteger(a0) }

func NewList(a0 []core.Value) core.Value { return core.NewList(a0) }

func NewMap(a0 *core.OrderedMap) core.Value { return core.NewMap(a0) }

func NewMark(a0 string, a1 ...core.Value) core.Value { return core.NewMark(a0, a1...) }

func NewMove(a0 string, a1 string) core.Value { return core.NewMove(a0, a1) }

func NewMoveCont(a0 string, a1 string, a2 *core.ForCont) core.Value {
	return core.NewMoveCont(a0, a1, a2)
}

func NewMoveIf(a0 string, a1 string, a2 *core.IfCont) core.Value { return core.NewMoveIf(a0, a1, a2) }

func NewNone() core.Value { return core.NewNone() }

func NewOpenParen() core.Value { return core.NewOpenParen() }

func NewOrderedMap() *core.OrderedMap { return core.NewOrderedMap() }

func NewRecordType(a0 *core.OrderedMap) core.Value { return core.NewRecordType(a0) }

func NewSplice(a0 core.Value) core.Value { return core.NewSplice(a0) }

func NewString(a0 string) core.Value { return core.NewString(a0) }

func NewTop(a0 *core.Registry) *core.Engine { return core.NewTop(a0) }

func NewTypeLiteral(a0 *core.Type) core.Value { return core.NewTypeLiteral(a0) }

func NewValueRaw(a0 *core.Type, a1 core.Payload) core.Value { return core.NewValueRaw(a0, a1) }

func NewWord(a0 string) core.Value { return core.NewWord(a0) }

func NewWordModified(a0 string, a1 int, a2 bool, a3 bool) core.Value {
	return core.NewWordModified(a0, a1, a2, a3)
}

func NextMarkID() string { return core.NextMarkID() }

func ParseFnDef(a0 *core.Registry, a1 []core.Value) (core.FnDefInfo, error) {
	return core.ParseFnDef(a0, a1)
}

func ParseFnUndefSpec(a0 *core.Registry, a1 []core.Value) (core.FnUndefInfo, error) {
	return core.ParseFnUndefSpec(a0, a1)
}

func PathOf(a0 core.Value) core.Value { return core.PathOf(a0) }

func ResolveBuiltinTypeName(a0 string) (*core.Type, bool) { return core.ResolveBuiltinTypeName(a0) }

func ResolveFieldType(a0 *core.Registry, a1 core.Value) core.Value {
	return core.ResolveFieldType(a0, a1)
}

func ReturnsIdentity(a0 ...int) core.ReturnsFunc { return core.ReturnsIdentity(a0...) }

func RunCarrierBody(a0 *core.Registry, a1 core.Value) []core.Value {
	return core.RunCarrierBody(a0, a1)
}

func RunCarrierBodyKeepDefs(a0 *core.Registry, a1 core.Value) []core.Value {
	return core.RunCarrierBodyKeepDefs(a0, a1)
}

func RunCarrierBodyWithDefs(a0 *core.Registry, a1 core.Value) ([]core.Value, map[string]core.Value) {
	return core.RunCarrierBodyWithDefs(a0, a1)
}

func RunCarrierCondBody(a0 *core.Registry, a1 core.Value) ([]core.Value, map[string]core.Value) {
	return core.RunCarrierCondBody(a0, a1)
}

func RunInCheck() core.GoOpt { return core.RunInCheck() }

func StoreKey(a0 core.Value) string { return core.StoreKey(a0) }

func TypeNameOf(a0 core.Value) string { return core.TypeNameOf(a0) }

func TypeOf(a0 core.Value) core.Value { return core.TypeOf(a0) }

func TypePathOf(a0 core.Value) string { return core.TypePathOf(a0) }

func Unify(a0 core.Value, a1 core.Value) (core.Value, bool) { return core.Unify(a0, a1) }

func UninstallDef(a0 *core.Registry, a1 string) { core.UninstallDef(a0, a1) }

func ValidateWordName(a0 string) error { return core.ValidateWordName(a0) }

func ValueType(a0 core.Value) *core.Type { return core.ValueType(a0) }
