// Code generated by piecetool -facade; DO NOT EDIT.
//
// The eng facade over the core module (design/ENG-FOUR-PIECE.0.md
// Stage 4): type aliases are zero-cost, the function wrappers are thin
// enough to inline, and set-once vars mirror by value at init (core's
// package init completes first). Mutable slot tables are NOT mirrored —
// their installers write core.X directly.
package eng

import (
	"context"
	"io"
	"math/big"
	"regexp"
	"time"

	check "github.com/boru-lang/boru/check/go"
	compiler "github.com/boru-lang/boru/compiler/go"
	core "github.com/boru-lang/boru/core/go"
	apd "github.com/cockroachdb/apd/v3"
)

var _ = context.Canceled
var _ io.Reader
var _ big.Int
var _ regexp.Regexp
var _ time.Time
var _ apd.Decimal
var _ = core.TheInactiveEmit
var _ = check.DispatchBraid
var _ compiler.EmitState

type (
	ArgsStack            = core.ArgsStack
	AtomPayload          = core.AtomPayload
	BailEvent            = core.BailEvent
	BigIntPayload        = core.BigIntPayload
	BoolPayload          = core.BoolPayload
	BoruError            = core.BoruError
	BoruImpl             = core.BoruImpl
	BranchRecord         = core.BranchRecord
	CalDurationData      = core.CalDurationData
	CallableSpec         = core.CallableSpec
	CandidateFailure     = core.CandidateFailure
	CapabilityRegistry   = core.CapabilityRegistry
	CapturedBinding      = core.CapturedBinding
	CheckDiagnostic      = core.CheckDiagnostic
	CheckFullStackFunc   = core.CheckFullStackFunc
	CheckSeverity        = core.CheckSeverity
	CheckState           = core.CheckState
	ChildEntry           = core.ChildEntry
	ChildTypeInfo        = core.ChildTypeInfo
	ClassInstanceInfo    = core.ClassInstanceInfo
	ClassTypeInfo        = core.ClassTypeInfo
	ClosureInShape       = core.ClosureInShape
	ClosurePayload       = core.ClosurePayload
	CodeEffectInfo       = core.CodeEffectInfo
	Comparer             = core.Comparer
	CompileEffect        = core.CompileEffect
	CompileSandbox       = core.CompileSandbox
	CompiledRuntime      = core.CompiledRuntime
	ConstBakeable        = core.ConstBakeable
	ContentMembership    = core.ContentMembership
	ContextStack         = core.ContextStack
	DebugTraceFrom       = core.DebugTraceFrom
	DecimalPayload       = core.DecimalPayload
	DeclSite             = core.DeclSite
	DeepCloner           = core.DeepCloner
	DeepEqualer          = core.DeepEqualer
	DefCleanupInfo       = core.DefCleanupInfo
	DefEntry             = core.DefEntry
	DefTable             = core.DefTable
	DepBound             = core.DepBound
	DepKind              = core.DepKind
	DepScalarInfo        = core.DepScalarInfo
	DepScalarUnifier     = core.DepScalarUnifier
	DeqIndex             = core.DeqIndex
	DeqKeyClass          = core.DeqKeyClass
	DiagSpan             = core.DiagSpan
	DiagSuggestion       = core.DiagSuggestion
	DisjunctInfo         = core.DisjunctInfo
	DisjunctUnifier      = core.DisjunctUnifier
	DispatchModInfo      = core.DispatchModInfo
	DurationPayload      = core.DurationPayload
	EffectLedger         = core.EffectLedger
	EmitCheckpoint       = core.EmitCheckpoint
	EmitCheckpointBase   = core.EmitCheckpointBase
	EmitFragmentRef      = core.EmitFragmentRef
	EmitRecorder         = core.EmitRecorder
	Engine               = core.Engine
	EngineState          = core.EngineState
	ErrorCode            = core.ErrorCode
	ErrorInfo            = core.ErrorInfo
	ExtensionPayload     = core.ExtensionPayload
	FallbackSpan         = core.FallbackSpan
	FlexListData         = core.FlexListData
	FlexXmlData          = core.FlexXmlData
	FloatPayload         = core.FloatPayload
	FlowCtrl             = core.FlowCtrl
	FnDefInfo            = core.FnDefInfo
	FnFrameMeta          = core.FnFrameMeta
	FnParam              = core.FnParam
	FnSig                = core.FnSig
	FnSigSpec            = core.FnSigSpec
	FnUndefInfo          = core.FnUndefInfo
	ForCont              = core.ForCont
	FormatDelegate       = core.FormatDelegate
	ForwardInfo          = core.ForwardInfo
	FrameOpenInfo        = core.FrameOpenInfo
	FrameTailSpec        = core.FrameTailSpec
	GenInstRef           = core.GenInstRef
	GenParam             = core.GenParam
	GenSpecInfo          = core.GenSpecInfo
	GoImpl               = core.GoImpl
	GoOpt                = core.GoOpt
	GuardFactInfo        = core.GuardFactInfo
	Handler              = core.Handler
	Hasher               = core.Hasher
	HostTypeBody         = core.HostTypeBody
	Ideal                = core.Ideal
	IdealConverter       = core.IdealConverter
	IdealRegistry        = core.IdealRegistry
	IfCont               = core.IfCont
	IntPayload           = core.IntPayload
	InterpEntry          = core.InterpEntry
	InterpPart           = core.InterpPart
	InterpStringPayload  = core.InterpStringPayload
	IntervalInfo         = core.IntervalInfo
	ListPayload          = core.ListPayload
	MapPayload           = core.MapPayload
	MarkInfo             = core.MarkInfo
	MatchDelegating      = core.MatchDelegating
	MatchResult          = core.MatchResult
	Materializer         = core.Materializer
	MaterializerPayload  = core.MaterializerPayload
	MemberUnifier        = core.MemberUnifier
	MicronPayload        = core.MicronPayload
	MicronSubtypeMinter  = core.MicronSubtypeMinter
	MicronTypeInfo       = core.MicronTypeInfo
	ModuleCallChecker    = core.ModuleCallChecker
	ModuleCallID         = core.ModuleCallID
	ModuleDesc           = core.ModuleDesc
	ModuleNSInfo         = core.ModuleNSInfo
	ModuleRegistry       = core.ModuleRegistry
	MoveInfo             = core.MoveInfo
	NativeFunc           = core.NativeFunc
	NegationInfo         = core.NegationInfo
	NegationUnifier      = core.NegationUnifier
	Nodifier             = core.Nodifier
	NonePayload          = core.NonePayload
	OptionsTypeInfo      = core.OptionsTypeInfo
	OrderedMap           = core.OrderedMap
	OriginKind           = core.OriginKind
	ParenExprPayload     = core.ParenExprPayload
	PathonInfo           = core.PathonInfo
	PathonPayload        = core.PathonPayload
	Payload              = core.Payload
	PayloadBase          = core.PayloadBase
	PendingMethodApply   = core.PendingMethodApply
	PolicyDenied         = core.PolicyDenied
	PolyNoMatchSpec      = core.PolyNoMatchSpec
	PredicateUnifier     = core.PredicateUnifier
	Process              = core.Process
	ProcessRuntime       = core.ProcessRuntime
	ReachInfo            = core.ReachInfo
	ReachSeg             = core.ReachSeg
	ReadList             = core.ReadList
	ReadMap              = core.ReadMap
	RecordTypeInfo       = core.RecordTypeInfo
	Recorder             = core.Recorder
	RecorderSkipper      = core.RecorderSkipper
	Registry             = core.Registry
	RenderOpts           = core.RenderOpts
	ResourceInstanceInfo = core.ResourceInstanceInfo
	ResourceTypeInfo     = core.ResourceTypeInfo
	ReturnCheckInfo      = core.ReturnCheckInfo
	ReturnsFunc          = core.ReturnsFunc
	SchemaKind           = core.SchemaKind
	SigImpl              = core.SigImpl
	Signature            = core.Signature
	Sizer                = core.Sizer
	SpliceInfo           = core.SpliceInfo
	SrcPos               = core.SrcPos
	StampEvent           = core.StampEvent
	StoreInstanceInfo    = core.StoreInstanceInfo
	StoreShapeInfo       = core.StoreShapeInfo
	StoredBodySpec       = core.StoredBodySpec
	StrPayload           = core.StrPayload
	SubtypeNamer         = core.SubtypeNamer
	SugarInfo            = core.SugarInfo
	SugarKind            = core.SugarKind
	SurfaceInfo          = core.SurfaceInfo
	SyncWriter           = core.SyncWriter
	TCOState             = core.TCOState
	TableData            = core.TableData
	TableTypeInfo        = core.TableTypeInfo
	Tape                 = core.Tape
	TapeConfig           = core.TapeConfig
	TimePayload          = core.TimePayload
	TimeoutInfo          = core.TimeoutInfo
	TimezonePayload      = core.TimezonePayload
	TraceCallback        = core.TraceCallback
	Truther              = core.Truther
	Type                 = core.Type
	TypeBehavior         = core.TypeBehavior
	TypeSchemaInfo       = core.TypeSchemaInfo
	TypeTable            = core.TypeTable
	TypedBindKind        = core.TypedBindKind
	TypedBindSpec        = core.TypedBindSpec
	Unifier              = core.Unifier
	UnifyError           = core.UnifyError
	Value                = core.Value
	ValueShape           = core.ValueShape
	Walker               = core.Walker
	WeakFlexListData     = core.WeakFlexListData
	WeakFlexMapData      = core.WeakFlexMapData
	WeakFlexXmlData      = core.WeakFlexXmlData
	WeakRefusal          = core.WeakRefusal
	WordChecker          = core.WordChecker
	WordInfo             = core.WordInfo
	XmlAttrTmpl          = core.XmlAttrTmpl
	XmlCren              = core.XmlCren
	XmlCrenKind          = core.XmlCrenKind
	XmlElementPayload    = core.XmlElementPayload
	XmlInterpPayload     = core.XmlInterpPayload
	XmlTmpl              = core.XmlTmpl
)

const (
	BarrierAllForward       = core.BarrierAllForward
	BodyOutResidual         = core.BodyOutResidual
	CapPolicy               = core.CapPolicy
	CompileDefault          = core.CompileDefault
	CompileDiverges         = core.CompileDiverges
	CompileDynBody          = core.CompileDynBody
	CompileExecutesBody     = core.CompileExecutesBody
	CompileFallbackBody     = core.CompileFallbackBody
	CompileFnHandlerStrict  = core.CompileFnHandlerStrict
	CompileIslandPure       = core.CompileIslandPure
	CompileModuleFold       = core.CompileModuleFold
	CompileQuoteInert       = core.CompileQuoteInert
	CompileReadsFn          = core.CompileReadsFn
	CompileRunsBodyIsolated = core.CompileRunsBodyIsolated
	CompileScalarFold       = core.CompileScalarFold
	CompileStoresBody       = core.CompileStoresBody
	CompileStoresBodyList   = core.CompileStoresBodyList
	CompileStoresFn         = core.CompileStoresFn
	CompileValueDiverges    = core.CompileValueDiverges
	DefaultCheckStepBudget  = core.DefaultCheckStepBudget
	DefaultMailboxBound     = core.DefaultMailboxBound
	DefaultStepLimit        = core.DefaultStepLimit
	DefaultSubStepLimit     = core.DefaultSubStepLimit
	DefaultTapeGrowthFactor = core.DefaultTapeGrowthFactor
	DefaultTapeInitialFloor = core.DefaultTapeInitialFloor
	DefaultTapeMaxGrows     = core.DefaultTapeMaxGrows
	DepGT                   = core.DepGT
	DepGTE                  = core.DepGTE
	DepLT                   = core.DepLT
	DepLTE                  = core.DepLTE
	DeqKeyed                = core.DeqKeyed
	DeqNeverEqual           = core.DeqNeverEqual
	DeqUnkeyed              = core.DeqUnkeyed
	ExitCodeKey             = core.ExitCodeKey
	ExitErrorCode           = core.ExitErrorCode
	FlowBreak               = core.FlowBreak
	FlowContinue            = core.FlowContinue
	FlowNone                = core.FlowNone
	KeyValI                 = core.KeyValI
	KeyValK                 = core.KeyValK
	KeyValN                 = core.KeyValN
	KeyValV                 = core.KeyValV
	MaxArgs                 = core.MaxArgs
	OriginBuiltin           = core.OriginBuiltin
	OriginUserDef           = core.OriginUserDef
	OverflowBlock           = core.OverflowBlock
	OverflowDrop            = core.OverflowDrop
	OverflowFail            = core.OverflowFail
	OwnerKernel             = core.OwnerKernel
	OwnerLang               = core.OwnerLang
	OwnerProgram            = core.OwnerProgram
	SchemaClass             = core.SchemaClass
	SchemaFn                = core.SchemaFn
	SchemaFnSig             = core.SchemaFnSig
	SchemaRecord            = core.SchemaRecord
	SeverityError           = core.SeverityError
	SeverityInfo            = core.SeverityInfo
	SeverityWarning         = core.SeverityWarning
	ShapeAbsent             = core.ShapeAbsent
	ShapeAny                = core.ShapeAny
	ShapeCarrier            = core.ShapeCarrier
	ShapeDepScalar          = core.ShapeDepScalar
	ShapeDisjunct           = core.ShapeDisjunct
	ShapeFnUndef            = core.ShapeFnUndef
	ShapeFunction           = core.ShapeFunction
	ShapeList               = core.ShapeList
	ShapeMap                = core.ShapeMap
	ShapeNegation           = core.ShapeNegation
	ShapeNever              = core.ShapeNever
	ShapeNone               = core.ShapeNone
	ShapeObjectInstance     = core.ShapeObjectInstance
	ShapeObjectType         = core.ShapeObjectType
	ShapeOptions            = core.ShapeOptions
	ShapeRecord             = core.ShapeRecord
	ShapeScalar             = core.ShapeScalar
	ShapeTable              = core.ShapeTable
	ShapeTypeLiteral        = core.ShapeTypeLiteral
	ShapeTypedList          = core.ShapeTypedList
	ShapeTypedMap           = core.ShapeTypedMap
	ShapeUnknown            = core.ShapeUnknown
	StackHeadroom           = core.StackHeadroom
	SugarAngle              = core.SugarAngle
	SugarForceArity         = core.SugarForceArity
	SugarForwardArgs        = core.SugarForwardArgs
	SugarGenApply           = core.SugarGenApply
	SugarGenDefault         = core.SugarGenDefault
	SugarGenHead            = core.SugarGenHead
	SugarLambda             = core.SugarLambda
	SugarMini               = core.SugarMini
	SugarStackArgs          = core.SugarStackArgs
	SugarTypeBound          = core.SugarTypeBound
	SugarUsurp              = core.SugarUsurp
	TypedBindDepScalar      = core.TypedBindDepScalar
	TypedBindPredicate      = core.TypedBindPredicate
	TypedBindRefine         = core.TypedBindRefine
	XmlCrenChild            = core.XmlCrenChild
	XmlCrenExpr             = core.XmlCrenExpr
	XmlCrenLit              = core.XmlCrenLit
)

var (
	Builtin              = core.Builtin
	DefaultBehavior      = core.DefaultBehavior
	DynStackShuffleWords = core.DynStackShuffleWords
	ErrMailboxOverload   = core.ErrMailboxOverload
	ErrNoComparer        = core.ErrNoComparer
	ErrNoConverter       = core.ErrNoConverter
	ErrNoDeepEqualer     = core.ErrNoDeepEqualer
	ErrNoNodifier        = core.ErrNoNodifier
	ErrNoTruther         = core.ErrNoTruther
	ErrNoUnifier         = core.ErrNoUnifier
	ErrRuntimeDown       = core.ErrRuntimeDown
	GtHandler            = core.GtHandler
	GteHandler           = core.GteHandler
	LtHandler            = core.LtHandler
	LteHandler           = core.LteHandler
	TAbsent              = core.TAbsent
	TAny                 = core.TAny
	TAtom                = core.TAtom
	TBigDecimal          = core.TBigDecimal
	TBigInteger          = core.TBigInteger
	TBoolean             = core.TBoolean
	TCidron              = core.TCidron
	TClass               = core.TClass
	TCloseParen          = core.TCloseParen
	TColoron             = core.TColoron
	TDefCleanup          = core.TDefCleanup
	TDisjunct            = core.TDisjunct
	TDispatchMod         = core.TDispatchMod
	TEmailon             = core.TEmailon
	TEnd                 = core.TEnd
	TEnum                = core.TEnum
	TError               = core.TError
	TFlexList            = core.TFlexList
	TFlexMap             = core.TFlexMap
	TFlexXml             = core.TFlexXml
	TFloat               = core.TFloat
	TFnUndef             = core.TFnUndef
	TForward             = core.TForward
	TFunction            = core.TFunction
	TGenParam            = core.TGenParam
	TGenSpec             = core.TGenSpec
	THoston              = core.THoston
	TIdeal               = core.TIdeal
	TInspect             = core.TInspect
	TInteger             = core.TInteger
	TInternal            = core.TInternal
	TInterpString        = core.TInterpString
	TIpon                = core.TIpon
	TKeyVal              = core.TKeyVal
	TList                = core.TList
	TListArgs            = core.TListArgs
	TMacon               = core.TMacon
	TMap                 = core.TMap
	TMark                = core.TMark
	TMicron              = core.TMicron
	TMimon               = core.TMimon
	TModule              = core.TModule
	TMove                = core.TMove
	TNegation            = core.TNegation
	TNever               = core.TNever
	TNode                = core.TNode
	TNone                = core.TNone
	TNumber              = core.TNumber
	TOpenParen           = core.TOpenParen
	TOptions             = core.TOptions
	TParenExpr           = core.TParenExpr
	TPathon              = core.TPathon
	TPhonon              = core.TPhonon
	TQion                = core.TQion
	TReach               = core.TReach
	TRecord              = core.TRecord
	TResource            = core.TResource
	TResourceEntity      = core.TResourceEntity
	TReturnCheck         = core.TReturnCheck
	TScalar              = core.TScalar
	TSelf                = core.TSelf
	TSemveron            = core.TSemveron
	TSplice              = core.TSplice
	TStore               = core.TStore
	TStoreSystem         = core.TStoreSystem
	TString              = core.TString
	TStringEmpty         = core.TStringEmpty
	TStringProper        = core.TStringProper
	TSugar               = core.TSugar
	TSurface             = core.TSurface
	TTable               = core.TTable
	TType                = core.TType
	TTypeParam           = core.TTypeParam
	TUrlon               = core.TUrlon
	TWeakFlexList        = core.TWeakFlexList
	TWeakFlexMap         = core.TWeakFlexMap
	TWeakFlexXml         = core.TWeakFlexXml
	TWord                = core.TWord
	TXml                 = core.TXml
	TXmlInterp           = core.TXmlInterp
	TheInactiveEmit      = core.TheInactiveEmit
	TypeNames            = core.TypeNames
)

// Cold func-value re-exports: exported core funcs no suite calls
// through the facade (API surface only — lang re-export vars,
// short-circuited operands, external embedders). A var of func type
// keeps every reference site compiling verbatim with no wrapper body
// to leave uncovered; a name moves back up to a wrapper func when a
// hot path starts calling it.
var (
	AdoptIntoFlex              = core.AdoptIntoFlex
	AdoptIntoNode              = core.AdoptIntoNode
	AppendFrameTail            = core.AppendFrameTail
	ApplyReach                 = core.ApplyReach
	ArgTypeSummary             = core.ArgTypeSummary
	AsAtom                     = core.AsAtom
	AsBigDecimal               = core.AsBigDecimal
	AsBigInteger               = core.AsBigInteger
	AsBoolean                  = core.AsBoolean
	AsBoundedType              = core.AsBoundedType
	AsDefCleanup               = core.AsDefCleanup
	AsDispatchMod              = core.AsDispatchMod
	AsError                    = core.AsError
	AsFlexList                 = core.AsFlexList
	AsFlexXml                  = core.AsFlexXml
	AsFloatApprox              = core.AsFloatApprox
	AsForward                  = core.AsForward
	AsFrameOpen                = core.AsFrameOpen
	AsGenInstRef               = core.AsGenInstRef
	AsGenParamValue            = core.AsGenParamValue
	AsGenSpec                  = core.AsGenSpec
	AsInterpString             = core.AsInterpString
	AsMark                     = core.AsMark
	AsMicronFields             = core.AsMicronFields
	AsMicronType               = core.AsMicronType
	AsModuleDesc               = core.AsModuleDesc
	AsMove                     = core.AsMove
	AsMutableList              = core.AsMutableList
	AsNegation                 = core.AsNegation
	AsNumber                   = core.AsNumber
	AsOptionsType              = core.AsOptionsType
	AsParenExpr                = core.AsParenExpr
	AsPathon                   = core.AsPathon
	AsReach                    = core.AsReach
	AsResourceInstance         = core.AsResourceInstance
	AsResourceType             = core.AsResourceType
	AsReturnCheck              = core.AsReturnCheck
	AsSplice                   = core.AsSplice
	AsStore                    = core.AsStore
	AsSugar                    = core.AsSugar
	AsSurfaceType              = core.AsSurfaceType
	AsTypeSchema               = core.AsTypeSchema
	AsWeakFlexList             = core.AsWeakFlexList
	AsWeakFlexMap              = core.AsWeakFlexMap
	AsWeakFlexXml              = core.AsWeakFlexXml
	AsXmlElement               = core.AsXmlElement
	AsXmlInterp                = core.AsXmlInterp
	AtomReferent               = core.AtomReferent
	AttachGenBound             = core.AttachGenBound
	AutoEvalConsumedList       = core.AutoEvalConsumedList
	AutoEvalConsumedMap        = core.AutoEvalConsumedMap
	BaseValue                  = core.BaseValue
	BaseValueForConstraint     = core.BaseValueForConstraint
	BearsActiveTokens          = core.BearsActiveTokens
	BeginIDMintScope           = core.BeginIDMintScope
	BetweenHandler             = core.BetweenHandler
	BinaryIntOpNative          = core.BinaryIntOpNative
	BinaryNumOpNative          = core.BinaryNumOpNative
	BodyEvalsResidual          = core.BodyEvalsResidual
	BodyTokens                 = core.BodyTokens
	Boru                       = core.Boru
	BuildReturnCountError      = core.BuildReturnCountError
	BuildReturnTypeError       = core.BuildReturnTypeError
	BuiltinIDForPath           = core.BuiltinIDForPath
	BuiltinInitError           = core.BuiltinInitError
	CanonValue                 = core.CanonValue
	CanonicalType              = core.CanonicalType
	CarrierOfLiteral           = core.CarrierOfLiteral
	CheckFullStack             = core.CheckFullStack
	CheckPassActive            = core.CheckPassActive
	ClassFields                = core.ClassFields
	ClassifyWeakRefusal        = core.ClassifyWeakRefusal
	CloneValue                 = core.CloneValue
	CloneWeakFlexListData      = core.CloneWeakFlexListData
	CloneWeakFlexMapData       = core.CloneWeakFlexMapData
	CloneWeakFlexXmlData       = core.CloneWeakFlexXmlData
	CmpHandler                 = core.CmpHandler
	CollectBodyLocalDefs       = core.CollectBodyLocalDefs
	ComparePathons             = core.ComparePathons
	CompareSignatures          = core.CompareSignatures
	CompareValues              = core.CompareValues
	ComputeCaptures            = core.ComputeCaptures
	ConcreteArgsMatch          = core.ConcreteArgsMatch
	ConstFoldAgrees            = core.ConstFoldAgrees
	ContextStoreLookup         = core.ContextStoreLookup
	ConvertIdealToList         = core.ConvertIdealToList
	ConvertIdealToMap          = core.ConvertIdealToMap
	CowDel                     = core.CowDel
	CowSet                     = core.CowSet
	DeepEqualerOwner           = core.DeepEqualerOwner
	DenotedTypeNode            = core.DenotedTypeNode
	DeqHandler                 = core.DeqHandler
	DeqKey                     = core.DeqKey
	DidYouMean                 = core.DidYouMean
	DispatchSig                = core.DispatchSig
	EqHandler                  = core.EqHandler
	ErrorCodeInitError         = core.ErrorCodeInitError
	ErrorCodes                 = core.ErrorCodes
	ExactEqual                 = core.ExactEqual
	ExitCode                   = core.ExitCode
	ExpandMacroForm            = core.ExpandMacroForm
	ExpandMacroWith            = core.ExpandMacroWith
	ExpandOptionalSigs         = core.ExpandOptionalSigs
	FillConcreteOptionDefaults = core.FillConcreteOptionDefaults
	FlatInstanceFields         = core.FlatInstanceFields
	FlatInstanceParts          = core.FlatInstanceParts
	FlattenDisjunctAlts        = core.FlattenDisjunctAlts
	FlexDeepCopy               = core.FlexDeepCopy
	FlexibleMatch              = core.FlexibleMatch
	FnDefHasSig                = core.FnDefHasSig
	FnDefsOverlap              = core.FnDefsOverlap
	FnSigMatchesSpec           = core.FnSigMatchesSpec
	FnSigSatisfiesSpec         = core.FnSigSatisfiesSpec
	FnUndefMatchesFnDef        = core.FnUndefMatchesFnDef
	FnValueOnlyZeroArgSigs     = core.FnValueOnlyZeroArgSigs
	FnValueZeroArg             = core.FnValueZeroArg
	ForceArityFunction         = core.ForceArityFunction
	ForceForwardFunction       = core.ForceForwardFunction
	ForceStackFunction         = core.ForceStackFunction
	FormatBigDecimal           = core.FormatBigDecimal
	FormatBigInteger           = core.FormatBigInteger
	FormatFloat                = core.FormatFloat
	FormatFnDef                = core.FormatFnDef
	FormatForPrint             = core.FormatForPrint
	FormatValueJSON            = core.FormatValueJSON
	ForwardLiteralOperand      = core.ForwardLiteralOperand
	FreshenDefault             = core.FreshenDefault
	FromNative                 = core.FromNative
	FullStack                  = core.FullStack
	GenBindingCarrier          = core.GenBindingCarrier
	GenerateID                 = core.GenerateID
	GrowthCeiling              = core.GrowthCeiling
	HasLockedSigs              = core.HasLockedSigs
	IDPrefixForType            = core.IDPrefixForType
	InferAndInstantiateSchema  = core.InferAndInstantiateSchema
	InferGenBindings           = core.InferGenBindings
	InferSchemaBindings        = core.InferSchemaBindings
	InstallCompiledRuntime     = core.InstallCompiledRuntime
	InstallFrameBinding        = core.InstallFrameBinding
	InstallGenBindingMap       = core.InstallGenBindingMap
	InstallGenCallBindings     = core.InstallGenCallBindings
	InstallSchemaUnifier       = core.InstallSchemaUnifier
	InstallWordExtension       = core.InstallWordExtension
	InstantiateSchema          = core.InstantiateSchema
	InvokeCallback             = core.InvokeCallback
	IsAppliableFn              = core.IsAppliableFn
	IsAtom                     = core.IsAtom
	IsBoolean                  = core.IsBoolean
	IsBoundedType              = core.IsBoundedType
	IsClassInstance            = core.IsClassInstance
	IsCloseParen               = core.IsCloseParen
	IsDefCleanup               = core.IsDefCleanup
	IsDelegationFnDef          = core.IsDelegationFnDef
	IsDispatchMod              = core.IsDispatchMod
	IsEnd                      = core.IsEnd
	IsError                    = core.IsError
	IsFlatInstance             = core.IsFlatInstance
	IsFlexList                 = core.IsFlexList
	IsFlexMap                  = core.IsFlexMap
	IsFlexNode                 = core.IsFlexNode
	IsFlexXml                  = core.IsFlexXml
	IsFnTypedCarrier           = core.IsFnTypedCarrier
	IsFnValueResidual          = core.IsFnValueResidual
	IsForward                  = core.IsForward
	IsFrameOpen                = core.IsFrameOpen
	IsFunctionRef              = core.IsFunctionRef
	IsGenInstRef               = core.IsGenInstRef
	IsGenParamValue            = core.IsGenParamValue
	IsGenSpec                  = core.IsGenSpec
	IsGetWord                  = core.IsGetWord
	IsGetrWord                 = core.IsGetrWord
	IsHostTypeBody             = core.IsHostTypeBody
	IsImplicitMap              = core.IsImplicitMap
	IsInertConst               = core.IsInertConst
	IsInertConstMember         = core.IsInertConstMember
	IsInternalErr              = core.IsInternalErr
	IsInternalError            = core.IsInternalError
	IsInternalMarker           = core.IsInternalMarker
	IsInterpString             = core.IsInterpString
	IsListShape                = core.IsListShape
	IsLiteralTypeBody          = core.IsLiteralTypeBody
	IsMapShape                 = core.IsMapShape
	IsMark                     = core.IsMark
	IsMicronType               = core.IsMicronType
	IsMicronValue              = core.IsMicronValue
	IsModuleFamilyValue        = core.IsModuleFamilyValue
	IsMove                     = core.IsMove
	IsNegation                 = core.IsNegation
	IsNeverShape               = core.IsNeverShape
	IsNominalAnchor            = core.IsNominalAnchor
	IsNone                     = core.IsNone
	IsNoneShape                = core.IsNoneShape
	IsOpenParen                = core.IsOpenParen
	IsParenExpr                = core.IsParenExpr
	IsPathon                   = core.IsPathon
	IsReach                    = core.IsReach
	IsRecordableLiteral        = core.IsRecordableLiteral
	IsRefinePrefab             = core.IsRefinePrefab
	IsResourceInstance         = core.IsResourceInstance
	IsResourceType             = core.IsResourceType
	IsReturnCheck              = core.IsReturnCheck
	IsSealedWord               = core.IsSealedWord
	IsSigTypeValue             = core.IsSigTypeValue
	IsSplice                   = core.IsSplice
	IsStore                    = core.IsStore
	IsSugar                    = core.IsSugar
	IsSurfaceType              = core.IsSurfaceType
	IsTypeLiteral              = core.IsTypeLiteral
	IsTypeParamNode            = core.IsTypeParamNode
	IsTypeSchema               = core.IsTypeSchema
	IsTypeValue                = core.IsTypeValue
	IsUnconstrainedTypeParam   = core.IsUnconstrainedTypeParam
	IsValidXmlName             = core.IsValidXmlName
	IsWeakFlexList             = core.IsWeakFlexList
	IsWeakFlexMap              = core.IsWeakFlexMap
	IsWeakFlexNode             = core.IsWeakFlexNode
	IsWeakFlexXml              = core.IsWeakFlexXml
	IsWordExtension            = core.IsWordExtension
	IsXmlInterp                = core.IsXmlInterp
	IsXmlValue                 = core.IsXmlValue
	LitVsConcreteOrder         = core.LitVsConcreteOrder
	LitVsLitOrder              = core.LitVsLitOrder
	LookupDefType              = core.LookupDefType
	LookupErrorCode            = core.LookupErrorCode
	LookupModuleCallChecker    = core.LookupModuleCallChecker
	LookupWordChecker          = core.LookupWordChecker
	MakeBoruError              = core.MakeBoruError
	MakeBoruErrorAt            = core.MakeBoruErrorAt
	MakeClassFieldValue        = core.MakeClassFieldValue
	MakeClassInstance          = core.MakeClassInstance
	MakeConvert                = core.MakeConvert
	MakeDepScalarSig           = core.MakeDepScalarSig
	MakeFieldValue             = core.MakeFieldValue
	MakeFieldValueR            = core.MakeFieldValueR
	MakeHandler                = core.MakeHandler
	MakeNodeHandler            = core.MakeNodeHandler
	MakeObjHandler             = core.MakeObjHandler
	MakeObject                 = core.MakeObject
	MakePathon                 = core.MakePathon
	MakeRecord                 = core.MakeRecord
	MakeRecordR                = core.MakeRecordR
	MakeResource               = core.MakeResource
	MakeScalarHandler          = core.MakeScalarHandler
	MakeScalarOptsHandler      = core.MakeScalarOptsHandler
	MakeTable                  = core.MakeTable
	MakeTableR                 = core.MakeTableR
	MakeWithOpts               = core.MakeWithOpts
	MapFieldBoolean            = core.MapFieldBoolean
	MapFieldFloat              = core.MapFieldFloat
	MapFieldInteger            = core.MapFieldInteger
	MapFieldString             = core.MapFieldString
	MatchSignature             = core.MatchSignature
	MemberBehavior             = core.MemberBehavior
	MergeCaptures              = core.MergeCaptures
	MicronFieldsEqual          = core.MicronFieldsEqual
	MintTestType               = core.MintTestType
	MintTypeParam              = core.MintTypeParam
	MixedFormStackSlotAny      = core.MixedFormStackSlotAny
	ModuleExportAbsenceStable  = core.ModuleExportAbsenceStable
	ModuleExportNames          = core.ModuleExportNames
	ModuleKind                 = core.ModuleKind
	ModuleNSOf                 = core.ModuleNSOf
	ModuleScopeBinding         = core.ModuleScopeBinding
	NegateType                 = core.NegateType
	NeqHandler                 = core.NeqHandler
	NewArgsStack               = core.NewArgsStack
	NewBigDecimal              = core.NewBigDecimal
	NewBigInteger              = core.NewBigInteger
	NewBoundedType             = core.NewBoundedType
	NewBoundedTypeBody         = core.NewBoundedTypeBody
	NewCapabilityRegistry      = core.NewCapabilityRegistry
	NewCheckState              = core.NewCheckState
	NewClassInstance           = core.NewClassInstance
	NewContextStack            = core.NewContextStack
	NewDefCleanup              = core.NewDefCleanup
	NewDefTable                = core.NewDefTable
	NewDepScalar               = core.NewDepScalar
	NewDisjunct                = core.NewDisjunct
	NewDispatchMod             = core.NewDispatchMod
	NewDynamicTypeTable        = core.NewDynamicTypeTable
	NewEnd                     = core.NewEnd
	NewEvalList                = core.NewEvalList
	NewEvalMap                 = core.NewEvalMap
	NewExitError               = core.NewExitError
	NewExtension               = core.NewExtension
	NewFlexList                = core.NewFlexList
	NewFlexMap                 = core.NewFlexMap
	NewFlexXml                 = core.NewFlexXml
	NewForward                 = core.NewForward
	NewFrameOpen               = core.NewFrameOpen
	NewFrameOpenSpan           = core.NewFrameOpenSpan
	NewGenInstRef              = core.NewGenInstRef
	NewGenParamValue           = core.NewGenParamValue
	NewGenSpec                 = core.NewGenSpec
	NewIdealRegistry           = core.NewIdealRegistry
	NewImplicitMap             = core.NewImplicitMap
	NewInterpString            = core.NewInterpString
	NewKeyVal                  = core.NewKeyVal
	NewModuleInstance          = core.NewModuleInstance
	NewModuleRegistry          = core.NewModuleRegistry
	NewNegation                = core.NewNegation
	NewOptionsType             = core.NewOptionsType
	NewParenExpr               = core.NewParenExpr
	NewPathon                  = core.NewPathon
	NewPathonFromString        = core.NewPathonFromString
	NewPathonVol               = core.NewPathonVol
	NewProcess                 = core.NewProcess
	NewProcessRuntime          = core.NewProcessRuntime
	NewReach                   = core.NewReach
	NewReachFromKeys           = core.NewReachFromKeys
	NewReadList                = core.NewReadList
	NewRegistry                = core.NewRegistry
	NewResourceInstance        = core.NewResourceInstance
	NewResourceType            = core.NewResourceType
	NewReturnCheck             = core.NewReturnCheck
	NewStore                   = core.NewStore
	NewStoreShapeCarrier       = core.NewStoreShapeCarrier
	NewStoreValue              = core.NewStoreValue
	NewStoreWithPrototype      = core.NewStoreWithPrototype
	NewSugar                   = core.NewSugar
	NewSurfaceType             = core.NewSurfaceType
	NewSyncWriter              = core.NewSyncWriter
	NewTableType               = core.NewTableType
	NewTape                    = core.NewTape
	NewTapeWith                = core.NewTapeWith
	NewType                    = core.NewType
	NewTypeSchema              = core.NewTypeSchema
	NewTypedList               = core.NewTypedList
	NewTypedListWithElements   = core.NewTypedListWithElements
	NewTypedMap                = core.NewTypedMap
	NewTypedMapWithEntries     = core.NewTypedMapWithEntries
	NewWeakFlexList            = core.NewWeakFlexList
	NewWeakFlexMap             = core.NewWeakFlexMap
	NewWeakFlexXml             = core.NewWeakFlexXml
	NewWordExtension           = core.NewWordExtension
	NewWordRef                 = core.NewWordRef
	NewWordUsurp               = core.NewWordUsurp
	NewXmlElement              = core.NewXmlElement
	NewXmlInterp               = core.NewXmlInterp
	NoMatchDetail              = core.NoMatchDetail
	NoMatchDiag                = core.NoMatchDiag
	NodeDeepCopy               = core.NodeDeepCopy
	NodifyValue                = core.NodifyValue
	NormalizeSig               = core.NormalizeSig
	NoteModuleExportAdd        = core.NoteModuleExportAdd
	OpenUnifyMap               = core.OpenUnifyMap
	OutputSigIsConcreteReturns = core.OutputSigIsConcreteReturns
	OutputSigValues            = core.OutputSigValues
	PadRight                   = core.PadRight
	Park                       = core.Park
	ParseFnParams              = core.ParseFnParams
	ParseFnReturns             = core.ParseFnReturns
	PathonContentEqual         = core.PathonContentEqual
	PatternsFromParams         = core.PatternsFromParams
	PoisonModuleExportGrowth   = core.PoisonModuleExportGrowth
	PopFrameArgs               = core.PopFrameArgs
	PopGenBindings             = core.PopGenBindings
	PopulateWeakFlexList       = core.PopulateWeakFlexList
	PopulateWeakFlexMap        = core.PopulateWeakFlexMap
	PopulateWeakFlexXml        = core.PopulateWeakFlexXml
	PredicateInputType         = core.PredicateInputType
	PrevBehavior               = core.PrevBehavior
	PrintHandler               = core.PrintHandler
	PrintstrHandler            = core.PrintstrHandler
	PushGenBindings            = core.PushGenBindings
	QuoteArgsFromParams        = core.QuoteArgsFromParams
	RankSignatures             = core.RankSignatures
	RebuildXmlFromTmpl         = core.RebuildXmlFromTmpl
	RegisterBytesBridge        = core.RegisterBytesBridge
	RegisterErrorCodes         = core.RegisterErrorCodes
	RegisterMicronRenderBridge = core.RegisterMicronRenderBridge
	RegisterModuleExportGrowth = core.RegisterModuleExportGrowth
	RenderCheckDiagnostic      = core.RenderCheckDiagnostic
	ReorderHintFor             = core.ReorderHintFor
	ReparentValue              = core.ReparentValue
	RequireConcreteList        = core.RequireConcreteList
	RequireConcreteMap         = core.RequireConcreteMap
	ResetModuleExportGrowth    = core.ResetModuleExportGrowth
	ResolveChildTypeExpr       = core.ResolveChildTypeExpr
	ResolveDefType             = core.ResolveDefType
	ResolveRef                 = core.ResolveRef
	ResolveSigChildParam       = core.ResolveSigChildParam
	ResolveSigType             = core.ResolveSigType
	ResolveTypeLiteralDef      = core.ResolveTypeLiteralDef
	ResolveTypeName            = core.ResolveTypeName
	ResolveTypePath            = core.ResolveTypePath
	ResolveUsurp               = core.ResolveUsurp
	ResolveWordValue           = core.ResolveWordValue
	ResolveWordsDeep           = core.ResolveWordsDeep
	ResolveWordsDeepR          = core.ResolveWordsDeepR
	ResourceDefKey             = core.ResourceDefKey
	RetagFlexElem              = core.RetagFlexElem
	RetagTypedContainerArgs    = core.RetagTypedContainerArgs
	RetagTypedContainerParam   = core.RetagTypedContainerParam
	RetagTypedContainerValue   = core.RetagTypedContainerValue
	ReturnCountErrorText       = core.ReturnCountErrorText
	ReturnTypeErrorText        = core.ReturnTypeErrorText
	RunPooled                  = core.RunPooled
	RunPooledSub               = core.RunPooledSub
	RunPooledTop               = core.RunPooledTop
	RunResolved                = core.RunResolved
	RunTrace                   = core.RunTrace
	RunTypedBind               = core.RunTypedBind
	RuntimeNoMatch             = core.RuntimeNoMatch
	SchemaInfoOf               = core.SchemaInfoOf
	SetAtomReferent            = core.SetAtomReferent
	SetIDSeed                  = core.SetIDSeed
	SeverityFor                = core.SeverityFor
	Shape                      = core.Shape
	SigArgMatches              = core.SigArgMatches
	SigArgType                 = core.SigArgType
	SigOrderArgs               = core.SigOrderArgs
	SigPattern                 = core.SigPattern
	SigTypeMatches             = core.SigTypeMatches
	SigTypeSummary             = core.SigTypeSummary
	SimplifyDisjunctAlts       = core.SimplifyDisjunctAlts
	SingleOverloadRecoverable  = core.SingleOverloadRecoverable
	SizeOf                     = core.SizeOf
	SizeOfAbove                = core.SizeOfAbove
	SizeOwner                  = core.SizeOwner
	SortSignatures             = core.SortSignatures
	SpliceExpand               = core.SpliceExpand
	StampModuleCallGates       = core.StampModuleCallGates
	StampedModuleCall          = core.StampedModuleCall
	StepLimitFor               = core.StepLimitFor
	StripAscribed              = core.StripAscribed
	SubstituteSelf             = core.SubstituteSelf
	SubstituteTypeParams       = core.SubstituteTypeParams
	SugarExpansion             = core.SugarExpansion
	SuggestNames               = core.SuggestNames
	SurfaceInfoOf              = core.SurfaceInfoOf
	TandHandler                = core.TandHandler
	TandReturnsFn              = core.TandReturnsFn
	TandValues                 = core.TandValues
	TcmpHandler                = core.TcmpHandler
	TnotHandler                = core.TnotHandler
	TnotReturnsFn              = core.TnotReturnsFn
	ToNative                   = core.ToNative
	TorHandler                 = core.TorHandler
	TorReturnsFn               = core.TorReturnsFn
	TraceColorize              = core.TraceColorize
	TraceHandler               = core.TraceHandler
	TraceVisibleLen            = core.TraceVisibleLen
	TraceWrap                  = core.TraceWrap
	TransplantExtension        = core.TransplantExtension
	TypeMembership             = core.TypeMembership
	TypeNameByID               = core.TypeNameByID
	TypeNameTable              = core.TypeNameTable
	TypeNodeOf                 = core.TypeNodeOf
	TypeParamName              = core.TypeParamName
	UnaryNumOpNative           = core.UnaryNumOpNative
	UndefinedWordDetail        = core.UndefinedWordDetail
	UnifyExplain               = core.UnifyExplain
	UnifyExplainR              = core.UnifyExplainR
	UnifyR                     = core.UnifyR
	UninstallFnSigs            = core.UninstallFnSigs
	UnionType                  = core.UnionType
	UsurpFunction              = core.UsurpFunction
	ValToString                = core.ValToString
	ValidateTypeNameParts      = core.ValidateTypeNameParts
	ValuesEqual                = core.ValuesEqual
	WalkBodyWords              = core.WalkBodyWords
	WeakRefusalError           = core.WeakRefusalError
	WithModuleNS               = core.WithModuleNS
	WithPos                    = core.WithPos
	XmlParts                   = core.XmlParts
)

func AsChildType(a0 core.Value) (core.ChildTypeInfo, error) { return core.AsChildType(a0) }

func AsClassInstance(a0 core.Value) (core.ClassInstanceInfo, error) { return core.AsClassInstance(a0) }

func AsClassType(a0 core.Value) (core.ClassTypeInfo, error) { return core.AsClassType(a0) }

func AsDisjunct(a0 core.Value) (core.DisjunctInfo, error) { return core.AsDisjunct(a0) }

func AsFloat(a0 core.Value) (float64, error) { return core.AsFloat(a0) }

func AsInteger(a0 core.Value) (int64, error) { return core.AsInteger(a0) }

func AsList(a0 core.Value) (core.ReadList, error) { return core.AsList(a0) }

func AsMap(a0 core.Value) (core.ReadMap, error) { return core.AsMap(a0) }

func AsMutableMap(a0 core.Value) (*core.OrderedMap, error) { return core.AsMutableMap(a0) }

func AsRecordType(a0 core.Value) (core.RecordTypeInfo, error) { return core.AsRecordType(a0) }

func AsString(a0 core.Value) (string, error) { return core.AsString(a0) }

func AsTableType(a0 core.Value) (core.TableTypeInfo, error) { return core.AsTableType(a0) }

func AsWord(a0 core.Value) (core.WordInfo, error) { return core.AsWord(a0) }

func BoundToKind(a0 *core.DepBound, a1 bool) core.DepKind { return core.BoundToKind(a0, a1) }

func Canon(a0 []core.Value) string { return core.Canon(a0) }

func CoerceBoolean(a0 core.Value) bool { return core.CoerceBoolean(a0) }

func DeepEqual(a0 core.Value, a1 core.Value) bool { return core.DeepEqual(a0, a1) }

func GenerateObjectTypeID() string { return core.GenerateObjectTypeID() }

func GetKey(a0 core.Value) string { return core.GetKey(a0) }

func Go(a0 core.Handler, a1 ...core.GoOpt) *core.GoImpl { return core.Go(a0, a1...) }

func InstallDef(a0 *core.Registry, a1 string, a2 core.Value, a3 ...bool) {
	core.InstallDef(a0, a1, a2, a3...)
}

func InstallFnDef(a0 *core.Registry, a1 string, a2 core.FnDefInfo, a3 ...bool) {
	core.InstallFnDef(a0, a1, a2, a3...)
}

func InstallType(a0 *core.Registry, a1 string, a2 core.Value) error {
	return core.InstallType(a0, a1, a2)
}

func InvokeBody(a0 *core.Registry, a1 core.Value, a2 []core.Value) ([]core.Value, error) {
	return core.InvokeBody(a0, a1, a2)
}

func IsBareTypeNode(a0 core.Value) bool { return core.IsBareTypeNode(a0) }

func IsCapitalisedName(a0 string) bool { return core.IsCapitalisedName(a0) }

func IsClassType(a0 core.Value) bool { return core.IsClassType(a0) }

func IsConcrete(a0 core.Value) bool { return core.IsConcrete(a0) }

func IsDisjunct(a0 core.Value) bool { return core.IsDisjunct(a0) }

func IsOptionsType(a0 core.Value) bool { return core.IsOptionsType(a0) }

func IsRecordShape(a0 core.Value) bool { return core.IsRecordShape(a0) }

func IsRecordType(a0 core.Value) bool { return core.IsRecordType(a0) }

func IsTableType(a0 core.Value) bool { return core.IsTableType(a0) }

func IsTypeBody(a0 core.Value) bool { return core.IsTypeBody(a0) }

func IsTypedList(a0 core.Value) bool { return core.IsTypedList(a0) }

func IsTypedMap(a0 core.Value) bool { return core.IsTypedMap(a0) }

func IsValueOfType(a0 core.Value, a1 core.Value) bool { return core.IsValueOfType(a0, a1) }

func IsWord(a0 core.Value) bool { return core.IsWord(a0) }

func New(a0 *core.Registry) *core.Engine { return core.New(a0) }

func NewAtom(a0 string) core.Value { return core.NewAtom(a0) }

func NewBoolean(a0 bool) core.Value { return core.NewBoolean(a0) }

func NewCarrier(a0 *core.Type) core.Value { return core.NewCarrier(a0) }

func NewClassType(a0 *core.Type, a1 core.ClassTypeInfo) core.Value { return core.NewClassType(a0, a1) }

func NewCloseParen() core.Value { return core.NewCloseParen() }

func NewDynamicCarrier(a0 *core.Type) core.Value { return core.NewDynamicCarrier(a0) }

func NewEnum(a0 []core.Value) core.Value { return core.NewEnum(a0) }

func NewError(a0 error) core.Value { return core.NewError(a0) }

func NewFloat(a0 float64) core.Value { return core.NewFloat(a0) }

func NewFnUndef(a0 core.FnUndefInfo) core.Value { return core.NewFnUndef(a0) }

func NewFunction(a0 core.FnDefInfo) core.Value { return core.NewFunction(a0) }

func NewInteger(a0 int64) core.Value { return core.NewInteger(a0) }

func NewList(a0 []core.Value) core.Value { return core.NewList(a0) }

func NewMap(a0 *core.OrderedMap) core.Value { return core.NewMap(a0) }

func NewMark(a0 string, a1 ...core.Value) core.Value { return core.NewMark(a0, a1...) }

func NewMove(a0 string, a1 string) core.Value { return core.NewMove(a0, a1) }

func NewMoveCont(a0 string, a1 string, a2 *core.ForCont) core.Value {
	return core.NewMoveCont(a0, a1, a2)
}

func NewMoveIf(a0 string, a1 string, a2 *core.IfCont) core.Value { return core.NewMoveIf(a0, a1, a2) }

func NewNone() core.Value { return core.NewNone() }

func NewOpenParen() core.Value { return core.NewOpenParen() }

func NewOrderedMap() *core.OrderedMap { return core.NewOrderedMap() }

func NewRecordType(a0 *core.OrderedMap) core.Value { return core.NewRecordType(a0) }

func NewSplice(a0 core.Value) core.Value { return core.NewSplice(a0) }

func NewString(a0 string) core.Value { return core.NewString(a0) }

func NewTop(a0 *core.Registry) *core.Engine { return core.NewTop(a0) }

func NewTypeLiteral(a0 *core.Type) core.Value { return core.NewTypeLiteral(a0) }

func NewValueRaw(a0 *core.Type, a1 core.Payload) core.Value { return core.NewValueRaw(a0, a1) }

func NewWord(a0 string) core.Value { return core.NewWord(a0) }

func NewWordModified(a0 string, a1 int, a2 bool, a3 bool) core.Value {
	return core.NewWordModified(a0, a1, a2, a3)
}

func NextMarkID() string { return core.NextMarkID() }

func ParseFnDef(a0 *core.Registry, a1 []core.Value) (core.FnDefInfo, error) {
	return core.ParseFnDef(a0, a1)
}

func ParseFnUndefSpec(a0 *core.Registry, a1 []core.Value) (core.FnUndefInfo, error) {
	return core.ParseFnUndefSpec(a0, a1)
}

func PathOf(a0 core.Value) core.Value { return core.PathOf(a0) }

func ResolveBuiltinTypeName(a0 string) (*core.Type, bool) { return core.ResolveBuiltinTypeName(a0) }

func ResolveFieldType(a0 *core.Registry, a1 core.Value) core.Value {
	return core.ResolveFieldType(a0, a1)
}

func RunInCheck() core.GoOpt { return core.RunInCheck() }

func StoreKey(a0 core.Value) string { return core.StoreKey(a0) }

func TypeNameOf(a0 core.Value) string { return core.TypeNameOf(a0) }

func TypeOf(a0 core.Value) core.Value { return core.TypeOf(a0) }

func TypePathOf(a0 core.Value) string { return core.TypePathOf(a0) }

func Unify(a0 core.Value, a1 core.Value) (core.Value, bool) { return core.Unify(a0, a1) }

func UninstallDef(a0 *core.Registry, a1 string) { core.UninstallDef(a0, a1) }

func ValidateWordName(a0 string) error { return core.ValidateWordName(a0) }

func ValueType(a0 core.Value) *core.Type { return core.ValueType(a0) }
