// Code generated by piecetool -facade; DO NOT EDIT.
//
// The eng facade over the core module (design/ENG-FOUR-PIECE.0.md
// Stage 4): type aliases are zero-cost, the function wrappers are thin
// enough to inline, and set-once vars mirror by value at init (core's
// package init completes first). Mutable slot tables are NOT mirrored —
// their installers write core.X directly.
package eng

import (
	"context"
	"io"
	"math/big"
	"regexp"
	"time"

	check "github.com/boru-lang/boru/check/go"
	compiler "github.com/boru-lang/boru/compiler/go"
	core "github.com/boru-lang/boru/core/go"
	apd "github.com/cockroachdb/apd/v3"
)

var _ = context.Canceled
var _ io.Reader
var _ big.Int
var _ regexp.Regexp
var _ time.Time
var _ apd.Decimal
var _ = core.TheInactiveEmit
var _ = check.DispatchBraid
var _ compiler.EmitState

type ()

const (
	FnAnalysisQuota = check.FnAnalysisQuota
)

// Cold func-value re-exports: exported core funcs no suite calls
// through the facade (API surface only — lang re-export vars,
// short-circuited operands, external embedders). A var of func type
// keeps every reference site compiling verbatim with no wrapper body
// to leave uncovered; a name moves back up to a wrapper func when a
// hot path starts calling it.
var (
	AdoptShapeValue        = check.AdoptShapeValue
	AnalyseFnBody          = check.AnalyseFnBody
	BodyFreeForFallback    = check.BodyFreeForFallback
	BodyHasSentinel        = check.BodyHasSentinel
	BodyHasSentinelDeep    = check.BodyHasSentinelDeep
	CheckListIndex         = check.CheckListIndex
	FnAnalysisKey          = check.FnAnalysisKey
	NewCarrierTypedListLen = check.NewCarrierTypedListLen
	ShapeFieldRead         = check.ShapeFieldRead
	StaticListLen          = check.StaticListLen
)

func AnalyseLoopBody(a0 *core.Registry, a1 core.Value, a2 []string, a3 []core.Value, a4 bool) []core.Value {
	return check.AnalyseLoopBody(a0, a1, a2, a3, a4)
}

func DataListElemTypeFromValue(a0 core.Value) *core.Type { return check.DataListElemTypeFromValue(a0) }

func ElementCarrierFromValue(a0 core.Value) core.Value { return check.ElementCarrierFromValue(a0) }

func NewElementCarrier(a0 *core.Type) core.Value { return check.NewElementCarrier(a0) }

func ReturnsFreshInstance(a0 ...int) core.ReturnsFunc { return check.ReturnsFreshInstance(a0...) }
