// Command genhelp pre-computes help example results by running each
// expression through the AQL native. Output is written to
// lang/go/engine/help/examples_gen.go as a static map.
//
//go:generate go run .
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/aql-lang/aql/eng/go/parser"
	"github.com/aql-lang/aql/lang/go/native"
	"github.com/aql-lang/aql/lang/go/native/help"
)

// outputPath returns the absolute path of the generated file, derived from
// this source file's location so it works regardless of the working
// directory: <repo>/cmd/go/genhelp/main.go -> <repo>/lang/go/native/help/examples_gen.go
func outputPath() string {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	return filepath.Join(repoRoot, "lang", "go", "native", "help", "examples_gen.go")
}

func main() {
	reg, err := native.DefaultRegistry()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genhelp: %v\n", err)
		os.Exit(1)
	}
	reg.SetParseFunc(parser.Parse)

	// Collect all example expressions across all words.
	// Use a fresh registry per word to avoid state leakage between examples.
	results := map[string]string{}
	words := help.Words()
	sort.Strings(words)

	for _, word := range words {
		info := native.BuildFuncInfo(reg, word)
		if info == nil {
			continue
		}
		exprs := help.ExampleExprs(*info)

		// Fresh registry per word.
		wordReg, err := native.DefaultRegistry()
		if err != nil {
			fmt.Fprintf(os.Stderr, "genhelp: %v\n", err)
			os.Exit(1)
		}
		wordReg.SetParseFunc(parser.Parse)

		for _, expr := range exprs {
			if _, done := results[expr]; done {
				continue
			}
			result, err := evalExpr(wordReg, expr)
			if err != nil || result == "" {
				continue // skip errors (side-effect-only words, etc.)
			}
			results[expr] = result
		}
	}

	// Generate Go source file.
	var b strings.Builder
	b.WriteString("// Code generated by cmd/go/genhelp; DO NOT EDIT.\n\n")
	b.WriteString("package help\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\texampleResults = map[string]string{\n")

	// Sort keys for deterministic output.
	keys := make([]string, 0, len(results))
	for k := range results {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		b.WriteString(fmt.Sprintf("\t\t%q: %q,\n", k, results[k]))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	outPath := outputPath()
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "genhelp: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "genhelp: wrote %d examples to %s\n", len(results), outPath)
}

func evalExpr(reg *native.Registry, expr string) (string, error) {
	vals, err := parser.Parse(expr)
	if err != nil {
		return "", err
	}

	// Suppress output from print/trace.
	savedOut := reg.Output
	reg.Output = io.Discard
	defer func() { reg.Output = savedOut }()

	eng := native.NewTop(reg)
	result, err := eng.Run(vals)
	if err != nil {
		return "", err
	}
	var parts []string
	for _, v := range result {
		parts = append(parts, v.String())
	}
	return strings.Join(parts, " "), nil
}
