package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRunGeneratesExamples drives the exact production pipeline into a
// temp path and validates the generated source's shape and a few known
// stable rows.
func TestRunGeneratesExamples(t *testing.T) {
	if testing.Short() {
		t.Skip("run evaluates every word's examples; skipped under -short")
	}
	out := filepath.Join(t.TempDir(), "examples_gen.go")
	var errb bytes.Buffer
	if err := run(out, &errb); err != nil {
		t.Fatalf("run: %v", err)
	}
	src, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read generated: %v", err)
	}
	s := string(src)
	for _, want := range []string{
		"// Code generated by cmd/go/genhelp; DO NOT EDIT.",
		"package help",
		"exampleResults = map[string]string{",
		`"2 dup":`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
	if !strings.Contains(errb.String(), "genhelp: wrote") {
		t.Errorf("run progress line missing, got %q", errb.String())
	}
	// Determinism vs the committed file (the same pipeline `go generate`
	// runs) — a mismatch means genhelp drifted or the committed file is
	// stale. The `class` example embeds a per-process minted type ID
	// (Ideal/Class/T_…), so that one row is excluded from the comparison.
	committed, err := os.ReadFile(outputPath())
	if err != nil {
		t.Fatalf("read committed: %v", err)
	}
	if got, want := stripMintedIDs(s), stripMintedIDs(string(committed)); got != want {
		t.Errorf("generated output differs from committed examples_gen.go — regenerate with `go run ./genhelp`")
	}
}

// stripMintedIDs drops rows whose value embeds a freshly-minted type ID,
// which legitimately differs per generation run.
func stripMintedIDs(src string) string {
	lines := strings.Split(src, "\n")
	kept := lines[:0]
	for _, l := range lines {
		if strings.Contains(l, "Ideal/Class/T_") {
			continue
		}
		kept = append(kept, l)
	}
	return strings.Join(kept, "\n")
}

// TestRunRejectsUnwritablePath pins the write-error path.
func TestRunRejectsUnwritablePath(t *testing.T) {
	if testing.Short() {
		t.Skip("run evaluates every word's examples; skipped under -short")
	}
	var errb bytes.Buffer
	err := run(filepath.Join(t.TempDir(), "no-such-dir", "x.go"), &errb)
	if err == nil || !strings.Contains(err.Error(), "write") {
		t.Fatalf("run into missing dir: got %v, want write error", err)
	}
}

func TestRenderSourceDeterministic(t *testing.T) {
	m := map[string]string{"b expr": "2", "a expr": "1"}
	got := renderSource(m)
	// Keys sorted, values quoted.
	ia, ib := strings.Index(got, `"a expr"`), strings.Index(got, `"b expr"`)
	if ia < 0 || ib < 0 || ia > ib {
		t.Errorf("renderSource ordering wrong:\n%s", got)
	}
	if renderSource(m) != got {
		t.Error("renderSource is not deterministic")
	}
	// Empty map still renders a valid skeleton.
	empty := renderSource(nil)
	if !strings.Contains(empty, "exampleResults = map[string]string{") {
		t.Errorf("empty renderSource missing skeleton:\n%s", empty)
	}
}
